### ISSUE TITLE
SqlServerCompact does not support DateTime2

### ISSUE THREAD

**Issue by Daniel79WI** [aspnet/EntityFramework6#100]
The SqlServerCompact provider seems not to support DateTime2 data types. When I try to create a sql compact database, I get the error message that this type cannot be found in the list of store types (exception from the GetStoreTypeFromName function in the DbProviderManifestExtensions).

This following lines are a comparison of the provider manifest resources between SqlServer and SqlServerCompact.

ProviderManifest of the EntityFramework.SqlServer Provider:

90         <Type Name="datetime2" PrimitiveTypeKind="DateTime"> 
91             <FacetDescriptions> 
92                 <Precision Minimum="0" Maximum="7" DefaultValue="7" Constant="false" /> 
93             </FacetDescriptions> 
94         </Type> 

In the ProviderManifest of the EntityFramework.SqlServerCompact this entry is missing.

Is this a bug or is this Feature really not supported?

**Comment by ErikEJ** [comment]
The error message is correct, SQL Server Compact does not support datetime2, you must use datetime instead. The SQL Server Compact provider has support for a limited number of SQL Server data types.

**Comment by Daniel79WI** [comment]
But the documentation at Technet writes that the data type is supported in Sql Server Compact 4.0.
(https://technet.microsoft.com/en-us/library/bb896140(v=sql.110).aspx)

**Comment by ErikEJ** [comment]
Yeah, that page has caused much confusion - it relates to what data types can be merge replicated to SQL CE from SQL Server - the actual page you are looking for is here: https://technet.microsoft.com/en-us/library/ms172424(v=sql.110).aspx
