### ISSUE TITLE
Can't customize RelationshipMultiplicity when generating code from existing database

### ISSUE THREAD

**Issue by kayle** [aspnet/EntityFramework6#102]
I'd like to change a few navigation properties to be 1:0..1 instead of 1:* when reverse engineering code from an existing database. I'm unable to find any hooks to do so. I tried inserting the following in Context.cs.t4, but it causes problems like using the wrong pluralization:

```
var config = (MultiplicityConfiguration) navigationPropertyMultiplicityConfiguration;
var original = config.RightNavigationProperty;
isDefaultMultiplicity = false;
config.RightNavigationProperty = 
    NavigationProperty.Create(original.Name, original.TypeUsage, original.RelationshipType, 
    AssociationEndMember.Create(original.FromEndMember.Name, (RefType) original.FromEndMember.TypeUsage.EdmType, RelationshipMultiplicity.One, original.FromEndMember.DeleteBehavior, null),
    original.ToEndMember,
    null);	
```

**Comment by rowanmiller** [comment]
In EF6 there isn't a place that allows you to manipulate the model (though we did introduce this in EF Core). Unfortunately, in EF6 you are really limited to manipulating the code that is generated. So in this case, you would need to adjust the template to generate code that doesn't accurately reflect the input model, but does generate the model you want.

**Comment by LJ9999** [comment]
Get rid of pluralization. It's worthless and keeps getting in my way when it doesn't work. I don't want it but it keeps popping up. Any DBA worth their salt will tell you it's a stupid naming convention, too.
