### ISSUE TITLE
enable-migrations causes "the project 'project' failed to build.

### ISSUE THREAD

**Issue by JamieL22** [aspnet/EntityFramework6#1062]
Describe what is not working as expected.

The command "enable-migrations"  according to many tutorial sessions, this one included, always produces the same error result **The project 'MigrationsDemo' failed to build.** (or CodeFirstDemo from Udemy - another example  https://bah.udemy.com/entity-framework-tutorial/learn/lecture/3243042#overview)

There is some indication after googling - that the migrations are enabled automatically when the job runs the first time and sets up a database in the "(localdb)\MsSqlLocalDb"  (also localdb? poorly documented here)
WHEN running the "enable-migrations" command after the database is setup, there is a message about scaffolded migration.  (Didn't get that far).

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
The project 'MigrationsDemo' failed to build.

_Detected database created with a database initializer. Scaffolded migration '201907172347434_InitialCreate' corresponding to existing database. To use an automatic migration instead, delete the Migrations folder and re-run Enable-Migrations specifying the -EnableAutomaticMigrations parameter._

Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

I did not vary from the script above.  I am running SSMS 2017 with SQL Server 2017 Developer and Visual Studio 2017 Professional.

# Create Console App (.NET Framework) called MigrationsDemo
# Install-Package EntityFramework from Package Manager Console
# Add Class named Model with code from link
# Update Program.cs with code from link
# Run Package and wait for console to show "Another Blog" (press any key to exit)
# Run the Enable-Migrations command in Package Manager Console

***What may have fixed this for me - as it works now - was opening the (localdb)\MsSqlLocalDB.   Once that was created, and opened for a first time with SSMS, the enable-migrations command began to run.   If I am correct, the part that is missing is the "open the database" portion.  Or perhaps another command that would ensure the data is committed to this database called (localdb)\MsSqlLocalDB 

### Further technical details
EF version: (found in project.csproj or packages.config is 6.2.0)
Database Provider: (e.g. EntityFramework.SqlServer) presumably the one in the command above which is System.Data.SqlClient.
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by bricelam** [comment]
This my no longer be a problem in 6.3.0. I removed the code that builds the project twice during Enable-Migrations

**Comment by JamieL22** [comment]
Thank you bricelam
