### ISSUE TITLE
DbSet.SqlQuery exception for entity with complex type property

### ISSUE THREAD

**Issue by protokol** [aspnet/EntityFramework6#107]
When DbSet.SqlQuery is used to retrieve entities that contain complex types as properties, the following exception is thrown.

System.InvalidOperationException:  Cannot create a value for property '{name}' of type '{complex-type}'. Only properties of primitive or enumeration types are supported.

Example:

    public class MyDbContext : DbContext
    {
        public DbSet<Person> People { get; set; }
    }

    public class Person
    {
        public virtual int Id { get; set; }
        public virtual PersonName Name { get; set; }
    }

    public class PersonName
    {
        public string First { get; set; }
        public string Last { get; set; }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyDbContext())
            {
                var query = db.People.SqlQuery("SELECT [Id], [Name_First], [Name_Last] FROM [dbo].[People]");
                query.Count(); // throws exception
                query.ToList(); // throws exception
            }
        }
    }

**Comment by rowanmiller** [comment]
This is unfortunately by design. Raw SQL queries to entities with complex types was never implemented. We would consider a contribution to enable this. But it is not something our team is planning to tackle.

**Comment by kristjank** [comment]
@protokol how can I reach you via e-mail or any other channels.

**Comment by kristjank** [comment]
@protokol

**Comment by ChrisSchaller** [comment]
@kristjank how did you go with this, doesn't seem like a big deal, I don't know where to start but I'm happy to help out. 
As explained in this post on SO: https://stackoverflow.com/a/37554389/1690217 the work around now is to materialize into an intermediary structure and then parse that into one with complex types.
