### ISSUE TITLE
Entity Framework has inconsistent behaviour with int/tinyint keys

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1075]
In a simple EF C# project, I experience different behaviour when a key value is defined as byte (tinyint) or int.

Repro steps:
Build the attached solution
Debug the project.

On line 76, a System.InvalidOperation exception occurs.

Continue  - deletes the database.

Modify the code to use the int version of the Post class Id.
Delete the Migrations folder/code.
Use Package Manager Console to run the command:
  Add-Migration InitialCreate

Rebuild the project
Debug the project

This time there's no exception, and the DB entries are created as expected.

Although this example uses EFCore, the same occurs with EF6.

Why is there this inconsitency between use of byte (tinyint) and int type for the key?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/630464/entity-framework-has-inconsistent-behaviour-with-i.html
VSTS ticketId: 941222_
_These are the original issue comments:_

Visual Studio Feedback System on 7/2/2019, 08:26 PM (22 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/3/2019, 11:52 PM (21 days ago): <markdown><p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
`tinyint` keys are not generated by default since the key space is very small leading to significant risk of collisions when not used carefully.

**Comment by Dave-Lowndes** [comment]
@ajcvickers Arthur, why does the code even compile then? The reason for the issue needs to be made clear to the developer. It's pretty lousy having this be an ambiguous run-time problem. Can you improve this situation?

**Comment by ajcvickers** [comment]
@Dave-Lowndes Not sure what you mean--can you be more specific about what your expectations are?

**Comment by Dave-Lowndes** [comment]
@ajcvickers In the example I provided, it compiles and works fine with an int key. If the key is changed to be byte (tinyint), the code still compiles fine, but fails at run-time with a vague exception. If you've made a design decision to disallow tinyint keys (I don't know why you'd have that restriction since the DB table could well be intended to only have a very small number of records) the code should ideally not have compiled - with an error that clearly identified this design decision.

**Comment by ajcvickers** [comment]
@Dave-Lowndes The design decision defines the default behavior for `tinyint` keys. It's not about not using them.

**Comment by Dave-Lowndes** [comment]
@ajcvickers It's my turn to ask you what you mean now :) Fundamentally, I don't understand why my example code fails at run-time when the Key is defined to be byte.
