### ISSUE TITLE
Adding Entity Model in EF 6.3

### ISSUE THREAD

**Issue by GuyBenhaim** [aspnet/EntityFramework6#1087]
Hello,
I have successfully installed .Net Core 3.0 PV7,&nbsp; EF6.3 PV7 and using VS 2019 16.3 all in <strong>Windows 10 PC</strong>.

I wanted to add a new Data First model to my 3.0 project but, the ADO.Net option does NOT exist under Project > Add > New Item.  Shouldn't this option be there? (Note project target is Windows)

Can you describe another way to build a model directly from SQL DB?
Or, how do we build the model in .Net Framework, and port to EF6.3?

Thx

**Comment by ajcvickers** [comment]
@GuyBenhaim Yes, currently the EF Designer does not support .NET Core or the new project system. See https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-7-and-entity-framework-6-3-preview-7/

**Comment by GuyBenhaim** [comment]
So, what is the suggested way of porting my current model to the new Core 3.0 & EF 6.3 project?
Could you please direct me to concrete instructions?
Thx

**Comment by bricelam** [comment]
Docs:
* [Porting an EF6 EDMX-Based Model to EF Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)
* [Porting an EF6 Code-Based Model to EF Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code)

**Comment by ErikEJ** [comment]
@bricelam  I think @GuyBenhaim asked for a guide for porting an EDMX based .NET Framework project with EF 6.2 to and EDMX based .NET Core 3.0  project  with EF 6.3

**Comment by bricelam** [comment]
Ah, it's broken in Preview 7. But after PR #1095 it will be as simple as copying the files (*.edmx, *.cs, and App.config) into the .NET Core project

**Comment by GuyBenhaim** [comment]
Thanks for clarifying, @ErikEJ
Of course, no problem with doing some work for porting but, it yet unclear to me what that work is.

**Comment by GuyBenhaim** [comment]
Hi @bricelam, when would you expect #1095 done, including porting guidelines?

**Comment by GuyBenhaim** [comment]
Hello,
Any conclusion, or info?
Thx

**Comment by ajcvickers** [comment]
@GuyBenhaim What specifically are you waiting for?

**Comment by GuyBenhaim** [comment]
Arthur, I'm looking for instructions on how to port edmx data-model from **.Net Framework/EF6**  to **.Net Core3.0/EF6.3-pv7**, or to understand when would that be possible?
Alternatively, what is the second-best way to generate a DB-first data model in Core3.0/EF6.3-pv7.
Thx
