### ISSUE TITLE
Error after adding ADO.NET Entity Data Model in VS Dev15 shell

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#11]
I have a winform app and it does build successfully. Then I tried to add a ADO.NET Entity Data Model into my project which connects to sqlcldb4 RS_NorthWind database, and after that I tried to rebuild it, it threw me some errors (refer to picture attached). 
I just tried the scenario in another machine and it still reproes. So I believe the failure is common. I installed from the following path \\cpvsbuild\drops\VS\preview\layouts\x86ret\25107.00\enu\vs\enterprise\dvd, and the repro step is pretty simple:
1.	Create a WinForm application
2.	Add a new item “ADO.NET Entity Data Model”
3.	Choose “EF Designer from database”
4.	Click “New Connection…”, add RS_Northwind database from sqlcldb4 using Windows Authentication
5.	Only choose “Customers” table, and click “Finish”
6.	It will pop up some security warnings saying “Running this text template can potentially harm your computer. Do not run it if you obtained it from an untrusted source.”, and hit “OK”
7.	Then in the Error List window, there are already several errors shown up.
8.	If you rebuild the project, it will give the errors that we see in the picture.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2894

**Comment by rowanmiller** [comment]
lajones wrote Mar 24 at 10:43 AM [x] 


Blocked on VS internal bug: DevDiv 205506. 

 The problems seems to be that the TextTemplating engine for .tt files with Custom Tool set to "TextTemplateFileGenerator" does not work on a 32-bit Windows 10 OS. My speculation is that the CSC process being kicked off in the background needs different flags to reference the DLLs correctly on 32-bit but could be a different problem.



lajones wrote Apr 5 at 4:38 PM [x] 


Notes from the investigation into the DEVDIV bug. Dev15 VS now no longer stores EnvDTE (and other DLLs) in the GAC. EnittyFramework creates .tt files which contain lines such as the following:

 <#@ assembly name="EnvDTE” #>

 This finds EnvDTE from the GAC, but does not find it if EnvDTE.dll is stored in one of the directories which VS searches (e.g. PublicAssemblies). This is a regression and the VS team will be fixing it.

 In the meantime there is a workaround which is to change the above to read:

 <#@ assembly name="EnvDTE.dll” #>

 (Note: the .dll suffix).

 So to fix this temporarily (for CS projects using EF6) you can change the file in ...\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\Templates\Includes\EF6.Utility.CS.ttinclude so that all the <#@ assembly #> lines include the .dll suffix. Note: you will need administrator privileges to do this.

**Comment by lajones** [comment]
This was fixed by the TextTemplating team some while back. We no longer have this problem.

**Comment by mahsaAminiyan** [comment]
I have have the same problem .pls help me

**Comment by HammedAbdulazeez** [comment]
I have the same issue as well and the VS will freeze every time i click on the dialogue that appears. Please i need your help...
