### ISSUE TITLE
Entity Properties with different column order as composite Key and ForeignKey 

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#110]
I have two entities with properties, "PropA" and "PropB" that are used a parts of the entity composite primary key.

Entity1 is associated with a database table that has a composite primary key [PropA, PropB].

Entity2 is associated with a database table that has a composite primary key with the order reversed [PropB, PropA].

And so the entity definitions associate Key and ColumnOrder values accordingly 

I am trying to define a 1-to-many relationship from Entity1 to Entity2 using Fluent API. 
I have tried using
   .ForeignKey( x => new { x.PropA, x.PropB})
and
   .ForeignKey( x => new { x.PropB, x.PropA})

One fails to fill the virtual navigation properties because it is using the value of Entity2.PropA as when looking for Entity1.ProbB objects, e.g. SELECT ... WHERE (fieldPropB="valueOfEntity2PropA", fieldPropA="valueOfEntity2PropB"

The other throws a run time error
ERROR (3015): Problem in Mapping Fragments xxx Insufficient mapping: Foreign key must be mapped to some AssociationSet or ...

The only way I could get this work was to have the both entities agree on the ordering within the composite primary and then use that ordering in the ForeignKey.

Is in possible for an entity property to have one order when used as a key and another when used as a foreignkey?

Thanks
Daniel

**Comment by dlipkie** [comment]
110 and 113 are not dups.

110 concerns the interaction between two different entities.

113 concerns properties within a single entity

**Comment by dlipkie** [comment]
Rowan, Thanks for clarification you added to #113 ... look forward to finding out where i missed the boat on understanding this topic.

**Comment by AndriySvyryd** [comment]
@dlipkie Could you share a small project with a repro for this issue?
If you are using the primary key properties for the foreign key you are creating a 1-to-1 relationship, correct?

**Comment by AndriySvyryd** [comment]
Closing this for now, but will reopen once we get the requested code.
