### ISSUE TITLE
Retrieving the ROW_NUMBER

### ISSUE THREAD

**Issue by rendmath** [aspnet/EntityFramework6#112]
There doesn't currently seem to be a way to retrieve the ROW_NUMBER along the results of a request. This may prove to be problematic. As an example among others, some UI component frameworks require this ability for their virtualization features.

Because when you know that the current selected item in your drop down list has an ID of 77, and the user opens the drop down panel, you need to be able to determine the position of item 77 inside the ordered set, in order to fetch the appropriate page.

It would require the ability to execute this kind of request:
context.Products.Select((p, i) => new { p  = p, i = i }).Where(t => t.p.Id == 77).Select(t => t.i);

This SO claims that there is currently no solution to this problem in EF6:
http://stackoverflow.com/questions/1165028/how-do-i-add-row-number-to-a-linq-query-or-entity

Are there any plans to implement this in either EF6 or EF7?

**Comment by rowanmiller** [comment]
This is not something we are planning to implement in EF6. We may look at it in the future for EF Core (formerly EF7).

The best bet at the moment is probably to calculate the index in-memory after getting the results (or use IndexOf on the loaded result set).
