### ISSUE TITLE
Can Entity Property have different Column Order when it is being use a Key and as a ForeignKey?

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#113]
Thanks
Daniel

**Comment by rowanmiller** [comment]
Closing as a dupe of https://github.com/aspnet/EntityFramework6/issues/110 - we will follow up there

**Comment by dlipkie** [comment]
110 and 113 are not dups.

110 concerns the interaction between two different entities.

113 concerns properties within a single entity

**Comment by rowanmiller** [comment]
Sorry, I just meant that we'd cover all this as part of the answer to #110.

**Comment by dlipkie** [comment]
Thanks for clarification ... look forward to finding out where i missed the boat on understanding this topic.
