### ISSUE TITLE
Entity has four key properties used in multiple relationships.

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#114]
I have an Oracle DB and would like to create an entity. The entity is on the 1 side of multiple 1-to-many relationships.

E.g. I would like Relationship A to use 1 and 3 and Relationship B to 2, 3 & 4.

Is this possible?

Daniel

**Comment by rowanmiller** [comment]
In general, yes. But you'd need to validate your exact scenario.
