### ISSUE TITLE
Enable migrations - preview 8

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/EntityFramework6#1143]
VS 16.3.0 preview 2
.NET Core 3 preview 8
.NET 4.8

Create 4 class libraries:

ClassLibrary.NET (targets .NET 4.7.2)
ClassLibraryNetCore (targets .NET Core 3 p8)
ClassLibraryStandard(.NET standard 2.1 p8)
ClassLibraryMulti (multi target all)

Add EF 6.3 p8 to all of them and add an empty DbContext.

Try to use enable-migrations on each of them:

> enable-migrations -project classlibrary.net -startupproject classlibrary.net

 fails with:

![image](https://user-images.githubusercontent.com/271656/63045508-68a6a880-bec8-11e9-9100-cd5fdaaf5385.png)

> enable-migrations -project classlibrary.net -startupproject **classlibrarynetcore**

oddly this works and enables migrations on the .net project.

> enable-migrations -project classlibrarynetcore -startupproject classlibrarynetcore

works.

> enable-migrations -project classlibrarynetstandard -startupproject classlibrarynetstandard

fails with:

![image](https://user-images.githubusercontent.com/271656/63045788-fc787480-bec8-11e9-972c-d03b1b412a2b.png)

Which seems odd since surely the .NET core tools can handle a .NET standard assembly?

> enable-migrations -project classlibrarymulti -startupproject classlibrarymulti

works.

Should the tools just work in all of these scenarios?

Demo solution: [EfMigrate.zip](https://github.com/aspnet/EntityFramework6/files/3502732/EfMigrate.zip)

**Comment by bricelam** [comment]
Does `-Verbose` give any additional information about the first error?

**Comment by bricelam** [comment]
> Surely the .NET core tools can handle a .NET standard assembly?

No. The tools need to execute code. .NET Standard is a spec. There is no runtime associated with it. NuGet won't restore all the assets to run it on a different runtime (e.g. .NET Core) unless it also targets that framework.

**Comment by PhilPJL** [comment]
> Does -Verbose give any additional information about the first error?

No, -Verbose, -Debug both give the same error.  No additional info.

> No. The EF tools need to execute code. .NET Standard is a spec.

But .Net Standard 2.1 can be consumed/referenced by .Net Core 3 so why can't your tools handle it?

**Comment by bricelam** [comment]
One change we made on EF Core is to execute code using the startup project. This enabled you to create a dummy console project to use for migrations on .NET Standard class libraries. But making that change on EF6 could break some workflows.

**Comment by bricelam** [comment]
### Workaround

To avoid this bug, add a dummy `app.config` file to the project.
