### ISSUE TITLE
Schema breaking when attempting to reuse entity in Table Valued Function return type

### ISSUE THREAD

**Issue by WillSullivan** [aspnet/EntityFramework6#116]
This question is primarily about another framework, https://github.com/Dixin/EntityFramework.Functions which adds code-first support for things like Table Valued Functions.

I'm investigating why, when you try to reuse an entity type as a return type for a function, it breaks the schema representation of the database within EF.  Specifically, I get these errors:

> Schema specified is not valid. Errors: 
(0,0) : error 0040: The Type Int32 is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type String is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type Int32 is not qualified with a namespace or alias. Only primitive types can be used without qualification.
(0,0) : error 0040: The Type Int32 is not qualified with a namespace or alias. Only primitive types can be used without qualification.

The types referenced by these errors match the four properties within the model I'm attempting to reuse.

As I read the code for entityframework.functions, the return type for the function is constructed here 

https://github.com/Dixin/EntityFramework.Functions/blob/master/EntityFramework.Functions/Function.DbModel.cs#L439

The relevant lines where the RowType is created

    EntityType modelReturnParameterEntityType = modelReturnParameterStructuralType as EntityType;
    if (modelReturnParameterEntityType != null)
    {
        storeReturnParameterRowType = RowType.Create(
            modelReturnParameterEntityType.Properties.Select(property => property.Clone()),
            null);
    }

The result seems valid and is added to the ModelStore. The conceptual model is created, and the return value is generated here 

https://github.com/Dixin/EntityFramework.Functions/blob/master/EntityFramework.Functions/Function.DbModel.cs#L568

The relevant portion of the method is here

    if (functionAttribute.Type == FunctionType.TableValuedFunction)
    {
        // returnParameterInfo.ParameterType is IQueryable<T>.
        Type returnParameterClrType = returnParameterInfo.ParameterType.GetGenericArguments().Single();
        StructuralType modelReturnParameterStructuralType = model.GetModelStructualType(returnParameterClrType, methodInfo);
        modelReturnParameterEdmTypes = Enumerable.Repeat(modelReturnParameterStructuralType, 1);
    }

Again it appears that the already-defined model is found and used to generate the return value.  Everything looks correct, and is added to the ConceptualModel.

For some reason this appears to break the schema of my model.  I kinda doubt the answer as to why and the solution to fix it won't be initially obvious.  But any hints/suggestions as to what might be happening and why, and how it might be fixed would be appreciated.  A demo app is attached (Edit:  It can be found attached to this issue over on Codeplex https://entityframework.codeplex.com/workitem/2959).  I might have killed the entityframework.functions project when trying to get the zip in under the weight limit.  If so, you can re-download it from the GitHub repository.

**Comment by ajcvickers** [comment]
Note for triage: EF6.

**Comment by rowanmiller** [comment]
This would require a lot of digging for us to understand the EntityFramework.Functions code base and then isolate the issue in EF. We're going to ask that you start with raising the issue with the EntityFramework.Functions project and have them open an issue here if there are able to isolate it to an specific issue in EF.
