### ISSUE TITLE
VS 2019 not able to run Custom Tool for EDMX T4 Templates

### ISSUE THREAD

**Issue by jbest054** [aspnet/EntityFramework6#1174]
After creating a new ASP.NET Web API project, create an EDMX model, Visual Studio will then *not* run the T4 templates, forcing one to run them manually.
After attempting to do so, the process fails with: The custom tool ‘TextTemplatingFileGenerator’ failed.

### Further technical details
EF version: 6.2.0
Database Provider: IBM.Data.DB2.EntityFramework
Operating system: Windows 10 1903
IDE: Visual Studio 2019 (16.2.3)

**Comment by jbest054** [comment]
Cross-posted a similar issue to the Visual Studio developer community since I wasn't sure where it belonged.

**Comment by jbest054** [comment]
FWIW, I was able to create a successful project with 2017, but I'm still baffled as to why 2019 would have failed in such a spectacular fashion.

**Comment by ajcvickers** [comment]
@lajones Was the known T4 issue fixed in 16.2.3?

**Comment by smitpatel** [comment]
@lajones - ping

**Comment by lajones** [comment]
The problem with Run Custom Tool not being kicked off (note: internally bug 779606) was solved in 16.1 Preview 1. But there was also the issue about BeginInvoke/EndInvoke (internally 890302) and another where some customers .tt processing was failing to understand $(VSAPPIDDIR) and it needing to be %VSAPPIDDIR% (internally 964348). That resulted in customers seeing "ErrorGeneratingOutput" in the .cs files. That last  was not solved til 16.4 Preview 1. So I would suggest moving to at least that version.

**Comment by jbest054** [comment]
@lajones Cool. I will install the Preview and report back. Thanks for the update.

**Comment by istvanbialko** [comment]
Hello,

Is the problem resolved? I have a tool to generate edmx with the built-in templates. In which update will this variable be fixed?

Thanks!
