### ISSUE TITLE
PackageReference breaks Entity Framework 6

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1197]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/714435/packagereference-breaks-entity-framework-6.html)._

---
What steps will reproduce the problem?
1. Create a new console project ConsoleApp1, specifying PackageReference architecture instead of Packages.config
2. Add the EntityFramework.SqlServerCompact package (note that its dependencies include EntityFramework)
3. Add a class to the project that inherits from DbContext
4. Run Enable-Migrations from the Package Manager Console
5. Note the resulting error: &quot;The EntityFramework package is not installed on project 'ConsoleApp1'&quot;

What is the expected output? What do you see instead?
Expected:
Creation of a Migrations folder containing a Configuration class (i.e. Code First Migrations are enabled)

Actual:
The above error message

Please provide any additional information below.
Workaround:
We can install the EntityFramework package prior to installing the EntityFramework.SqlServerCompact package in order to mitigate this problem. However, this extra step shouldn't be necessary. The Enable-Migrations CmdLet should be able to walk package dependencies and discover that the requisite packages are installed.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
@InteXX Generally speaking, EF 6.2 doesn't work with SDK-style projects and package references. This is fixed for 6.3--see #231. However, we are not updating the SQL Compact package for 6.3 because SQL Compact is end-of-life.

**Comment by InteXX** [comment]
@ajcvickers 

Very good, thank you.

Note: SqlCe doesn't hit EOL until July 2021. Nevertheless, is the v6.2 package expected to work with EF6.3?

That said, it appears that v6.3 is being worked on: https://www.nuget.org/packages/EntityFramework.SqlServerCompact/6.3.0-preview8-19405-04

**Comment by ajcvickers** [comment]
@InteXX The package still exists, and it may also happen to work with package references due to picking up changes made for the other packages, but it isn't a goal to bring this package to .NET Core or the new project system. What works works, what doesn't work, doesn't work.

**Comment by ErikEJ** [comment]
@InteXX I have created an unofficial port  of the SQL Compact provider to .NET Core: https://github.com/ErikEJ/EntityFramework6PowerTools/tree/community/src/ErikEJ.EntityFramework.SqlServerCompact

**Comment by InteXX** [comment]
That looks great, thanks. Is there a corresponding NuGet package?

Eventually I'd like to contribute a VB.NET SQL generator for it, but that's only a long-term goal at this point.

**Comment by ErikEJ** [comment]
There is, just look at the readme at the link

**Comment by InteXX** [comment]
I did, but I didn't find a package name. Maybe I'm looking right past it.

I did find this in the `.csproj`, though, inside the `<PackageID/>` tag: `ErikEJ.EntityFramework.SqlServerCompact`
