### ISSUE TITLE
Stop depending on NuGet.VisualStudio.IVsPackageInstallerServices for PMC commands

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#12]
Currently we depend on resolving an instance of the interface NuGet.VisualStudio.IVsPackageInstallerServices to lockage the NuGet package installation path. 

 This has proved to be very brittle. We have been broken a couple of times already, e.g. lately by a change in the behavior of PowerShell: https://entityframework.codeplex.com/workitem/2872. 

 @BriceLambson has a few ideas to replace this logic. Creating this work item to track this for a future improvement.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2887

**Comment by bricelam** [comment]
My idea: Use `$PSScriptRoot` instead.

**Comment by bricelam** [comment]
Looking into this, I'm not sure it's a good idea.

You can only have one version (the latest) of the PMC commands loaded at at time. Right now, we use the `IVsPackageInstallerServices` to ensure we use the version of `EntityFramework.dll` and `EntityFramework.PowerShell.dll` that is installed into the target project.

If we switch to using `$PSScriptRoot`, it would use the version of the dlls that match the loaded PMC commands. This may cause problems in solutions containing multiple versions of Entity Framework.
