### ISSUE TITLE
EntityFramework error: Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1226]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/721338/entityframework-error-cannot-bind-argument-to-para.html)._

---
If the path to the current project contains square brackets, the EntityFramework tools return a null Path error.

Steps to Repro (from memory):
1. Create a new project inside a parent folder called &quot;[test]&quot;
2. Setup EntityFramework
3. Create models, contexts, etc.
4. Run &quot;add-migration InitialCreate&quot; in the package manager window

Result
error: Cannot bind argument to parameter 'Path' because it is null.

Expected result:
the add-migration command runs successfully.

To further demonstrate this issue:
1. close solution and visual studio
2. move the project folder to a different parent folder called &quot;test&quot;
3. open visual studio and load the project file just copied.
4. Run &quot;add-migration InitialCreate&quot; in the package manager window

Result:
the add-migration tool runs correctly.

---
#### Visual Studio Feedback System on 9/4/2019, 00:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/5/2019, 00:43 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by bricelam** [comment]
What version of EF and VS? What's selected as the Default project insdie Package Manager Console?

**Comment by bricelam** [comment]
Given that it works after re-opening the solution, I think this is a known NuGet issue we've seen before. It sometimes has issues with new projects under solution directories. The NuGet API gives us wrong information which eventually leads to this error.

But it's hard to say for sure without debugging the failure.

**Comment by andersonphiri** [comment]
In my case I had multiple projects under one solution and I am using Npgsql as my provider. So experienced this error with the intended project set as start up. I only changed the startup project to a different one, and then run for example: Update-Database -ProjectName "MytargetProjectName" and it was working again
