### ISSUE TITLE
Tools: Include a copy of the .NET 4.5 version of the EF5 assembly in a well known location for all supported VS versions

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#125]
This issue was originally described at https://entityframework.codeplex.com/workitem/2844 and https://entityframework.codeplex.com/workitem/2788. It was more recently reported internally by the Web Tools team while working on VS 2017 features, since the assembly has been relocated once more. 

__Cause__
The location of EntityFramework.dll for 5.0.0 was fixed as a result of a previous bug fix: A [CodeBase entry](https://github.com/aspnet/EntityFramework6/blob/master/src/EFTools/EntityDesignPackage/PkgDefData/Microsoft.Data.Entity.Design.Package.pkgdef#L182) was added to the EF Tools package definition, but for different versions of VS the location can vary. 

E.g. in VS versions previous to 2015 the location is: 

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\EFTools\NuGet Packages\EntityFramework.5.0.0\lib\net45\EntityFramework.dll
```

For VS 2015, it the location is:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages\EntityFramework.5.0.0\lib\net45\EntityFramework.dll
```

For VS 2017 we currently don't include the NuGet packages under the VS installation folder but in a separate place on disk:

```
C:\Program Files (x86)\Entity Framework Tools\NuGet Packages\EntityFramework.5.0.0\lib\net45\EntityFramework.dll
```
__Proposed solution__
It is very hard to track down where exactly the NuGet packages will be copied (at least once the location changed due to changes in how certain variables get expanded in VS) and as far as we know the codebase entry can only point to a folder inside the VS installation, so the simplest solution is for us to upgrade our setup to place a copy of the EF5 version of the entityframework.dll assembly (note that only the .NET 4.5 flavor should be needed) in a well known location. 

We should also update the package definition to point to the new location.

__Symptoms__
Any time VS needs the EF5 assembly, e.g. to execute Migrations commands in the Package Management Console, it will fail. e.g.:

```
PM> enable-migrations
Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 'EntityFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The 
system cannot find the file specified."
At C:\Users\divega\documents\visual studio 2015\Projects\ConsoleApplication22\packages\EntityFramework.5.0.0\tools\EntityFramework.psm1:431 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
```

__Workaround__
You can copy the contents of the EF5 package where Visual Studio expects to find it, e.g. in the Developer Command Prompt run the following command:

```
xcopy "%DevEnvDir%\Extensions\Microsoft\Entity Framework Tools\Nuget Packages\entityframework.5.0.0\lib\net45\*" "%DevEnvDir%\CommonExtensions\Microsoft\EFTools\NuGet Packages\EntityFramework.5.0.0\lib\net45\"
```

**Comment by divega** [comment]
Note that we already do something similar for the assemblies contained in the EF6 package. They are placed in the Common7\IDE folder.

**Comment by lajones** [comment]
For now decided that the EntityFramework v5.0.0 DLL should be installed (by the VSIX) into `<VS_install_dir>\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\Runtimes\5.0.0`. For now this will only affect VS15. We will investigate later whether this same change can be safely applied to all VS versions prior to VS15 as well.

**Comment by lajones** [comment]
Checked into release-6.1.3-tools-dev15-test with commit ca0afe9 (and matching commit in EFBuild which contains the setup changes - commit bb32616).

**Comment by lajones** [comment]
As of Dec 7, 2016 the above changes were included into the lab\d15prerel branch which will be incorporated into VS2017 in the RC.3 release. This issue is now tracking the work to adopt the same approach (if possible) for all previous versions of VS as well.

**Comment by lajones** [comment]
Checked in change with commit 91ccec4.
