### ISSUE TITLE
Revisit query compilation performance PR after 6.3

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#1257]
We got a PR from @cjpearson in 6.3 that appear to have some significant query compilation performance improvements that could benefit some customers (including @chrfin): https://github.com/aspnet/EntityFramework6/pull/430.

Unfortunately there was a bug discovered in the last minute that forced us to revert in https://github.com/aspnet/EntityFramework6/pull/1251.

This issue is to track revisiting the original PR and try to get it fixed for a later version. 

We don't plan to be proactive about this but we will consider contributions.

**Comment by chrfin** [comment]
@divega Please take a look at #1239 as I think this fixes the problem and could be merged after 6.3 release to have the improvements back in for the first nightly after the release...
