### ISSUE TITLE
Dynamic Proxy Setter is not Defining Reference/Collection as Loaded

### ISSUE THREAD

**Issue by ziongh** [aspnet/EntityFramework6#127]
I'm using **Entity Framework 6.1.3**. and The _repository object is a Extension of **IdentityDbContext**.

In the DBContext initialization I'm using the following configurations:

```cs
this.Configuration.AutoDetectChangesEnabled = false;
this.Configuration.ProxyCreationEnabled = true;
this.Configuration.LazyLoadingEnabled = true;
```

The following code shows the unexpected behaviour:

```cs
var car = _repository.Set<Car>().AsQueryable().Where(s => s.Id == carID)
                    .Include(s => s.Trunk)
                    .FirstOrDefault();

car.Doors = _repository.Set<Door>().AsQueryable().Where(s => s.Car_Id == carID).Include(s => s.Window).ToList();

if(car.Doors.Any()) // Another Query is triggered Here!
{
   return;
}
```

In the above scenario, I try to Eager Load the **Doors** Collection of the **Car** entity by setting the **Doors** collection. However, when this collection is accessed another Query is triggered. I supposed that it's a problem with the Dynamic Proxy that EF is creating for the **car** entity:

- The getter of the proxy probably isn't checking if the collection is already loaded.

- Or maybe the setter of the proxy isn't setting the collection as Loaded. (The **_isLoaded** attribute of the System.Data.Entity.Core.Objects.DataClasses.**RelatedEnd**)

**Comment by rowanmiller** [comment]
This is by-design. EF doesn't know if the collection you set contains all the contents of navigation, or just some of them. Because you do know that they are all there, you can set the loaded flag (the reason we added a public setter to it).
