### ISSUE TITLE
Pluralization ToDo is ToDoes

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#1278]
See notes from Scott Hunter:

- Pluralization ToDo is ToDoes

(See also internal DevDiv issue 978993).

**Comment by bricelam** [comment]
Fixing pluralization bugs are a breaking change. Any database already created using the incorrect pluralization would start throwing. As such, we'll never actually be able to fix these issues. ☹

**Comment by CZEMacLeod** [comment]
@lajones I'm not sure if it is well documented or not, but if you inherit DbConfiguration you can override the initializer
```
Sub New()
    MyBase.New()
    Dim customWords = {
        New CustomPluralizationEntry("Status", "Statuses"),
        New CustomPluralizationEntry("ToDo", "ToDos")
    }
    SetPluralizationService(New EnglishPluralizationService(customWords))
End Sub
```
