### ISSUE TITLE
ef 6.3 under linux

### ISSUE THREAD

**Issue by Elufimov** [aspnet/EntityFramework6#1288]
Hi! I just tried a simple example under linux and it works. However in official posts I did not see any mention about such big feature as linux support. Also as I can see in the repository source code does not test under linux. In all this in mind I want to ask Is this an official feature that will be supported or a happy accident?

**Comment by ErikEJ** [comment]
It works with SQL Server from Linux, yes.

**Comment by Elufimov** [comment]
> It works with SQL Server from Linux, yes.

And this is a supported scenario? I always thought that main difference in long run between ef core and classic ef will be a linux support.

**Comment by divega** [comment]
I can confirm it’s no accident. We tend to think that targeting .NET Standard 2.1 and testing on .NET Core implies cross-platform support, but given that some of the other recent additions (e.g. WinForms and WPF) are Windows-only, I agree that it’s worth calling out explicitly in docs and announcements. 

cc: @bricelam

**Comment by bricelam** [comment]
Don't worry, we ran the tests on Linux. 😄 It was just too expensive to automate.

My comment from a previous PR:
> We're not going to enable macOS and Ubuntu on the CI since there are still 4K tests failing with "LocalDB is not supported on this platform." If the community is interested in skipping these tests, or getting the base connection string from an environment variable, we'd happily accept a PR.

**Comment by bricelam** [comment]
EF6 has actually worked on Linux [for seven years](https://www.mono-project.com/docs/about-mono/releases/3.0.0/#new-microsoft-open-source-stacks) 😉

**Comment by Elufimov** [comment]
> EF has actually worked on Linux [for seven years](https://www.mono-project.com/docs/about-mono/releases/3.0.0/#new-microsoft-open-source-stacks) now. 😉

We do not run mono in production (and I do not know any company who does in my environment), however we have plans to move everything to core(Everything that not already was moved :)). Including our big monolithic applications. Official support for ef 6.3 under linux would greatly reduce amount of work.

>  If the community is interested in skipping these tests, or getting the base connection string from an environment variable, we'd happily accept a PR.
Maybe it will be good to open issue with label "Help wanted" for visibility? Dotnet core is really amazing but ci tests for target systems would be a good thing to have.

**Comment by divega** [comment]
I added this to the blog post and the what's new question:

> * This means that EF 6.3 is cross-platform and supported on other operating systems besides Windows, like Linux and macOS.
