### ISSUE TITLE
MSBuild error with Visual Studio 2015

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework6#1292]
(From [the blog post](https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/) comments)

Does Entity Framework 6.3 support Visual Studio 2015? I am getting the following error after upgrading:

> The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns=”http://schemas.microsoft.com/developer/msbuild/2003″ to the element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by bricelam** [comment]
FYI, this fix is included in our [daily builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) (see link for setup instructions). Feel free to start using it today via the version 6.4.0-preview1-* prerelease packages.

**Comment by nicholastic** [comment]
Could you please look at this question, it's similar but it's failing on Azure: https://stackoverflow.com/questions/58617182/azure-deployment-error-msb4041-the-default-xml-namespace-of-the-project-must-b
