### ISSUE TITLE
Migrate.exe runs all the migrations even if they are already applied

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#13]
It looks like migrate.exe is not interpreting right the exceptions - for example if user, that is used to connect to database when running migrate.exe does not have rights to read migration history table (is only ddladmin), migrate.exe tries to run all the migrations, instead of showing error for missing permissions. 

 It took lots of time and reverse engineering to figure this out.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2886

**Comment by bricelam** [comment]
This sounds by-design. I believe that to SQL Client, table that doesn't exist and a table that you don't have permissions to access are the same thing.

I'll dig into the experience to see we can short-circuit sooner with a friendlier error message.

**Comment by divega** [comment]
The exceptions should be different, but not sure if currently we have a mechanism to reason about exceptions in a provider specific way like we would need to do here. 

> System.Data.SqlClient.SqlException
  Class=14
  Message=The SELECT permission was denied on the object 'TableX', database 'DatabaseY', schema 'Z'.
  Number=229
  State=5
  
> System.Data.SqlClient.SqlException 
  Class=16
  Message=Invalid object name 'TableX'.
  Number=208
  State=1

**Comment by divega** [comment]
Moving to @anpete to load-balance.
