### ISSUE TITLE
EF 6.3 release: where is the changelog?

### ISSUE THREAD

**Issue by MatejQ** [aspnet/EntityFramework6#1305]
Hello,
I have only 2 things to mention...
With new EF 6.3 release, I was unable to find a changelog. I would like to know what was added, updated, which bugs were fixed, to justify upgrade in our solution.
Second, I have come across [this page](https://github.com/aspnet/EntityFramework6/wiki/Roadmap), which still says EF6.3 is planned, I think that page needs updating.

**Comment by MagicAndre1981** [comment]
Changelog is posted here:

https://docs.microsoft.com/en-us/ef/ef6/what-is-new/#ef-630
