### ISSUE TITLE
 EF 6.3 + MSSQL CE (Edmx) in dotnet core 3.0 . Get error in config.

### ISSUE THREAD

**Issue by parad74** [aspnet/EntityFramework6#1316]
Describe what is not working as expected.
I tried run options  EF 6.3 + MSSQL CE  from dotnet core 3.0 -  was not successful. No one idea more. 
Looks like error in app.config  DbProviderFactories.
In .Net Framework 4.8 – all work. But in dotnet core 3.0 –not work.
I got idea from https://github.com/efcore/EdmxDotNetCoreSample/
But it didn’t help for me. 

I added simple code
https://github.com/parad74/dotnetcore_mssqlce
4.8/C4U.Model – project 4.8 Net Framework 4.8
C4U.Model.Include – Model for dotnet Core 3.
Host – simple host-server dotnet Core 3. Test connection in 
public static void Main(string[] args)
Help me, plz

```
Operating system: (e.g. Windows 7)
IDE: (e.g. Visual Studio 2019)
EF 6.3 + MSSQL CE  from dotnet core 3.0 


```
An error occurred while starting the application.
ConfigurationErrorsException: Unrecognized configuration section system.data. (T:\Count4U\trunk\github\Count4U\host\bin\Debug\netcoreapp3.0\host.dll.config line 23)
System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool ignoreLocal)

ConfigurationErrorsException: Configuration system failed to initialize
System.Configuration.ClientConfigurationSystem.EnsureInit(string configKey)

TypeInitializationException: The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception.
System.Data.Entity.Internal.AppConfig.get_DefaultInstance()

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor, ref bool hasNoDefaultCtor)

ConfigurationErrorsException: Unrecognized configuration section system.data. (T:\Count4U\trunk\github\Count4U\host\bin\Debug\netcoreapp3.0\host.dll.config line 23)
System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool ignoreLocal)
System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
System.Configuration.ClientConfigurationSystem.EnsureInit(string configKey)

Show raw exception details
ConfigurationErrorsException: Configuration system failed to initialize
System.Configuration.ClientConfigurationSystem.EnsureInit(string configKey)
System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(string sectionName)
System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(string sectionName)
System.Configuration.ConfigurationManager.GetSection(string sectionName)
System.Configuration.ConfigurationManager.get_ConnectionStrings()
System.Data.Entity.Internal.AppConfig..ctor()
System.Data.Entity.Internal.AppConfig..cctor()

Show raw exception details
TypeInitializationException: The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception.
System.Data.Entity.Internal.AppConfig.get_DefaultInstance()
System.Data.Entity.Infrastructure.DependencyResolution.InternalConfiguration..ctor(ResolverChain appConfigChain, ResolverChain normalResolverChain, RootDependencyResolver rootResolver, AppConfigDependencyResolver appConfigResolver, Func<DbDispatchers> dispatchers)
System.Data.Entity.DbConfiguration..ctor()

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor, ref bool hasNoDefaultCtor)
System.RuntimeType.CreateInstanceDefaultCtorSlow(bool publicOnly, bool wrapExceptions, bool fillCache)
System.RuntimeType.CreateInstanceDefaultCtor(bool publicOnly, bool skipCheckThis, bool fillCache, bool wrapExceptions)
System.Activator.CreateInstance(Type type, bool nonPublic, bool wrapExceptions)
System.Activator.CreateInstance(Type type, bool nonPublic)
System.Data.Entity.Utilities.TypeExtensions.CreateInstance<T>(Type type, Func<string, Exception> exceptionFactory)
System.Data.Entity.Utilities.TypeExtensions.CreateInstance<T>(Type type, Func<string, string, string> typeMessageFactory, Func<string, Exception> exceptionFactory)
System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.<.ctor>b__10_0()
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()
System.Lazy<T>.get_Value()
System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.GetConfiguration()
System.Data.Entity.Infrastructure.DependencyResolution.InternalConfiguration.get_Instance()
System.Data.Entity.DbConfiguration.get_DependencyResolver()
System.Data.Entity.Core.EntityClient.EntityConnection.ChangeConnectionString(string newConnectionString)
System.Data.Entity.Core.EntityClient.EntityConnection..ctor(string connectionString)
System.Data.Entity.Core.Objects.ObjectContext.CreateEntityConnection(string connectionString)
System.Data.Entity.Core.Objects.ObjectContext..ctor(string connectionString)
System.Data.Entity.Core.Objects.ObjectContext..ctor(string connectionString, string defaultContainerName)
Count4U.Model.App_Data.MainDB..ctor(string connectionString) in Model6.cs
+
        public MainDB(string connectionString) : base(connectionString, "MainDB")
host.Program.Main(string[] args) in Program.cs
+
			using (Count4U.Model.App_Data.MainDB dc = new Count4U.Model.App_Data.MainDB(cs))
```

**Comment by ErikEJ** [comment]
You cannot use app.config with .NET Core, try the workaround described here: https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/

     DbProviderFactories.RegisterFactory("System.Data.SqlSeverCe.4.0", SqlCeClientFactory.Instance);

**Comment by parad74** [comment]
Erik, Thank you so much.
I was able to run.
but it was crazy quest. 
If it ll add in doc or in package, it will make it much easier transition from .Net to doctnet Core 3
Fixed sample,
https://github.com/parad74/dotnetcore_mssqlce

**Comment by ErikEJ** [comment]
Your codes documents how to do it! https://github.com/parad74/dotnetcore_mssqlce/commit/beebf90f1e252f64073794c5a55671735eed906c#diff-d9f32fc1395f6c8f94b824c308bd4271

**Comment by parad74** [comment]
Need add document?

**Comment by ErikEJ** [comment]
Maybe a few words would be helpful - maybe you can propose an issue in EF Docs? (or maybe the provider is not really supported any more?)

**Comment by parad74** [comment]
I ll do document tomorrow.

> maybe you can propose an issue in EF Docs? (or maybe the provider is not really supported any more?)

How to do it?
If there is <PackageReference Include="EntityFramework.SqlServerCompact">
			<Version>6.3.0</Version>
how it not suppot?

**Comment by ErikEJ** [comment]
https://github.com/aspnet/EntityFramework.Docs/issues is the docs repo.

>> how it not suppot?

Because the ADO.NET provider is no longer supported.

**Comment by parad74** [comment]
In simple case it's working now. I hope it ll work in my dotnet core 3 application. :)

**Comment by bricelam** [comment]
We also have #920 and https://github.com/dotnet/corefx/issues/37998 which could make things a little easier

**Comment by parad74** [comment]
I added simple doc to sample.
I think, there are steps that can be added to the package "EntityFramework.SqlServerCompact"
f.e. to copy 
files 
sqlceca40.dll
sqlcecompact40.dll
sqlceer40EN.dll
sqlceme40.dll
sqlceqp40.dll
sqlcese40.dll
3-4 steps

**Comment by parad74** [comment]
Developers who want to migrate their Application with data-level on MSSQL CE,  most of them with MSSQL CE 10 year or more. And if the systems are migrating now so users need these Applications and they are in progress. To transfer a large system with a large number of users with a change in the data-level and model is unrealistic. If the level of the model is working, then the chances increase.

**Comment by ajcvickers** [comment]
@parad74 As was also answered elsewhere, we're not explicitly blocking anything for SQL Compact, but we're also not doing anything to make it work with EF in .NET Core since there are no plans to bring SQL Compact itself to .NET Core.
