### ISSUE TITLE
6.4.0 or 6.3.1?

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework6#1322]
Can we just call it version 6.3.1? Everyone knows it should be...

**Comment by AartBluestoke** [comment]
typical versioning is <breakingChange>.<newFeatures>.<Bugfix> ; i guess someone somewhere decided that there was enough new stuff in new features that it warranted a new minor version.

**Comment by bricelam** [comment]
So far, there are 4 bug fixes...

**Comment by AndriySvyryd** [comment]
It might be easier to release 6.4.0 instead of 6.3.1 due to how our infrastructure works.

**Comment by bricelam** [comment]
Patch infrastructure for 6.3 is set up. I've requested approval to include those four bugs in 6.3.1. Dreams can come true
