### ISSUE TITLE
DbEntityEntry contains unrelated/outdated info

### ISSUE THREAD

**Issue by Cassandra-d** [aspnet/EntityFramework6#1362]
Not sure that creating the issue in correct repository.

[DbEntityEntry<TEntity>](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.dbentityentry-1?view=entity-framework-6.2.0) page lists a [method](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.dbentityentry-1.collection?view=entity-framework-6.2.0#System_Data_Entity_Infrastructure_DbEntityEntry_1_Collection__1_System_Linq_Expressions_Expression_System_Func__0_System_Collections_Generic_ICollection___0____) called Collection which does not exist in [source code](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/Infrastructure/DbEntityEntry.cs).

**Comment by smitpatel** [comment]
Transferred here. Not sure if it is extension method. If it is issue with doc generation, let me know so that I can escalate to appropriate team.

**Comment by ajcvickers** [comment]
@Cassandra-d You're looking in the wrong class; it's defined in the generic `DbEntityEntry<>`:
https://github.com/aspnet/EntityFramework6/blob/release/6.4/src/EntityFramework/Infrastructure/DbEntityEntry%60.cs#L289
