### ISSUE TITLE
Potential cross-platform path handling issue in EntityDeploy MSBuild task

### ISSUE THREAD

**Issue by mistachkin** [aspnet/EntityFramework6#1378]
The OutputCMS method in the source file "src/Microsoft.Data.Entity.Build.Tasks/EntityDeploy.cs" has the following code:

**FileInfo outputFile = new FileInfo(Path.Combine(topLevelOutputDir.FullName, inputFileRelativePath));**

And then a bit later in the same method:

**string outputDirPath = outputDir.FullName + "\\\\";**

I think hard-coding the backslash here is causing the problem I'm seeing with my Linux build:

CSC : error CS1566: Error reading resource 'NorthwindModel.EF6.NetStandard21.csdl' -- 'Could not find file './testlinq/obj/Debug/netcoreapp3.0/NorthwindModel.EF6.NetStandard21.csdl'.' [./testlinq/testef6.NetStandard21.csproj]

Within the "**obj/Debug/netcoreapp3.0**" directory, I see the following files and directories:

(directory) edmxResourcesToEmbed
(file) **edmxResourcesToEmbed\NorthwindModel.EF6.NetStandard21.ssdl**
(file) **edmxResourcesToEmbed\NorthwindModel.EF6.NetStandard21.msl**
(file) **edmxResourcesToEmbed\NorthwindModel.EF6.NetStandard21.csdl**
(file) testef6.NetStandard21.assets.cache
(file) testef6.NetStandard21.csproj.FileListAbsolute.txt
(file) testef6.NetStandard21.csprojAssemblyReference.cache

Notice the three files that have a backslash within their name?  That is the root of the problem, which I'm pretty sure was caused by the errant code in the MSBuild task.

I think the solution may be as simple as using the System.IO.Path.DirectorySeparatorChar field instead of hard-coding the backslash; alternatively, the Path.Combine method could potentially be used (again) in this method to avoid using the character at all.

FYI: This issue is currently **blocking** the release of .NET Core 3.0 support for System.Data.SQLite.

**Comment by ajcvickers** [comment]
@bricelam Thoughts?

**Comment by mistachkin** [comment]
Update: I think part of the problem here is actually a bad interaction with the private **CreateTaskItem** method within the same file.  It searches for **Path.DirectorySeparatorChar**, not backslash.  Seemingly, this would lead to an incorrect **LogicalName** being set on the created **TaskItem**.

**Comment by mistachkin** [comment]
I think pull request #1385 should contain the necessary changes to fix this issue.

**Comment by bricelam** [comment]
PR looks good to me. I suspected there might be bugs in this area. https://github.com/aspnet/EntityFramework6/issues/1137#issuecomment-520917472

**Comment by springy76** [comment]
@mistachkin btw: I was the one who created ticket ce75d320d0a31dabfec48df265e611d0fc235a30 asking for netcore3/netstandard2.1. I have to admit I'm not a "fan" of fossil (I have no clue how to register there, thats why I'm using anonymous all the time) and I might not have the time to build System.Data.SQLite myself -- or is there a private feed of prerelease NuGet packages?
