### ISSUE TITLE
Upgrade .NET Standard 2.0 project from EF 6.2.3 to 6.3.0 => System.Data.Entity namespace no longer found

### ISSUE THREAD

**Issue by ssteiner** [aspnet/EntityFramework6#1381]
I tried migrating my DBL from EF 6.2.3 to 6.3.0. The DBL is contained in a .NET 4.7.2 lib - no problems updating that one. And then there's another lib (this one a .NET standard 2.0 lib) that us using the EF to perform coded migrations, and create default DBs. It uses amongst other things System.Data.Entity.IDatabaseInitializer<T>.

After the migration, I can no longer compile the .NET Std 2.0 lib. Visual Studio 2017 tells me the type DBContext<T> is defined in an unreferenced library and I need to reference EntityFramework Version 6.0.0.0. Looking at my dependencies in VS 2017, under Dependencies - NuGet, I see the EntityFramework (6.3.0) but there's no icon to expand (as there is for every other reference, e,.g. System.Security.Principal.Windows - which is self contained but still expands to list System.Security.Principal.Windows.dll).

So.. is EF 6.3.0 not meant to be used in a .NET 2.0 context, or am I missing something.

**Comment by ajcvickers** [comment]
@bricelam Is using a .NET Standard 2.0 class library supported? (As opposed to a .NET Core 3.0 class library, a .NET Framework class library, or a .NET Standard 2.1 class library.)

**Comment by ssteiner** [comment]
That's a good question. But if it weren't, it should prevent me from updating the package I'd say. I have this situation for other packages that require .coreapp2.1 - they cannot be updated on a .netstandard2.0 lib.

And I guess with .net core 3.0 it's time that nuget gets the capability of not showing certain updates because they cannot be applied - the number of incompatible upgrades is ever growing. But that's an issue to raise with the nuget folks.

**Comment by bricelam** [comment]
The only .NET Standard 2.0 class library an EF6 project can have is for the POCO entity types. Everything else that references EF directly needs to target .NET Framework 4.0+ or .NET Standard 2.1

**Comment by jzabroski** [comment]
> The only .NET Standard 2.0 class library an EF6 project can have is for the POCO entity types. Everything else that references EF directly needs to target .NET Framework 4.0+ or .NET Standard 2.1

Note, with EF 6.5.1, users would now need to use `<TargetFrameworks>net48;net6.0</TargetFrameworks>`.  POCO entity type libraries that reference ObjectContext will need to work this way and cannot do `<TargetFramework>netstandard2.0</TargetFramework>`

It took me a few minutes to wonder why I was getting an error "The type or namespace name 'Entity' does not exist in the namespace 'System.Data'" on `using System.Data.Entity.Core.Objects;`

**Comment by ErikEJ** [comment]
Or maybe just net6.0 or net48 ?

Also, how POCO are classes that need ObjectContext?

**Comment by jzabroski** [comment]
It literally says it https://learn.microsoft.com/en-us/dotnet/api/system.data.objects.objectcontext.getobjecttype?view=netframework-4.8.1#remarks

I realize you could put this logic elsewhere, but we don't. It's part of our EntityBase class. Having it polymorphic avoids passing in the wrong type.

**Comment by jzabroski** [comment]
> Or maybe just net6.0 or net48 ?

Migrating a huge code base with multiple executables/apis/websites isn't that easy. Multi-targeting spreads out release regression risk and planning on call support to be in line with development expertise.
