### ISSUE TITLE
EF code first tools migration does not work

### ISSUE THREAD

**Issue by altyne** [aspnet/EntityFramework6#1383]
Describe what is not working as expected.
        Enable-Migrations, Add-Migration, Update-Database and Get-Migrations should work
```
Package Manager Console:
enable-migrations : The term 'enable-migrations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ enable-migrations
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (enable-migrations:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

add-migrations : The term 'add-migrations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Steps to reproduce
Nuget Package Manager -> PackageReference
Create new console project
Package Manager Console -> install-package entityframework
Package Manager Console -> install-package Oracle.ManagedDataAccess.EntityFramework 

### Further technical details
EF version: 6.3
Database Provider: Oracle.ManagedDataAccess
Operating system: Windows 7, 8.1
IDE: Visual Studio 2017 15.9.14

Root Cause:
PackageReference does not execute install.ps1 -  [see github link](https://github.com/NuGet/Home/issues/6330)

PackageReference  install packages in c:\\users\\[user]\\.nuget\\packages where as the package.config setup installed in solution directory.

Issues Closed:
https://github.com/aspnet/EntityFramework6/issues/1348
https://github.com/aspnet/EntityFramework6/issues/1197

But still the problem exists.

**Comment by ajcvickers** [comment]
@altyne What is your target framework?

**Comment by altyne** [comment]
4.8

**Comment by ajcvickers** [comment]
@altyne If the root cause of this is that, `PackageReference does not execute install.ps1`, then that's by-design by NuGet and not something that will change. You need to continue to use `packages.config` to get this functionality.

That being said, EF 6.3 should be able to work without running `install.ps1`, but it may require manual work--for example, updating app.config.

**Comment by altyne** [comment]
I found [Microsoft ](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#package-compatibility-issues) write-up regarding this one. So this issue will be dead in the water.

However, I managed to do migrations but it will entails a lot of manual work - utilizing ef6.exe, tinkering app.config, and adding code infrastructure to make this happen.
