### ISSUE TITLE
EF6.3 update-database command not working

### ISSUE THREAD

**Issue by PhilPJL** [aspnet/EntityFramework6#1387]
update-database command not working

----------------------------------
If all my projects reference EF 6.2 this works fine.

----------------------------------
If my project uses EF 6.3, but references another project which uses EF 6.2 I can specify entityframework\update-database, which results in

PM> entityframework\update-database -project hexcel.data.rateplan -startupproject hexcel.data.rateplan -script -sourcemigration $InitialDatabase
Both Entity Framework 6.x and Entity Framework Core commands are installed. The Entity Framework 6 version is executing. You can fully qualify the command to select which one to execute, 'EntityFramework\Update-Database' for EF6.x and 'EntityFrameworkCore\Update-Database' for EF Core.
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 
'file:///C:\Users\leedevpx\.nuget\packages\entityframework\6.3.0\tools\EntityFramework.PowerShell.Utility.dll' or one of its dependencies. The system cannot 
find the file specified."
At C:\Users\leedevpx\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:782 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
You cannot call a method on a null-valued expression.
At C:\Users\leedevpx\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:783 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 
'file:///C:\Users\leedevpx\.nuget\packages\entityframework\6.3.0\tools\EntityFramework.PowerShell.dll' or one of its dependencies. The system cannot find the 
file specified."
At C:\Users\leedevpx\.nuget\packages\entityframework\6.2.0\tools\EntityFramework.psm1:811 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

----------------------------------
If all my projects use EF 6.3

PM> update-database -project hexcel.data.rateplan -startupproject hexcel.data.rateplan -script -sourcemigration $InitialDatabase
Update-Database : A parameter cannot be found that matches parameter name 'script'.
At line:1 char:84
+ ... el.data.rateplan -startupproject hexcel.data.rateplan -script -source ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Database], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Database
 
PM> 

Honestly this is crazy.  Reverting to EF 6.2 which prevents us from starting to migrate to .NET Core 3.

**Comment by bricelam** [comment]
> I can specify entityframework\update-database

Use `EntityFramework6\Update-Database` on EF 6.3 projects

**Comment by neozhu** [comment]
update to 6.5.0-alpha1-19515-01 is ok,thanks

**Comment by PhilPJL** [comment]
If I create a sample database then it works fine.  If I update our solution which contain 50+ projects that reference EF then I get the errors shown above. I've reverted to 6.2 and updated to 6.3 again.  Same issue.

Plus

PM> update-database -project hexcel.data.rateplan -startupproject hexcel.data.rateplan -sourcemigration $InitialDatabase
Update-Database : A parameter cannot be found that matches parameter name 'sourcemigration'.
At line:1 char:84
+ ... ateplan -startupproject hexcel.data.rateplan -sourcemigration $Initia ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Database], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Database

PM> update-database -project hexcel.data.rateplan -startupproject hexcel.data.rateplan
Your startup project 'Hexcel.Data.RatePlan' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
PM> update-database -project hexcel.data.rateplan -startupproject hexcel.data.rateplan
Your startup project 'Hexcel.Data.RatePlan' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

We don't use EF Core anywhere, only EF .NET Framework.  There are a few .NET Core 3 projects in the solution but they don't reference EF.

**Comment by PhilPJL** [comment]
I've tried EF 6.4 p1 as well.  Same problem.

PM> update-database -project hexcel.data.cocoa -startupproject hexcel.data.cocoa -script
Update-Database : A parameter cannot be found that matches parameter name 'script'.
At line:1 char:78
+ ...  -project hexcel.data.cocoa -startupproject hexcel.data.cocoa -script
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Database], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Database
 
PM> entityframework\update-database -project hexcel.data.cocoa -startupproject hexcel.data.cocoa -script
entityframework\update-database : The module 'entityframework' could not be loaded. For more information, run 'Import-Module entityframework'.
At line:1 char:1
+ entityframework\update-database -project hexcel.data.cocoa -startuppr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (entityframework\update-database:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

Why is the package manager console running the EF Core commands?
What can I do to help debug this issue?

**Comment by PhilPJL** [comment]
Possibly sorted, although I'm pessimistic.  Every time I think this is sorted something else doesn't work.

To fix I ran 'init.ps1' in PMC.

Now this command works:

update-database -project hexcel.data.cocoa -startupproject hexcel.data.cocoa -script -sourcemigration $InitialDatabase
Both Entity Framework 6 and Entity Framework Core are installed. The Entity Framework 6 tools are running. Use 'EntityFrameworkCore\Update-Database' for Entity Framework Core.

Entity Framework Core is definitely not installed.
I'll try the other commands shortly.

**Comment by PhilPJL** [comment]
Seems to be ok after manually running init
