### ISSUE TITLE
Add VS2015 support to Power Tools VSIX

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#14]
EF power tools are not listed as an extension for Visual Studio 2015. The VSIX needs to be updated with 
 <VisualStudio Version-"14.0"> 
 <Edition>Pro</Edition> 
 </VisualStudio> 

 I've been using a modified VSIX but have only used it for View Entity Data Model (Read-Only) feature. Not sure if there are other known problems.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2881

**Comment by rowanmiller** [comment]
Note @julielerman has  PR on the CodePlex site to add this which we've given her the option to port to GitHub so that the change comes from her

**Comment by julielerman** [comment]
Thanks. Will do. Leaving this link for myself here: https://entityframework.codeplex.com/SourceControl/network/forks/jlerman/PowerToolsVSIX2015/contribution/8672

**Comment by julielerman** [comment]
Pull Request: https://github.com/aspnet/EntityFramework6/pull/27
