### ISSUE TITLE
EF6.3 Within NetCoreApp3.0 Library and PMC Migrations

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/EntityFramework6#1400]
I have a .NET Core 3 library which references EF6.3 and configuration.json. When I execute ```entityframework6\enable-migrations```  I run into a problem with using  configuration.json which is used to read the connection string from appsettings.json within the IDbContextFactory method. This is due to the package references not being copied to the bin directory during build.
I have hard coded the connection string for now, but would like to use .Net Core 3 configuration to get the connection string.
I haven't been able to find any csproj setting that will allow my to use .Net Core 3 configurations

**Comment by ajcvickers** [comment]
@bricelam  "This is due to the package references not being copied to the bin directory during build." is this known/expected?

**Comment by bricelam** [comment]
Ah, we inject this on EF Core to make it work:
``` xml
  <PropertyGroup>
    <GenerateRuntimeConfigurationFiles>True</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
```

**Comment by bricelam** [comment]
We may also hit binding redirect issues on .NET Framework class libraries for similar reasons

**Comment by bricelam** [comment]
Hmm, looks like I'm talking about a different problem. @ToddThomson do you have a repro project I can dig into?

**Comment by ToddThomson** [comment]
Hi @bricelam . I created a simple repro project for you, but everything ( enable-migrations; add-migration ) worked properly. This project only included EF 6.3 and configuration json.

The only difference I can think of is that the project that was giving me problems included both EF 6.3 and EFCore 3.0.

Let me go back and confirm that the issue still exists...

**Comment by ToddThomson** [comment]
@bricelam The issue results from having:
```
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```
included in any library project in the dependency chain.

**Comment by bricelam** [comment]
I don't follow. Can you share a repro? Also, what error are you seeing?

**Comment by ToddThomson** [comment]
@bricelam Here is a link to the repo [Issue 1400 repo](https://github.com/ToddThomson/EF63MigrationTest).

Within VS2019 latest open the Nuget Package Manager Console. Type ```enable-migrations```. This will work properly.

Now edit the project file and remove the comments around the lines:
```
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```
Remove the migration configuration file that was previously created from running the ```enable-migrations``` command.

In the PMC try running the ```enable-migrations``` command again. The command will fail.

**Comment by bricelam** [comment]
Thanks! Setting `GenerateRuntimeConfigurationFiles` to `True` does indeed fix the problem.

### The gory details

Using the Microsoft.AspNetCore.App framework reference tells CoreCLR to load Microsoft.Extensions.* assemblies from the framework instead of from the NuGet packages directory. But without a *.runtimeconfig.json the tools use the Microsoft.NETCore.App which doesn't include these libraries leading to the following error.

> Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

@ajcvickers Looks like we should take (at least part of) PR #1419 in 6.4

**Comment by ajcvickers** [comment]
@bricelam Sounds reasonable.
