### ISSUE TITLE
Add-Migration has no 'IgnoreChanges' parameter

### ISSUE THREAD

**Issue by steamwings** [aspnet/EntityFramework6#1435]
When I run Add-Migration InitialCreate –IgnoreChanges in package manager console, I get Add-Migration : A parameter cannot be found that matches parameter name 'IgnoreChanges'.
I just created this project yesterday and I'm running VS2019 which shows no relevant updates available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30985321-a087-4ba8-1ef2-1311532ceaf5
* Version Independent ID: 97a0e081-b208-8042-5964-02bccb4a1db0
* Content: [Code First Migrations with an existing database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/existing-database)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/existing-database.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/existing-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by steamwings** [comment]
Here's the whole project:
https://github.com/steamwings/aspnetefcore-dbfirst-migration
There's also a text file called PackageManagerSession.txt in case that's helpful.

**Comment by bricelam** [comment]
The parameter is there in 6.3.0. I suspect you're inadvertently using the EF Core cmdlet.

https://github.com/aspnet/EntityFramework6/blob/2f61cffeb5e09708a20bc6e3f4414b43407170a3/src/NuGet/EntityFramework/tools/EntityFramework6.psm1#L380

**Comment by steamwings** [comment]
Yep, I should have been looking at the EF Core reference instead of the EF6 reference. I hope y'all are able to bring migration support to existing databases with EF Core. Thanks!

**Comment by bricelam** [comment]
Note, to do this on EF Core, comment out the contents of the Up method, run the migration, then uncomment. Issue https://github.com/aspnet/EntityFrameworkCore/issues/2167 is about making this experience better.
