### ISSUE TITLE
Can EF have two database (mssql and postgres) in one project ?

### ISSUE THREAD

**Issue by lunyi** [aspnet/EntityFramework6#1436]
Hi all 
As title described, Can EF have two database (mssql and postgres) in one project ? 
I will move mssql  to postgres, but I need two databases exist during transition. 
It will insert the same data into mssql and postgres. Then read data from different API. 

I created two DbContexts for two databases
but it seems to be only one defaultConnectionFactory  in the web.config to decide we use which one db provider. Do we have any solution for my requirement ? 

### Further technical details
EF version: 6.2
Database Provider:  EntityFramework.SqlServer, EntityFramework6.Npgsql
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.13

**Comment by ajcvickers** [comment]
@lunyi Yes, you can use multiple databases by using multiple models; one for each database. You will of course have to explicitly pass in the connection string since it will be different in each case.
