### ISSUE TITLE
.NET Standard 2.0 Target

### ISSUE THREAD

**Issue by JonathanHopeDMRC** [aspnet/EntityFramework6#1439]
We have a larger legacy WCF app that we are slowly moving towards a .NET Core app. Ideally we would be moving a single project here and there to .NET Standard 2.0 starting on the bottom layer and moving up.

This has been going very well apart from Entity Framework 6.X. Because the top layer is still necessarily running on .NET Framwork 4.X we can't make our libraries .NET Standard 2.1. I imagine there are a lot of legacy projects out there that would appreciate the simple migration path afforded by a .NET Standard 2.0 target for Entity Framework 6.X.

I understand that there isn't a .NET Standard 2.0 target now, but will there every be? Or is the expected migration path to convert our data layer to an older EF Core release?

### Steps to reproduce
Try use Entity Framework 6.3+ with a .NET Standard 2.0 class library.

### Further technical details
EF version: 6.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
@JonathanHopeDMRC We don't have any plans for a .NET Standard 2.0 release. The .NET 4 and .NET 4.5 targets exist for .NET Framework, and the .NET Standard 2.1 target supports .NET Core 3.0. You may need to multi-target your app.

**Comment by AroglDarthu** [comment]
@ajcvickers This is really inconvenient. The use case is that legacy applications need to be ported to .net core sometime in the future. One of the first steps that we are taking, is to port all class library projects to .NET Standard 2.0.

After that, the only remaining Full Framework projects will be ASP.NET front-end applications. ALL other projects can be reused in .net core 3.0 applications.

Migrating the ASP.NET front-end applications is a whole other ball game. Especially if WCF is involved as well.

With the decision to not support .NET Standard 2.0, this whole approach will get stuck on the data access layer projects and every project that has a dependency on it. Leaving only the big-bang migration as an option, which really isn't an option either.

EF Core 3.1 now also targets .NET Standard 2.0

Please, reconsider the standpoint for a .NET Standard 2.0 release.
