### ISSUE TITLE
PMC: Support cross-targeting and ASP.NET Core projects

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework6#146]
The new VS2017 cross-targeting and ASP.NET Core (on .NET Framework) projects will require updates from us to make commands like `Add-Migration` and `Update-Database` work.

The DTE Project object isn't marshal-by-ref either. (See dotnet/roslyn-project-system#934) If we can't get that changed it will require architectural changes on our end to make them work.

**Comment by rowanmiller** [comment]
Closing as you can workaround this using a class library. We will reconsider if we get a lot of requests for this though.

**Comment by bricelam** [comment]
> DTE Project object isn't marshal-by-ref

We had CPS give us a private build with that change, but we hit additional issues. In the end we decided if it was going to require changes on our end, we should just update everything to use an architecture similar to EFCore which completely avoids the need for them to be `MarshalByRef`.

**Comment by bricelam** [comment]
Another workaround: [mrahhal/Migrator.EF6](https://github.com/mrahhal/Migrator.EF6)

This allows you to use `dotnet ef` with EF6.
