### ISSUE TITLE
EF 6.3 Powershell Command notwork on Windows 7 (PS2)

### ISSUE THREAD

**Issue by andrensairr** [aspnet/EntityFramework6#1469]
Since updating to EF6.3 the Package Manager Console commands are no longer working on my Windows 7 machine. The same work fine on Windows 10 without issue. The PowerShell 2 module appears to be failing to load:

```
Missing function body in function declaration.
At C:\project path\packages\EntityFramework.6.3.0\tools\EntityFramework6.PS2.psm1:241 char:5
+      <<<< WarnIfOtherEFs 'Enable-Migrations'
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingFunctionBody
 
Import-Module : The module to process 'EntityFramework6.PS2.psm1', listed in field 'ModuleToProcess' of module manifest 'C:\project path\packages\EntityFramework.6.3.0\tools\EntityFra
mework6.PS2.psd1' was not processed because no valid module was found in any module directory.
At C:\project path\packages\EntityFramework.6.3.0\tools\init.ps1:11 char:18
+     Import-Module <<<<  (Join-Path $PSScriptRoot 'EntityFramework6.PS2.psd1')
    + CategoryInfo          : ResourceUnavailable: (EntityFramework6.PS2:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

If I roll the installed version back to EF 6.2, there are no problems loading the commands module. If I upgrade to the latest preview version EntityFramework.6.4.0-preview3-19553-01, the error still occurs.

### Steps to reproduce

* Create a new project/solution
* Manage NuGet Packages for Solution..
* Install EntityFramework v6.3

The PowerShell commands module fails to load with the error described above.

### Further technical details
EF version: 6.3
Database Provider: EntityFramework.SqlServer
Operating system: Windows 7
IDE: VS2019 16.3.9

**Comment by ajcvickers** [comment]
@andrensairr You will need to update to at least PowerShell 3.
