### ISSUE TITLE
The code don't work

### ISSUE THREAD

**Issue by jt4000** [aspnet/EntityFramework6#1478]
Based on the instruction I have followed
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/

The black marked selection from the picture don't work.

How is it possible that the code works for you?

![g1](https://user-images.githubusercontent.com/14993569/69254658-e1e42480-0bb6-11ea-92f0-ecd5dbbc4e15.png)
![g2](https://user-images.githubusercontent.com/14993569/69254659-e1e42480-0bb6-11ea-8300-9d2b18258be4.png)

![g3](https://user-images.githubusercontent.com/14993569/69254803-17890d80-0bb7-11ea-914e-094766c1ddd1.png)
![g4](https://user-images.githubusercontent.com/14993569/69254804-1821a400-0bb7-11ea-9616-a2a5397cf157.png)

**Comment by ErikEJ** [comment]
You are missing some using statements?

**Comment by ajcvickers** [comment]
@ErikEJ's answer seems correct.
