### ISSUE TITLE
After deleting an entity, ChangeTracker.HasChanges() errors with "Adding a relationship with an entity which is in the Deleted state is not allowed." even though SaveChanges is fine and same change can be made at database level 

### ISSUE THREAD

**Issue by Mamikel** [aspnet/EntityFramework6#1497]
My application is saving fine.  I'm now trying to introduce auditing by using the ChangeTracker on the db context.  This is working fine except in some cases where I'm removing an entity from a collection.  In this case as soon as I try to determine whether there are changes via the ChangeTracker.HasChanges(), I get the aforementioned error.  

I'd like to reiterate, the EF saves the changes fine and I can also perform the deletion at the database level.  So my foreign keys are certainly not preventing the deletion.  So, all was hunky-dory until I started trying to utilise the ChangeTracker to grab the changes for auditing purposes.

I can see the error is being thrown in the DetectConflicts method at line 3383 based on the error coming back.  Unfortunately, this provides only a generic message so I can't get any specifics as to why the ChangeTracker is complaining.  

```
                //Ensure new graph relationships do not involve a Deleted Entity
                if (addedRelationshipsByGraph != null
                    && addedRelationshipsByGraph.Count > 0)
                {
                    if (entry.State
                        == EntityState.Deleted)
                    {
                        throw new InvalidOperationException(Strings.RelatedEnd_UnableToAddRelationshipWithDeletedEntity);
                    }
                }

```
**StackTrace:**
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectConflicts(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Core.Objects.ObjectContext.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Infrastructure.DbChangeTracker.HasChanges()

**Comment by ajcvickers** [comment]
@Mamikel Please post a small, runnable project/solution or complete code listing so that we can investigate.

**Comment by Mamikel** [comment]
> 
> 
> @Mamikel Please post a small, runnable project/solution or complete code listing so that we can investigate.

Yes, will do.  On playing with it a bit, I found that by relaxing one of the FK constraints in the child object, it then goes through.  I'll see if I can provide a sample which illustrates both scenarios.

**Comment by Mamikel** [comment]
Hmm, I've tried replicating the issue from scratch in a new project, but I'm unable to.  There have been a lot of migrations in the application it's occurring in.  I'll look into resetting the schema, I think I saw something on how to do it on Rick Strahl's blog.
