### ISSUE TITLE
about EF 6.4

### ISSUE THREAD

**Issue by iulian0512** [aspnet/EntityFramework6#1507]
Can you tell us what's new in v6.4 or what's planned for this version ? Thanks.

**Comment by MagicAndre1981** [comment]
Here are all closed issues for 6.4:

https://github.com/aspnet/EntityFramework6/milestone/14?closed=1

**Comment by ajcvickers** [comment]
See https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-1-and-entity-framework-6-4/
