### ISSUE TITLE
install.ps1 isn't run in PackageReference projects

### ISSUE THREAD

**Issue by NetherGranite** [aspnet/EntityFramework6#1509]
When migrating from `packages.config` to `PackageReference` using [this official tool in Visual Studio 2019](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference), the tool warns that Entity Framework's `install.ps1` won't be run as such files are not supported in the new `PackageReference` format. Is this okay?

### Further technical details
EF version: 6.3.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2019 16.3.5

**Comment by ajcvickers** [comment]
@NetherGranite Depends what you mean by "okay". It's okay in the sense that the package is still usable. However, not being able to run a script on installation means that some things that may have been configured automatically, such as the default connection factory, may now need to be configured manually.

**Comment by NetherGranite** [comment]
@ajcvickers Is there any documentation stating that some things have to be configured manually in a project that uses `PackageReference` and how to do so, or does EF6 not officially support `PackageReference` projects?

**Comment by ajcvickers** [comment]
@NetherGranite It is supported, but we haven't yet [completed the documentation](https://github.com/aspnet/EntityFramework.Docs/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-ef6).

This is the way to think about EF6 on .NET Core: it works and is supported, but the experience was designed for .NET Framework in ways that are not a good match for .NET Core. For example, EF6 configuration is based heavily on `app.config`, which has only minimal functionality in .NET Core. Likewise, .NET Core/modern NuGet requires package references to work correctly, but the NuGet experience for package references doesn't support an install script, which EF6 uses to setup the app.config, and so this can't be done.
