### ISSUE TITLE
is there any plan to release entity framework 6.4+ with .NET standard 2.0 support

### ISSUE THREAD

**Issue by muhammadmubashirkhan** [aspnet/EntityFramework6#1538]
is there any plan to release entity framework 6.4+ with .NET standard 2.0 support so that it can be used with .net core 3.1

**Comment by ajcvickers** [comment]
@muhammadmubashirkhan EF 6.4 already supports .NET Core 3.1 through .NET Standard 2.1. We don't plan to add support for .NET Standard 2.0.

**Comment by amitkub** [comment]
I think that this means that you can't use .Net Standard to slowly migrate a project from .Net Framework to .Net Core if you are using Entity Framework.

I will explain:
1. I have a project using EF6 and .Net Framework ~4.7
2. I want to migrate slowly to .Net Core without multi-targeting
3. My solution, move projects slowly to .net standard, but:
a. I can't use .net standard 2 as EF 6 doesn't support it
b. I can't use .net Standard 2.1 as .net framework doesn't support it
So - I must use mutli-targeting?

**Comment by rangav** [comment]
I am also facing same issue as EF 6.4 does not support .Net Standard 2.0, its making more complicated to share database code between .net core and .net framework projects.

I am using

1. Mvc 5 web with EF 6
2. Asp core 3.1 for api project with EF core

Unfortunately cant share DB logic between the 2 projects. 
EF 6.4 made a strange decision not to support .net standard 2.0

**Comment by ajcvickers** [comment]
@rangav See the discussion here: https://github.com/dotnet/ef6/issues/1571
