### ISSUE TITLE
Discriminator column not updated correctly when introducing inheritor.

### ISSUE THREAD

**Issue by Michael-Danfoss** [aspnet/EntityFramework6#1539]
Introducing an inheritor to a class that is referenced in a DbSet prompts AutomaticMigrations to introduce scaffolding to support saving the inheritor to the database, even though the inheritor is not referenced or ever intended to be saved in the database.
Data saved to the database prior to the migration is no longer reachable via the DbSet that references it, it will never be returned. You can get tracked instances out via Database.SqlQuery<T>() still.

## Steps to reproduce

Create a Console Application targeting .Net Framework. Install EntityFramework 6.4.0 and EntityFramework.SqlServerCompact 6.4.0 from whichever NuGet repo you use.

### Program.cs
```c#

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp2
{
	class Program
	{
		static void Main(string[] args)
		{
			Database.SetInitializer(new MigrateDatabaseToLatestVersion<MyContext, MyContextConfiguration>());

			using (var ctx = new MyContext())
			{
				var things = ctx.Things.ToList();
				Console.WriteLine(things.Count);
			}
		}
	}

	class Thing

	{
		public string Id { get; set; }
		public string SomeProperty { get; set; }
	}
	class MyContext : DbContext
	{
		public MyContext() : base("name=MyModel") { Database.CreateIfNotExists(); }
		public virtual DbSet<Thing> Things { get; set; }
	}

	internal sealed class MyContextConfiguration : DbMigrationsConfiguration<MyContext>
	{
		public MyContextConfiguration()
		{
			AutomaticMigrationsEnabled = true;
		}

		protected override void Seed(MyContext ctx)
		{
			ctx.Things.Add(new Thing() { Id = Guid.NewGuid().ToString(), SomeProperty = "Hello" });
			ctx.SaveChanges();
		}
	}
}

```

## App.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
        <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
        <section name="entityFramework"
          type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
          requirePermission="false"/>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 --></configSections>
  <connectionStrings>
    <add name="MyModel" connectionString="Data Source=|DataDirectory|\mydb.sdf;Persist Security Info=false;" providerName="System.Data.SqlServerCe.4.0"></add>
  </connectionStrings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1"/>
    </startup>
    <entityFramework>
        <providers>
            <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"/>
            <provider invariantName="System.Data.SqlServerCe.4.0"
                type="System.Data.Entity.SqlServerCompact.SqlCeProviderServices, EntityFramework.SqlServerCompact"/>
        </providers>
        <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlCeConnectionFactory, EntityFramework">
            <parameters>
                <parameter value="System.Data.SqlServerCe.4.0"/>
            </parameters>
        </defaultConnectionFactory>
    </entityFramework>
<system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SqlServerCe.4.0"/>
      <add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0"
          description=".NET Framework Data Provider for Microsoft SQL Server Compact"
          type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91"/>
    </DbProviderFactories>
  </system.data></configuration>
```

With automatic migrations enabled the above should be a valid DB model and code to work with it. Run the code once to make EF seed the database with a single item. Then comment out the Seed method body.

Everything works as expected. If we now introduce an inheritor to Thing somewhere in the codebase that is findable by EF, automatic migrations will introduce the Discriminator column in the table Things, but won't update the discriminator for the old data. This causes subsequent queries to the DbSet with Things to never return elements that does not have a discriminator set.

If we change the above Program.cs code to this:

```c#
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp2
{
	class Program
	{
		static void Main(string[] args)
		{
			Database.SetInitializer(new MigrateDatabaseToLatestVersion<MyContext, MyContextConfiguration>());

			using (var ctx = new MyContext())
			{
				var things = ctx.Things.ToList();
				Console.WriteLine(things.Count);
			}
		}
	}

	class Thing

	{
		public string Id { get; set; }
		public string SomeProperty { get; set; }
	}

	class SuperThing: Thing { public string SuperProperty { get; set; } }

	class MyContext : DbContext
	{
		public MyContext() : base("name=MyModel") { Database.CreateIfNotExists(); }
		public virtual DbSet<Thing> Things { get; set; }
	}

	internal sealed class MyContextConfiguration : DbMigrationsConfiguration<MyContext>
	{
		public MyContextConfiguration()
		{
			AutomaticMigrationsEnabled = true;
		}

		protected override void Seed(MyContext ctx)
		{
			//ctx.Things.AddOrUpdate(new Thing() { Id = Guid.NewGuid().ToString(), SomeProperty = "Hello" });
			//ctx.SaveChanges();
		}
	}
}
```

The console line in Main will now return 0 elements even though, upon inspection, the database contains 1 element.

### Expected Behavior

EF should update the discriminator when running migrations, or alternatively reject instances that are not an exact type match to the DbSet.

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServerCompact
Operating system: Windows 10
IDE: Visual Studio 2017 Professional 15.9.18

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
