### ISSUE TITLE
Fluently ignored classes always cause errors

### ISSUE THREAD

**Issue by npbenjohnson** [aspnet/EntityFramework6#157]
TypeMapper 131:
```
if (_mappingContext.ModelConfiguration.IsIgnoredType(type)
  || _mappingContext.ModelConfiguration.IsComplexType(type))
{
  return null;
}
```
DbModelBuilder 468:
```
if (typeMapper.MapEntityType(type) == null)
{
  throw Error.InvalidEntityType(type);
}
```
Summary of Ignore Method on DbModelBuilder:
```
/// <summary>
/// Excludes a type from the model. This is used to remove types from the model that were added
/// by convention during initial model discovery.
/// </summary>
```
Fluently ignored models always throw errors. If calling DbModelBuilder.Ignore(Types) to ignore types is not the case that the Ignore summary claims to be for, what usage is correct?

**Comment by AndriySvyryd** [comment]
@npbenjohnson That exception is thrown if you have conflicting configuration, something like this:
```C#
ModelConfiguration.Entity(typeof(Product));
ModelConfiguration.Ignore(typeof(Product));
```
You can either add an entity type to the model or ignore it, but not both.

**Comment by npbenjohnson** [comment]
Thanks, that is definitely the cause of my error. I was assuming it's an override to let you conventionally ignore classes if they aren't used in a particular scenario (ex. ignoring the entities for abstract base classes when a TPC `EntityMappingConfiguration` is set up using `MapInheritedProperties`)

What is the use case for `DbModelBuilder.Ignore`, does it remove types from `DbModelBuilder.Types()`?

I'm hoping my flow is just backwards, I'm registering all potential entities, then iterating `DbModelBuilder.Types` and `DbModelBuilder.Properties` to set them up. Should I be using `Type<>`, then iterating, then only registering Entities for Types that aren't Ignored?

**Comment by AndriySvyryd** [comment]
EF usually discovers all the entity types by following navigation properties and finding derived types, so normally you would only add the root types that don't have a corresponding `DbSet` on the context. Ignore is used to remove the types that EF discovers by itself.
`DbModelBuilder.Types` will work for the entity types discovered by EF.
