### ISSUE TITLE
Migration commands fail for projects in a visual studio solution folder

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#17]
# Migration commands fail for projects in a visual studio solution folder
## Functional impact

Migrations stop working as long as the project remains in the solution folder. The workaround of moving the project into the solution root, doing the migration and moving it back into the solution folder works, but isn't that obvious.
## Minimal repro steps
1. Create a project
2. Add nuget package for EF latest stable (6.1.3)
3. Enable migrations
4. Create a solution folder
5. Move the project into the solution folder
6. Try to add a migration
## Expected result

Migration is added
## Actual result

Command fails with the message The EntityFramework package is not installed on project ''.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2804

**Comment by bricelam** [comment]
### Workaround

Closing and re-opening Visual Studio seems to fix the issue. This may be an issue in NuGet. I'll continue to investigate.

Also, if you move the project into the folder before installing EntityFramework, it works.

**Comment by bricelam** [comment]
It seems to be a NuGet issue. `Get-Project` returns `$null` after the default project is moved.
