### ISSUE TITLE
TPC Ignore throws unexpected exceptions due to MapDerivedTypes

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#170]
_From @npbenjohnson on December 16, 2016 1:45_

I know this example isn't the best usage, but it's for back-loading ef into as a provider in legacy code. There may be more reasonable TPC scenarios this breaks, but I've only found this one.

Simple Data Structure:
```
namespace A {
  public class EfModel : EfModelBase {}
  public class EfModelBase : {
    public Guid? Id {get;set;}
    public Repository Repo {get; set;}
  }
}
namespace B {
 [Serializable()]
 public class ModelForOtherSystem : EfModel {}
}
```

Now using fluent conventions, 
1. EfModel is registered
2. `MapInheritedProperties()` is called on all registered entities
3. `Ignore()` is called on all `Repo` properties

When the model spins up, `MapDerivedTypes` causes `ModelForOtherSystem` to be mapped, but because it (purposely) wasn't added to the model, `MapInheritedProperties()` was never called against it, so it throws  "You cannot use Ignore method on the property 'Repo' on type 'B.ModelForOtherSystem' because this type inherits from the type 'A.EfModel'"

The message is also counter-intuitive, because Repo is mapped to the model in the message, but it isn't declared on it, which I think is fuzzy based on the word "on" and the fact that the error message contains namespaces which generally mean clr, not db, context.

I think the assumption that could fix this is that the derived types of TPC classes are themselves TPC classes?

_Copied from original issue: aspnet/EntityFramework#7255_

**Comment by rowanmiller** [comment]
@npbenjohnson is `ModelForOtherSystem` intended to be part of the model, or should it be excluded (i.e. undo what we do by convention in `MapDerivedTypes`)? If the desire is for it to not be in the model, then does ignoring it resolve the issue?

> I think the assumption that could fix this is that the derived types of TPC classes are themselves TPC classes?

This may be a reasonable assumption, but is not the current behavior. Changing it would be a large breaking change, so it's not something we would take at this stage in the EF6.x lifecycle. We will take this as input though when we design non-TPH inheritance mapping in EF Core.
