### ISSUE TITLE
Adding an EF 6.x DbContext Generator to .NET Core project generates many errors

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#177]
_From @davkean on January 20, 2017 4:19_

_From @BillHiebert on January 19, 2017 18:53_

VS build D15Rel.26116.00

1, New .NET Core class library
2. R-click\Add new Item. Search for "Entity". 
3. Select the EF 6.x DbContext Generator, OK

You get a couple of errors like the following
```
---------------------------
Microsoft Visual Studio
---------------------------
Package Installation Error
Could not add all required packages to the project. The following packages failed to install from 'C:\Program Files (x86)\Entity Framework Tools\NuGet Packages':

EntityFramework.6.1.3 : Package restore failed. Rolling back package changes for 'ClassLibrary1'.
---------------------------
OK   
---------------------------
```
Followed by:
```
---------------------------
Microsoft Visual Studio
---------------------------
The reference "System" could not be added to the project. This wizard will continue to run, but the resulting project may not build properly.
---------------------------
OK   
---------------------------
```

_Copied from original issue: dotnet/roslyn-project-system#1260_

_Copied from original issue: aspnet/EntityFramework#7449_

**Comment by divega** [comment]
_From @davkean on January 20, 2017 4:19_

Is this thing supposed to show up for .NET Core projects? This sounds like a EF bug.

**Comment by divega** [comment]
_From @davkean on January 20, 2017 4:19_

tag @ajcvickers, @bricelam

**Comment by davkean** [comment]
Inception...

**Comment by divega** [comment]
@davkean we can still move it a few mor times :smile:

**Comment by rowanmiller** [comment]
We should see if there is an easy way to prevent the EF6.x item templates from showing up for .NET Core projects. @lajones talk to @bricelam if you can't get to this one.

**Comment by lajones** [comment]
@rowanmiller I've talked with @bricelam and we can't see any way to prevent the item templates from showing up for .NET Core while at the same time retaining them for other project types. I've sent mail out to the VSTemplate team but unless things have changed for VS2017 we don't think there's a way to do this.

**Comment by davkean** [comment]
Sure there is, notice how lots of other templates aren’t present in .NET Core but are when targeting .NET Framework?

There’s a variety of ways to prevent this:

- TFM in the template
- Project Capabilities – is this template only relevant when the package is installed? If so, have a capability handshake between the template and package so that it only shows up based on that.

**Comment by lajones** [comment]
Reading the repro steps more closely - the "Search" step is important. If you just right-click the project and do "Add New Item" all our item templates are *not* there for .NET Core projects (they are there for .NET Framework ones). However once you do the search step they appear and stay available in the list of items until the Add New Item dialog is closed. If you then re-open the dialog they are not there again until you search again.

This seems to affect any item template that is not available the first time. E.g. if you search for "Cursor" the Cursor File item template will start to show up but so will all the others, including Entity Framework.

I will need to talk to the vstemplate folks to get some guidance on what's happening here.

(Tested on build d15rel 26117.0)

**Comment by rowanmiller** [comment]
@lajones given that, I think we can just hand this off and consider it external to EF.

**Comment by lajones** [comment]
@rowanmiller I've raised a report via VSFeedback for the "Add New Item" folks within VS to address this. Once the search acts properly it will no longer be possible to do step 3 of the original repro.

**Comment by davkean** [comment]
Any reason you didn't file a bug?
