### ISSUE TITLE
Change Category of EF6 Tools Inidividual Component to Code Tools

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#180]
In the VS 2017 installer the EF6 Tools individual component is currently listed under the "SDK, libraries and frameworks" category. After discussion with @divega we think it would fit better under "Code tools". This is a reminder to change that.

**Comment by lajones** [comment]
@ajcvickers @divega Just checking - do you still want to do this?

**Comment by divega** [comment]
@lajones I would like us to do it but it is not a high priority this time around either, especially because out tools get installed by default in all the relevant workloads.

**Comment by ajcvickers** [comment]
@lajones Talked to Diego. Let's not do this.
