### ISSUE TITLE
Fix in PR #41 for updating large models from database has additional issues

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#185]
https://github.com/aspnet/EntityFramework6/pull/41 very ingeniously fixes issues with large models by consolidating parameters of schema discovery queries that contain the same values.

I have observed a few issues with it though:

1. Modifications and additional public surface on runtime pieces like EntityClient seem unnecessary
2. We would need to verify that this works with third party providers: 
 - SQL Server is the only provider for which we know 100% the fix is needed 
 - Any provider that implements schema discovery by faking the execution of schema discovery queries may have a hard dependency with the position of the parameters in the parameter collection

**Comment by divega** [comment]
@bengutt @IanYates Assuming you have been able to build the EF Tools from source, it would be great if you could do a quick validation that the reworked version of the fix works for you.

**Comment by IanYates** [comment]
My VS2015 installation is dead and I need to update a model today.  Back to the source, build and see if I can shoehorn into 2017...  I'll let you know.

**Comment by IanYates** [comment]
Success.
I did a fresh fetch of master, opened 2017 dev prompt and built EF and the tools.  A *lot* of the tests in the EF build failed...
I then overwrote these files in `progX86\Microsoft Visual Studio\2017\Enterprise\Common7\IDE`

![image](https://cloud.githubusercontent.com/assets/1314477/25161382/fb9f51b6-24fe-11e7-8e35-cbdf4da6b0ba.png)

I'm now able to update my model.  Thank you again!  🙌 

I briefly tried the build in the 2015 dev prompt but that failed due to .NET 4.6 targeting in one or more of the projects.  No big deal for me but it might be worth mentioning in your docs that 2017 seems to be the minimum (or perhaps at least a targeting pack being present for older VS versions)

**Comment by IanYates** [comment]
Is this present in the new VS 2017 Update 3  (VS 15.3) release that came out this week?

**Comment by raxitr** [comment]
I am facing issue in new VS 2017 15.4.5. What exactly needs to be done to apply this fix?

**Comment by ErikEJ** [comment]
I think you need to wait for updated tools for VS 2017, or install the EF 6.2 beta tools in VS 2015 (for example the free Community edition), and run the design process there.

**Comment by CZEMacLeod** [comment]
@ErikEJ Are the VS2017 tools an 'extension' (as most of VS2017 is now) or are they part of the main application? E.g. Is it possible to get out of band updates vs. the VS2017 release schedule and possibly install pre-release/beta versions?

**Comment by ErikEJ** [comment]
I would expect them to be an VSIX (extension) yes - but not sure about out of band options.

**Comment by ErikEJ** [comment]
@CZEMacLeod  To get the 6.2 bits installed with VS 2017, you could install the 6.2 beta tools: 
https://www.microsoft.com/en-us/download/details.aspx?id=55259 
and then copy the relevant dll files into your VS 2017 install, as described above: https://github.com/aspnet/EntityFramework6/issues/185#issuecomment-295048960 

@divega : We need the EF 6.2 Tools for VS 2017 very soon!

**Comment by raxitr** [comment]
Thank you Erik but just copying does not seem to be working. I ended up getting The 'Microsoft.Data.Entity.Design.Package.MicrosoftDataEntityDesignPackage' package did not load correctly. error and EDMX file has stopped opening. I am definitely doing something wrong here! I am not sure it is Ok to discuss issue I am facing so let me know if there are any detailed instructions available elsewhere. Thank you!

**Comment by IanYates** [comment]
I see this made it to the latest VS 2017 (v15.7) release!
Excellent 😀 

Thanks for getting it shipped - I appreciate it's not easy to swap in new tools versions in such a massive product.

**Comment by divega** [comment]
Thanks to you and sorry it took so long :blush: @bengutt’s PR is one of the most impactful contributions we have had on the designer.
