### ISSUE TITLE
New untracked Commands.vsct file generated on every EFTools build

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#192]
Every time I run `BuildEFTools.cmd /t:build` the file `src/EFTools/EntityDesignPackage/Commands.vsct` gets re-generated on my machine. The file is untracked and not ignored by git.

It seems that in a recent change we intentionally switched to have two separate files depending on the VS version tracked in the repo:

`Commands_VS15.vsct` 
`Commands_preVS15.vsct`

But we should probably do something to avoid the untracked file.

**Comment by lajones** [comment]
We do need separate .vsct files to support the package-load initiative.

Easiest solution would be to add `Commands.vsct` to the `.gitignore` file.

**Comment by lajones** [comment]
Fixed with commit 946b7592f. See #200.
