### ISSUE TITLE
VS2017: EF Tools uninstalled on build to build upgrade

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#196]
I haven't tried to repro this yet, but I saw it reported at https://developercommunity.visualstudio.com/content/problem/16970/entity-framework-not-opening-in-design-mode.html?childToView=17914#comment-17914.

AFAIR we have previously seen this behavior and it was the result of some issue with the installer or with VS setup authoring.

cc @lajones

**Comment by anselantz** [comment]
Steps in reproducing error.
Before update.
![image](https://cloud.githubusercontent.com/assets/3521188/22740249/f9334468-eddc-11e6-9785-0dbe89418d3d.png)
Update Notification
![image](https://cloud.githubusercontent.com/assets/3521188/22740296/34724ef2-eddd-11e6-9d3e-0b137a3f5e68.png)
Updating via VS Installer
![image](https://cloud.githubusercontent.com/assets/3521188/22740395/962a122e-eddd-11e6-94f8-97c0bf73146b.png)
Update Complete
![image](https://cloud.githubusercontent.com/assets/3521188/22740603/6f83f4cc-edde-11e6-8b6c-4f5c22fa9b7e.png)
Reboot Complete, VS Started, Double Clicked .edmx
![image](https://cloud.githubusercontent.com/assets/3521188/22740895/5fbf76a0-eddf-11e6-9bf4-0139cab28ab2.png)

**Comment by anselantz** [comment]
Fixed this by, opening Insaller, Modify and Reselect .NET desktop development Workload
![image](https://cloud.githubusercontent.com/assets/3521188/22740998/b8d27b84-eddf-11e6-9554-59a49e317bfa.png)
file now opens in design
![image](https://cloud.githubusercontent.com/assets/3521188/22741153/308359d2-ede0-11e6-833c-d5958e223c51.png)

**Comment by lajones** [comment]
@anselantz - thanks very much for the detailed repro steps. That will help us track it down.

**Comment by lajones** [comment]
@anselatz I am unable to repro. Some install logs are generated under %TEMP% when you run the installer. If you are still able to repro this can you clear out %TEMP% and then run the Update and send the logs that happen during that time, especially any with "EntityFramework" in the name. You can forward them to my user name at microsoft dot com.
