### ISSUE TITLE
Using custom EF builds - public signing service?

### ISSUE THREAD

**Issue by davidroth** [aspnet/EntityFramework6#197]
Disclaimer: This is also a general question which applies to all microsoft open source libs, but I am posting it here because it currently affects me in context of EF.

Story:
For a large project we have been using my custom [fork](https://github.com/davidroth/EntityFramework6/tree/DbModelStore) to overcome[ this issue](http://entityframework.codeplex.com/workitem/1876).

Since it took almost 2 years for this feature to land into EF master (and still not released) (https://github.com/aspnet/EntityFramework6/pull/40), I am happy that at least we had the opportunity to use my custom EF version (we could not wait 2 years for this feature - so open source FTW! 👍 )

However, If you want to use a custom EF version, you need you to build it using your own signing key because the official MS signing key is obviously not public.  

This leads to the following problem:

All external tools  (e.x. Linqpad) / libraries  (ex. extensions for EF6) reference the official strong named version of EF6. So these tools/libs will not work with your custom build and so you cannot use them.
This is a major drawback and really sucks.

Because #40 is now resolved and will land in EF 6.2, I am planning to switch back to the official nuget version of EF. This will allow tools depending on the offical version to work again. However, as soon as I would need a custom build again (for example a new fix which will need its time before landing in official), I'd have all of these problems again. (And i would probably have to remove third party EF extensions because they would break again)

I think this could be solved if microsoft could provide a public signing / build service or something similar. Is there any way of solving this issue?

**Comment by rowanmiller** [comment]
Unfortunately if we solved this, then anyone would be able to use the mechanism, which would defeat the purpose of strong naming.

You could use [our nightly builds](https://github.com/aspnet/EntityFramework6/wiki/Nightly-Builds), which are signed and include the fix you want.

You could also look at disabling strong name verification for the EF runtime (see bullet 6 of [Building the Runtime](https://github.com/aspnet/EntityFramework6/wiki/Building-the-Runtime)). Obviously there is some risk with doing that.

**Comment by davidroth** [comment]
@rowanmiller Thanks for your feedback.

I have a question though:

What do you mean by this:
> if we solved this, then anyone would be able to use the mechanism, which would defeat the purpose of strong naming.

According to [the corefx wiki](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md),  strong-names are used for identity, and not for security.  
Furthermore it's the recommended practice to check-in the signing key to enable drop in replacements for open source libraries. 

While i understand that you cannot publish the signing key for EF6 (since this is the global signing key MS uses for all it's libs since .NET 1.0?), I don't understand how a public signing service would defeat the purpose of strong naming? 
Remember: For all Core** related projects everyone has access to the signing key, so this obviously does not defeat the purpose of strong naming.

Could you please elaborate this? Thanks :)

**Comment by rowanmiller** [comment]
Fair point, to be a little more explicit...

>  I don't understand how a public signing service would defeat the purpose of strong naming?

The issue is that EF6 is signed with a Microsoft key. So if we had a public service then the output would be signed as if it were owned by Microsoft. With EF Core, we decided not to do this and we only strong name so that it can be consumed from strong named applications - not as a way to help verify the producer.

We can't really move EF6 to that model, because changing the key would break everything that currently works with EF6.

**Comment by davidroth** [comment]
Thanks for the clarification @rowanmiller 
I am glad that at least this is solved with EF Core and all other DotNet Core projects.
