### ISSUE TITLE
Eager loading, automatic navigation properties.

### ISSUE THREAD

**Issue by Ruud-cb** [aspnet/EntityFramework6#203]
As stated on the core documentation, but also in EF6:

> Entity Framework Core will automatically fix-up navigation properties to any other entities that were previously loaded into the context instance. So even if you don't explicitly include the data for a navigation property, the property may still be populated if some or all of the related entities were previously loaded.
https://docs.microsoft.com/en-us/ef/core/querying/related-data

While this is probably awesome in most Scenarios, it can lead to trouble as well. In my application I have some automatic conversions in place, these are extensions. These extensions call other extensions to convert a an entity to a model. But they can call each other in case it has a relation. One is an extension for converting an `IEnumerable`, other is to convert a single object. 

From a perspective of Eager loading, what is included should be loaded, e.g.: 

    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .ToList(); 

I would expect that all Posts are loaded for the blogs. But a single post has a relation back to blog. Currently that navigation property will be filled automatically and include the same blog again. BUT that automatic filled blog property, also has a collection of posts again.

Do you see where I can have a `stackoverflow exception`? My extensions keep looping through them.
For one relation it is easy to fix, just give your source type, see if it is different and don't load it again. But in an bigger application, you might have 3 entities that reference each other in a "circle". 

This is explained in this question: http://stackoverflow.com/questions/42189600/only-include-what-is-included-entity-framework

While solutions are there, I call it workarounds, I think it is better to have a configuration setting that can turn off this automatic navigation property that were previously loaded. We now have options for lazy loading to be turned off and proxies to be turned off. I think this is a missing feature.
Could this be developed?

**Comment by rowanmiller** [comment]
This isn't something we would implement. Relationship fixup is key to EF and is would be a mammoth undertaking to implement it and then deal with the side effects of relationships not being fixed up, as the stack always assumes they are. There would be wide reaching implications in change detection etc.
