### ISSUE TITLE
Cache Metadata per AppDomain instead of per DB connection string

### ISSUE THREAD

**Issue by vukoje** [aspnet/EntityFramework6#205]
According to [this link](https://msdn.microsoft.com/en-us/library/hh949853%28v=vs.113%29.aspx#3-4-Metadata-caching) EF metadata (mappings, queries...) is being cached per database connection string which can be a performance issue in multitenant web app where **each customer has separate database with identical schema**.

Consider scenario where there is 1 App with 100 users logged in and each user is from different company. Each company has their own DB with identical schema. This could cause big jump in memory consumption because same metadata would be stored 100 times. Also each customer would experience cold start.

To me it seems that if one DbContext is used across multiple DBs, it's more likely that those DBs have identical schema than having it different and hence there should be no need for separate cache per connection string.

I also found [this link](https://blogs.msdn.microsoft.com/appfabriccat/2010/10/22/holding-a-reference-to-the-ef-metadataworkspace-for-wcf-services/) describing forced MetadataWorkspace caching and I'm wondering would doing something like this help until EF supports this.?

Please advise

**Comment by rowanmiller** [comment]
That link is specifically about EDMX based models, is that what you are using?

**Comment by vukoje** [comment]
I'm using Code First. Which link are you referring to, first one or second?
As I understood [this link](https://msdn.microsoft.com/en-us/library/hh949853%28v=vs.113%29.aspx#3-4-Metadata-caching), behavior is present in Code First.

**Comment by rowanmiller** [comment]
Code First is actually quite a bit smarter, it uses the context type and database provider as the cache key. You can [see the implementation here](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Internal/DefaultModelCacheKeyFactory.cs). You can also customize how the cache key is generated, but it sounds like the default implementation is already what you want.

**Comment by vukoje** [comment]
Great news. Thanks a lot @rowanmiller.
I'm closing the case and I of course suggesting updating info in [this link](https://msdn.microsoft.com/en-us/library/hh949853%28v=vs.113%29.aspx?f=255&MSPPError=-2147217396#3-4-Metadata-caching) to avoid further confusion.
