### ISSUE TITLE
Doesn't see indexes on columns.

### ISSUE THREAD

**Issue by dannyboyng** [aspnet/EntityFramework6#207]
When generating/scaffolding models with Code First from existing database, Code First doesn't see my composite indexes on the columns and therefore, the indexes won't show up in the code/models.

I'm not sure if it sees my normal indexes either, haven't tested that yet.

**Comment by ErikEJ** [comment]
EF6 scaffolding/reverse engineer has no knowledge of indexes

**Comment by dannyboyng** [comment]
Is this impossible to implement? If so, I will close this issue.

**Comment by ErikEJ** [comment]
Nothing is impossible, but it is not going to happen
