### ISSUE TITLE
We sometimes expose PK values in exception messages

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#21]
Some exceptions contain information about Entity Key value. This may be a security concern, if the key is not surrogate. We should consider not exposing those values via exception messages

comments

maumar wrote Jul 24, 2015 at 3:46 PM [x] 

Examples of messages that reveal PK values:

 Materializer_RecyclingEntity - "All objects in the EntitySet '{0}' must have unique primary keys. However, an instance of type '{1}' and an instance of type '{2}' both have the same primary key value, '{3}'. "

 Materializer_AddedEntityAlreadyExists - "An object with a key value '{0}' already exists in an added state. An object in this state cannot be merged."

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2784

**Comment by mafshin** [comment]
@rowanmiller Wouldn't it be better to make it optional for developer to switch it off or on?

I usually use this PK values to identity what went wrong in my code. Removing them completely would make some debugging scenarios much harder.

**Comment by ajcvickers** [comment]
@mafshin Yes, that would be better, but that is a bigger feature than is covered by this issue. There are many places where it would be useful to have identifying information, so if a mechanism to allow this to be switched on and off is created, then many messages and the code that uses them should be updated. You might want to file another issue for this.
