### ISSUE TITLE
Why does IDbSet<T> does not define async methods from DbSet<T>?

### ISSUE THREAD

**Issue by mstaessen** [aspnet/EntityFramework6#210]
Regarding to IDbSet<T> , the [EF documentation](https://msdn.microsoft.com/en-us/library/jj592675(v=vs.113).aspx#Anchor_1) states the following: 

> "This context works in exactly the same way as the context that uses the DbSet class for its set properties."

That is far from true if you use the async methods on DbSet<T>, which aren't defined in IDbSet<T>. Why exactly doesn't IDbSet<T> define the async methods? Should it?

From a SOLID perspective, and in particular the last letter of the acronym, it would be more logical to define sets using IDbSet, but that would deny you access to the async features.

**Comment by ajcvickers** [comment]
@mstaessen See https://entityframework.codeplex.com/wikipage?title=Design%20Meeting%20Notes%20-%20May%2016%2c%202013

**Comment by mstaessen** [comment]
Thanks for the pointer. Hadn't found it.

The documentation though could be more explicit about the preference if DbSet over IDbSet. Does the old EF documentation take pull requests?

**Comment by ajcvickers** [comment]
@mstaessen We take pull requests for the inline XML documentation on the classes. Not sure about the other docs. @rowanmiller?

**Comment by rowanmiller** [comment]
@mstaessen Our current docs on testing don't show IDbSet (https://msdn.microsoft.com/en-us/library/dn314429(v=vs.113).aspx and https://msdn.microsoft.com/en-us/library/dn314431(v=vs.113).aspx). Was there another doc that you thought should be updated? As Arthur mentioned, you can send a PR for the API documentation, as it is maintained inline in the code.

**Comment by mstaessen** [comment]
I think this doc https://msdn.microsoft.com/en-us/library/jj592675(v=vs.113).aspx#Anchor_1 might need an update. It states  

> There a situations, such as when creating mocks or fakes, where it is more useful to declare your set properties using an interface. In such cases the IDbSet interface can be used in place of DbSet. [...] This context works in exactly the same way as the context that uses the DbSet class for its set properties.

but that would not be true if your code uses the async functions already.

**Comment by rowanmiller** [comment]
@mstaessen agreed, I opened https://github.com/aspnet/EntityFramework.Docs/issues/360 to track this
