### ISSUE TITLE
context does not update after querying the database

### ISSUE THREAD

**Issue by tschmit** [aspnet/EntityFramework6#215]
the followinf code outputs
A
A
B

when expected 
A
B
B

    using System;
    using System.Data.Entity;
    using System.Data.SqlClient;
    using System.Linq;

    namespace bugEF {
        class Program {
            public static string cs = @"server=.\SQL130EXP01;database=efbug;trusted_connection=yes";
            static void Main(string[] args) {
                using (BugCtx ctx = new bugEF.BugCtx()) {
                    ctx.Values.Add(new IdValue { Value = "A" });
                    ctx.SaveChanges();
                }

                using (SqlConnection conn = new SqlConnection(cs)) {

                    using (BugCtx ctx = new bugEF.BugCtx()) {
                        IdValue v = ctx.Values.Where(x => x.Id == 1).First();
                        Console.WriteLine(v.Value);

                        SqlCommand com = new SqlCommand("update IdValues set Value = 'B' where Id = 1", conn);
                        conn.Open();
                        com.ExecuteNonQuery();
                        conn.Close();

                        v = ctx.Values.Where(x => x.Id == 1).First();
                        Console.WriteLine(v.Value);

                    }
                }

                using (BugCtx ctx = new bugEF.BugCtx()) {
                    IdValue v = ctx.Values.Where(x => x.Id == 1).First();
                    Console.WriteLine(v.Value);
                }
            }
        }

        public class BugCtx : DbContext {
            public DbSet<IdValue> Values { get; set; }

           public BugCtx() : base(Program.cs) {
                Database.SetInitializer<BugCtx>(new DropCreateDatabaseAlways<BugCtx>());
            }
        }

        public class IdValue {
            public int Id { get; set; }
            public string Value { get; set; }
        }
    }

the sql trace is:

![image](https://cloud.githubusercontent.com/assets/3993568/23768497/8a5f75b0-050c-11e7-92cb-359d8206848b.png)

so you can see the queries sequence.
The context queries the database after the ADO query but... it does not update the entity

I have the same behavior if I use SSMS to update de db between the two context queries.

vs 2015
entity framework 6.1.3
windows 10 and windows 7

**Comment by ajcvickers** [comment]
@tschmit The context uses an "identity map" such that entity instances that are already being tracked are always returned from a tracking query. This ensures any modified values in the entity are preserved. There are ways to update entities with the values from the database, but this needs to be done explicitly. For example, `context.Entry(myEntity).Reload();`. You can also do a no-tracking query (Use `.AsNoTracking()`) if you always want the latest values from the database and are not concerned with changing property values on the client.

**Comment by tschmit** [comment]
ok, but why issuing the query to the db in this case ?

**Comment by ajcvickers** [comment]
@tschmit In general, to know which entities are returned from a query it must be executed on the server.

**Comment by tschmit** [comment]
Yes, I realize it after asking the question. Thank you for your work and time.
