### ISSUE TITLE
After installing VS2017, VS2015 New Connection button broken

### ISSUE THREAD

**Issue by WardDurossette** [aspnet/EntityFramework6#217]
![img_0232](https://cloud.githubusercontent.com/assets/19767604/23865174/cb749110-07e2-11e7-852c-3a4b95af09ac.JPG)
 
Note: Bug is durable, surviving multiple restarts of VS and a reboot of machine.

Steps to reproduce:
1. Start VS2015->File->New->Project->Console App
2. Create a new folder "Models" in the project
3. Right-click->Add New Item->Data->ADO.NET Entity Data Model
4. Code First from Database->Next->New Connection...
5. Error dialog is displayed.

Repeating the same steps in VS2017 does not generate the error dialog.

**Comment by ErikEJ** [comment]
@WardDurossette I am not able to repro - You could have a sick/bad connection lingering in Server Explorer - go to Server Explorer in VS 2015 - try to follow the guide here to clear them: http://hestia.typepad.com/flatlander/2010/08/fixing-the-server-explorer-the-given-key-was-not-present-in-the-dictionary-error.html

**Comment by ajcvickers** [comment]
@WardDurossette Could you send a report of this through `Help > Send Feedback > Report a Problem...` in Visual Studio? This will capture information about your configuration that may make it easier to debug why this happens on your system but not others.
