### ISSUE TITLE
enhancement request: add interception context metadata so interceptors can tell if a query is a lazy load

### ISSUE THREAD

**Issue by jamesmanning** [aspnet/EntityFramework6#219]
This may be PEBCAK on my part, but in looking through the RelatedEnd.DeferredLoad code path and existing contents of the interception context during a ReaderExecuting, I couldn't find anything that surfaced whether the query was happening in the context of a lazy load or not.  I ended up looking at the stack during the call to determine whether it was a lazy load (and what property of what entity if so), but that feels pretty fragile, especially in terms of trying to potentially have something work in EFCore in the future.

Here's what it's doing now FWIW:

https://github.com/jamesmanning/EntityFramework.LazyLoadLoggingInterceptor/blob/d88f068334b09e25f978c3256b8168110dfb0b0a/EntityFramework.LazyLoadLoggingInterceptor/LazyLoadLoggingInterceptor.cs#L118-L142

In trying to modify this to support EF6 and EFCore (or potentially make an EFCore alternate version), I'm not sure how to reliably detect lazy load context, though.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This is a reasonable suggestion, but it is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
