### ISSUE TITLE
Creating an instance of context slows down over time

### ISSUE THREAD

**Issue by lemkepf** [aspnet/EntityFramework6#224]
We noticed that some very small webservice calls were taking much longer than we expected. We did some investigation and put some timers in place and we narrowed it down to creating an instance of our Entity Framework DbContext. Not the query itself, just the creation of the context. I've since put some logging to see on average how long it actually takes to create an instance of our DbContext and it's quite surprising. Here is a graph of the average time it takes to create DbContext in milliseconds: 
![image](https://cloud.githubusercontent.com/assets/976010/24108297/3539cad4-0d5b-11e7-9f3d-83a5cae3e91c.png)

Something we also noticed is that it's not slow from the get-go. Context creation seems to slow down over time. Within the first couple minutes it goes from 2-4ms to 20+ms, then over the next couple hours it will creep up to the 50-80ms range and level off. The spike in this graph was me doing a deploy which recycled the app-domain. 
![image](https://cloud.githubusercontent.com/assets/976010/24108951/35dc0450-0d5d-11e7-8070-33597ad809a2.png)

Our context is a fairly large code-first context with around 400 entities - including some pretty complex relationships between some of the entities. We are running EF 6.1.3. We are doing a "one context per request", but for most of our web api calls it's only doing one or two queries. To create a context taking 60+ms, and then execute a 1ms query is a bit off. 

We realize that having a large context is not the most ideal solution, and we are working to reduce unused entities, or break it into multiple smaller context's. We don't really care about how much memory we use - we just care about the speed. 

I did take a memory dump to try and flesh out what's going on and here is the heap stats: 
![image](https://cloud.githubusercontent.com/assets/976010/24108620/24ce93c2-0d5c-11e7-9e7f-59e8ec591750.png)
That seems like quite a bit of metadata and typeusage. What can we investigate further? I understand the cache used by EF is extensive to speed things up. Does more things in the cache, slow down the context creation? Is there a way to see exactly what's in that cache to flesh out any weird things in there? Does anyone know what specifically we can do to speed up context creation? 

Thanks!

**Comment by ErikEJ** [comment]
Make you DbContext smaller - other tips here: https://msdn.microsoft.com/en-us/data/hh949853.aspx

**Comment by lemkepf** [comment]
Thanks @ErikEJ - I have looked through that doc extensively. I guess I want to know "why" does it take longer over time. Large context's are bad - but even with our large context it only takes 2-4ms on a fresh appdomain to create it. Over time that timing increases a lot.

**Comment by ajcvickers** [comment]
@lemkepf Couple of questions to help us understand this more:
* Is the same model used for every context instance? (If EF is building your model for you, then check whether OnModelCreating is called once or multiple times.)
* Is the same connection string used for each context instance? If not, how many different connection strings are used?

**Comment by lemkepf** [comment]
@ajcvickers Ask away!
1.  It's using the same model for every context instance. OnModelCreating is only called once during our globals pre-warm up on startup. 
2. The same connection string is used for each context instance.

**Comment by ajcvickers** [comment]
@lemkepf Can you create a project or complete code listing that reproduces this issue so we can attempt to root cause what is happening?

**Comment by lemkepf** [comment]
@ajcvickers this is a huge enterprise app. I'll try and get a smaller reproducible project for you. I can get you a memory dump quicker. Would that work?

**Comment by ajcvickers** [comment]
@lemkepf Possibly. :-)

**Comment by lemkepf** [comment]
@ajcvickers  - shoot me an email: plemke at acculynx.com and i'll sent you a link to a memory dump. I'm also working on creating a small project too that recreates it.

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you do an initial investigation? I can send you the memory dump.

**Comment by AndriySvyryd** [comment]
@ajcvickers Yes

**Comment by FrancoisBeaune** [comment]
Hi, any followup on this? We're observing a strikingly similar set of symptoms and have been struggling for a few days now. Any details on what was ultimately the problem is appreciated!

**Comment by FrancoisBeaune** [comment]
Just to let know what our issue was:

We were adding a new Entity Framework DB interceptor (`IDbCommandInterceptor`) _on every DB context creation_... Leading to thousands and thousands of interceptors after some time, slowing down not only context creation but also queries, after some time _by several orders of magnitude_...
