### ISSUE TITLE
Ensure EF6 Tools continue to work SxS with different releases of VS2017

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#225]
The 15.0 release of VS (VS2017) is already out. At some stage there will be a 15.1 release. This issue is so we do the requisite SxS testing to ensure we continue to work.

In particular EF6 tools utilizes a Singleton MSI to place the EF packages that NuGet uses for its local cache and to insert the registry key which points to that cache. We may need to investigate with the NuGet team to allow multiple caches and multiple registry keys, one for each installed version of VS.

Note for investigator: see email from Eric Knox re "Side-by-side expectations with Dev15 Preview".

**Comment by lajones** [comment]
Blocked awaiting input from NuGet on how they search for the registry key we install.

**Comment by divega** [comment]
We don't believe we have anything else to do here. This MSI is a singleton by-design. Now that the reference counting is correct it should be fine.
