### ISSUE TITLE
Is this SO post an issue with EF6?

### ISSUE THREAD

**Issue by AnilCAE** [aspnet/EntityFramework6#226]
http://stackoverflow.com/questions/16954429/entity-framework-6-code-first-one-way-many-to-many-via-annotations

**Comment by ajcvickers** [comment]
@AnilCAE Are you asking if there is a way to create a unidirectional many-to-many association with only data annotations? If so, then I think the answer is no; instead the fluent API should be used, as suggested in the answer to that question on StackOverflow.
