### ISSUE TITLE
EF 6.1.3 Crashing IIS Express with ASP.Net Core MVC

### ISSUE THREAD

**Issue by adam8797** [aspnet/EntityFramework6#237]
I (and a few other users) have been experiencing a problem when using EF 6.1.3 and IIS Express. For some reason, sites will crash very inconsistently. Some times, it works, other times it does not.

For the sake of not being redundant, I'll link to a StackOverflow question I put up on the subject, where I go into more detail. Other users are commenting that they have the exact same problem.

https://stackoverflow.com/questions/42772599

**Comment by ajcvickers** [comment]
@Eilon This is a FatalExecutionEngineError when running ASP.NET Core on .NET Framework with EF6 in IIS. It seems unlikely to be an actual EF6 issue. What would be the best place/contact to direct this kind of issue?

**Comment by Eilon** [comment]
Perhaps https://github.com/dotnet/coreclr is a good place to start?

**Comment by adam8797** [comment]
I'll post an issue to them, and see if they have any ideas, I'll link it back here for the sake of continuity.
