### ISSUE TITLE
Tools: Singleton MSI needs reference counting 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#245]
The singleton MSI used to put the runtime NuGet packages on disk in Dev15 doesn’t seem to have the reference counting mechanism enabled. 

If you install Dev15 RTW and Dev15.1 on the same machine and remove one of these, the MSI will likely get removed and you’d have to repair VS.

This is part or related to #225.

**Comment by ajcvickers** [comment]
This is an EF6 tools for Dev15 issue.

**Comment by lajones** [comment]
Fix checked into release-6.2.0-beta1 and master branches of EFBuild with commit acc2cf51.
