### ISSUE TITLE
Changing connection for a different database, same data

### ISSUE THREAD

**Issue by bass3l** [aspnet/EntityFramework6#246]
Hi, I'm trying to use EF with multiple DBs (all Oracle), I change the connection string but I get the data from the first DB I connect to, here is a code sample to demonstrate what I'm doing:
```c#
 public ActionResult MyAction(){

         OracleConnection firstConn = new ... // first db connection
         TestContext firstContext = new TestContext(firstConn , true);

         firstContext.MyModel.FirstOrDefault(); 

         OracleConnection secondConn = new ... // second db conneciton
         TestContext secondContext = new TestContext(secondConn, true);

         secondContext.MyModel.FirstOrDefault(); // getting the same data as of first context

         ...
    }
```
I tried using `IDbModelCacheKeyProvider` in the `TestContext` and set a different cache key for every context which connects to a different schema but with no luck, and I tried setting a HistoryContext with different schema names, but also with no luck, is the problem with the `EDMMetadataContext` being cached or something?

appreciate your help :)

**Comment by ajcvickers** [comment]
@bass3l There's nothing obvious in what you posted. Can you provide a more complete code listing or project that reproduces the issue?

**Comment by ajcvickers** [comment]
@bass3l You could also try looking at the logs, using DbContext.Database.Log.

**Comment by bass3l** [comment]
Yes thanks, I did that earlier, I was able to fix the problem using the `modelBuilder.HasDefaultSchema`, and EF was able to cache the models appropriately.
