### ISSUE TITLE
Improve Debugability of EntityFramework for Developers by providing more precise / meaningful errors (Entity Names along with the PropertyName)

### ISSUE THREAD

**Issue by Torgrimm** [aspnet/EntityFramework6#25]
Hello
Again, I had to search for several days for the root cause of an illegal state within my entity set, just because of an imprecise error message. Even worse, there is no way to download the pdb files (as far as i could discover).

Finally I was able to find the root cause by building EF for myself, to be able to debug into it.

For example:

`throw new InvalidOperationException(Strings.ObjectStateEntry_CannotModifyKeyProperty(memberName));
`
would be much more meaningful written as:

`throw new InvalidOperationException(Strings.ObjectStateEntry_CannotModifyKeyProperty(entityName, memberName));`

**Comment by divega** [comment]
@Torgrimm would you be willing to send a PR to improve this so that we can evaluate it?

**Comment by divega** [comment]
**Triage:** We are not planning to make changes in this area in EF6. If there is enough customer intereset and a contributor is interested in sending a PR we may consider it.
