### ISSUE TITLE
Two remaining PRs in CodePlex

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#276]
When we did the whole move to GitHub we left two PRs unreview in CodePlex: 

- [Comparison Null Semantics](http://entityframework.codeplex.com/SourceControl/network/forks/BrandonDahler/EntityFramework/contribution/7893)
- [TruncateTime performance enhancement](http://entityframework.codeplex.com/SourceControl/network/forks/BrandonDahler/EntityFramework/contribution/7750)  

For each of them we should decide whether these should be ported so that we can take them in 6.3.

cc @maumar @ajcvickers @brandondahler

**Comment by ajcvickers** [comment]
@maumar to move these to GitHub and provide some feedback if needed.
