### ISSUE TITLE
AspNetCore.Identity

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework6#277]
I'm unable to find the EntityFramework6 Identity repo on GitHub, could you please include a link in the main wiki?
Many users have implemented EF6 solutions for AspNetCore.Identity so Google doesn't find the original one anymore.

For many users using AspNetCore, EFCore isn't sufficient yet (for me: lack of `ComplexType`s and TPT), in the other hand, AspNetCore.Identity provides agnostic `IUserStore`, `IRoleStore` etc.
I'd like to see an official implementation of these interfaces (from AspCore) provided for EF6 users.

**Comment by ErikEJ** [comment]
There is no official support, see https://github.com/aspnet/Identity/issues/416

**Comment by weitzhandler** [comment]
I see. Sucks.
There are a gazillion of repos. You never know which of them is reliable. Why can't they come up with an official one?? This mess is annoying. Thanks for your link tho.

**Comment by ErikEJ** [comment]
@weitzhandler I guess it is a matter of resources and priority

**Comment by weitzhandler** [comment]
They should at least recommend one officially. It's a total mess, and since it's a mess, and I didn't want to pollute my lib, I came up with [this](https://gist.github.com/weitzhandler/9f5871e82d201f45bbcd3d3ab29bafc8) tiny wrapper.
Would love to hear your comments.
