### ISSUE TITLE
Nuget package is not available for EntityFramework.SQLserver

### ISSUE THREAD

**Issue by grimley517** [aspnet/EntityFramework6#279]
https://www.nuget.org/packages?q=EntityFramework.SqlServer 

Hi there

The nuget package is not available on nuget .org.  Is there another repository I should be using?

**Comment by ErikEJ** [comment]
The EF6 package for SQL Server is https://www.nuget.org/packages/EntityFramework/ - there is no seperate .SqlServer package

**Comment by grimley517** [comment]
Thanks. 

Did I dream it, or didn't there used to be one?

Regards

Brian

**Comment by ErikEJ** [comment]
Maybe during the EF Core preview/beta, yes

**Comment by CmdrBeavis** [comment]
> Thanks. Did I dream it, or didn't there used to be one? Regards Brian
> […](#)
> On 17 May 2017, at 17:48, Arthur Vickers ***@***.***> wrote: Closed #279. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah there was, I have it in one of my existing projects, so of course I thought I needed it in this new one, but, saw the answer and am going to assume I don't. 🤷‍♂
