### ISSUE TITLE
Moving Pull Requests from Codeplex

### ISSUE THREAD

**Issue by brandondahler** [aspnet/EntityFramework6#28]
I am the author of 6 of the 11 pull requests on CodePlex (https://entityframework.codeplex.com/sourcecontrol/list/contributions), would it be helpful for me to move those over myself to ensure the proper alerts are registered to come to me as necessary?

Brandon

**Comment by divega** [comment]
@brandondahler Thanks! We have assigned the PRs on the CodePlex repo to team members for review, so you may want to wait a bit until you get some feedback, but if you want to go ahead and resubmit them here and close them there that works too.

**Comment by brandondahler** [comment]
No problem :).
