### ISSUE TITLE
Dynamically change/update DefaultConnectionFactory and ProviderServices entity framework code first at runtime [EF6]

### ISSUE THREAD

**Issue by narendrasinghrathore** [aspnet/EntityFramework6#280]
Hi EF Team, please help on this issue.
@rowanmiller, @ajcvickers ,@maumar, @AndriySvyryd, @lajones, @bricelam, @lukewaters, @shanselman  
I have to change **default connection factory runtime** using **code first** EF6.x
**Here is the code I tried, but it runs only on app startup though it doesn't change the default provider i.e System.Data.SqlClient**

```C#
        public class ModelCodeFistConfig:DbConfiguration{

        public  #ModelCodeFistConfig(){

         //this.SetDefaultConnectionFactory(new System.Data.Entity.Infrastructure.SqlConnectionFactory());

        SetDefaultConnectionFactory(new MySql.Data.Entity.MySqlConnectionFactory());

        //SetProviderServices(System.Data.Entity.SqlServer.SqlProviderServices.ProviderInvariantName, System.Data.Entity.SqlServer.SqlProviderServices.Instance);

        SetProviderServices(MySql.Data.Entity.MySqlProviderInvariantName.ProviderName, new MySql.Data.MySqlClient.MySqlProviderServices());
        }
        public partial class ModelCodeFist : DbContext{
        public ModelCodeFist(string connection)
        : base(connection)
        {   }
        }
```

Web config.

```xml
        <entityFramework         codeConfigurationType="EFMultiDBSupport.ModelCodeFistConfig,EFMultiDBSupport" >
        <defaultConnectionFactory type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6"/>
        <!--<parameters>
        <parameter value="mssqllocaldb" />
        </parameters>
        </defaultConnectionFactory>-->
        <providers>
        <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d"></provider></providers>`
```

**Getting error:**

> Failed to set Database.DefaultConnectionFactory to an instance of the 'MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6' type as specified in the application configuration. See inner exception for details.

**Inner exception**

> Thread was being aborted.

**1. How i suppose to update the default connection factory to mysql/oracle/mssql(default) at runtime EF6 code first.**

**2. Is there a way to update connecting string( which we get from web.config ) for dbContext as param [ CODE  @FIRST ]see sample code below** 

```C#
    public DbContext alterConnectionString (string connectionString){

        DbContext db = new  DbContext("name=connectionStringNameInWebConfig");

        var getConnectionString = db.ConnectionString ; //getting a connection string

         db.ConnectionString = updateConnectionString // set a connection string

         return  db;
    }
```

Thanks!

**Comment by ajcvickers** [comment]
@narendrasinghrathore Configuration in the config file overrides code-based configuration. Options that come to mind:
* Change the applications config file...
* If you can't do that, then create the DbConnection directly in code and pass it to the DbContext. You could use the EF connection factory to do this, or you could use DbProviderFactory/Factories, or you could just new up a DbConnection object of the correct type.

**Comment by narendrasinghrathore** [comment]
Thanks for replying.
 I find solution and will soon create a repo on github, maybe will help someone in need.

**Comment by manojnetsmartz** [comment]
@narendrasinghrathore , I do have similar technical problem as your. Can you please suggest what solution you applied or please provide the github repo path.

**Comment by narendrasinghrathore** [comment]
@manojnetsmartz https://github.com/narendrasinghrathore/entityMultipleDb
Here you can find code and make sure you include dll for database providers for.eg MySql you have to download and include .dll in project.

**Comment by narendrasinghrathore** [comment]
@manojnetsmartz 
![image](https://user-images.githubusercontent.com/4208015/36591341-b5218b48-18b7-11e8-8038-d005b7321ab1.png)
