### ISSUE TITLE
Visual Studio 2017 Package Manager Console Does not read app.config correctly for migrations

### ISSUE THREAD

**Issue by rufio620** [aspnet/EntityFramework6#286]
I am running into an issue where I cannot run migrations from the visual studio package manager console. For some reason it cannot find my connection string entries in the dbmirations project app.config. This leads me to believe it is not reading the app.config correctly or reading it from the wrong location.

Executing the following command
update-database -ConnectionStringName "AdminDataContext" -ConfigurationTypeName "DbMigrations.SqlServer.Configuration"

Fails with No connection string named 'SqlServer' could be found in the application config file.

The correct project is selected in the Default project dropdown at the top of the pane and the migration project contains a app.config with the specified connection string "SqlServer".

**Comment by ajcvickers** [comment]
@rufio620 Check that the Startup project is set correctly in Visual Studio, or you can specify it on the command line. This is the project from which config will be read.

**Comment by rufio620** [comment]
Ahh just realized that. I guess previously I had multiple startup projects so it used the default project setting. Thanks for pointing that out.

**Comment by tlk** [comment]
Perhaps it could reveal the file path to the app.config being used/expected in this scenario, e.g.
``
No connection string named 'FooDbContext' could be found in the application config file 'C:\Foo\bar\app.config'
``

Also, is it necessary to dump a stack trace along with the System.InvalidOperationException? It makes the tool look like it is still in beta and the noise confuses people.
