### ISSUE TITLE
Applying migrations to upgrade from EF5 to 6.1.2 fails for SqlCE (CodePlex work items 2807, 2659)

### ISSUE THREAD

**Issue by JesperTreetop** [aspnet/EntityFramework6#29]
This is the same bug as [work item 2807](http://entityframework.codeplex.com/workitem/2807) on CodePlex.

Recapitulation:

Per [work item 2659](https://entityframework.codeplex.com/workitem/2659):

> The exception System.Data.SqlServerCe.SqlCeException (0x80004005): The foreign key constraint does not exist. [ PK___MigrationHistory ] 
> is thrown when attempting a migration of a SqlCE database created in EF5 to EF6.1.2. 
> 
> This problem is related to workitem 2523. The fix introduced for this workitem appears flawed. 
> 
> I have a SQLCE database created in EF5 and its __MigrationHistory table uses a primary key constraint name of PK_db0.__MigrationHistory. 
> When migrating the database to EF6.1.2 the update-database command updates the __MigrationHistory table using the SQL statements: 
> 
> ALTER TABLE [__MigrationHistory] ADD [ContextKey] nvarchar NOT NULL DEFAULT 'My.Database.Migrations.Configuration' 
> GO 
> 
> ALTER TABLE [__MigrationHistory] DROP CONSTRAINT [PK___MigrationHistory] 
> GO 
> 
> ALTER TABLE [__MigrationHistory] ALTER COLUMN [MigrationId] nvarchar NOT NULL 
> GO 
> 
> ALTER TABLE [__MigrationHistory] ADD CONSTRAINT [PK___MigrationHistory] PRIMARY KEY ([MigrationId], [ContextKey]) 
> GO 
> 
> The second SQL statement ALTER TABLE [__MigrationHistory] DROP CONSTRAINT [PK___MigrationHistory] 
> throws an exception as the constraint name should be PK_db0.__MigrationHistory. 
> 
> This is the CREATE script for the __MigrationHistory table from my SqlCE database as it was originally created using EF5: 
> 
> CREATE TABLE [__MigrationHistory]([MigrationId] nvarchar%28255%29 NOT NULL 
> , [Model] image NOT NULL 
> , [ProductVersion] nvarchar%2832%29 NOT NULL); 
> GO 
> ALTER TABLE [__MigrationHistory] ADD CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY ([MigrationId]); 
> GO 
> 
> My theory is that the SqlCE database can have a constraint name of either PK___MigrationHistory or PK_dbo.__MigrationHistory depending up which version of EF created the database, so the SQL statements for migrating the MigrationHistory to EF6.1.2 must be able to cope with either naming convention.

That work item was closed as avoidable: 

> I'm going to close this issue as it can be worked around by upgrading EF 5.0.0 => EF 6.0.0 => EF 6.1.2".

My work item pointed out that this did not fix every legitimate scenario:

> We ship a desktop application using EF and SQL CE and perform migrations programmatically as needed - we can't easily perform a disjointed upgrade (going from 5 to 6 to 6.1.2, migrating at each step) as the work item resolution suggests. It would be much more more helpful if the migration table code was updated to cover all historical scenarios. 
> 
> It looks like I'll have to stick with EF 5.0.0 until there are newer versions that can actually cleanly support upgrading.

and @rowanmiller commented with:

> **EF Team Triage**: Agreed - you should be able to go from 5 -> 6.x. Assigning to 6.2 to add logic to detect and support a v5 -> vCurrent upgrade.

I am reopening it here since the work item was closed instead of migrated and the bulk message noted that new issues could be opened. Is this still on the radar for any future release?

**Comment by divega** [comment]
**Triage: ** we agree it may not always be reasonable to upgrade the EF version in stages, so we will try to fix this.

**Comment by JesperTreetop** [comment]
That sounds great, thank you!

**Comment by bricelam** [comment]
> we agree it may not always be reasonable to upgrade the EF version in stages

I seem to remember seeing this issue reported in the past between different versions. I thought we decided it was by-design.

Should I check every version back to 4.3 (where Migrations was introduced)?

**Comment by JesperTreetop** [comment]
The close reason for the original work item sounds close enough to "not worth moving the design if everyone can trivially work around it", but I don't know if that's "by design" as such. Maybe there was another work item and another resolution, though - it seems unlikely that only me and the reporter of the original work item ever ran into this.

**Comment by ajcvickers** [comment]
@bricelam I think the idea was that we would make sure you could go from 5.0 to latest.

**Comment by rowanmiller** [comment]
I think @bricelam and myself are in agreement that this can be closed as "Won't Fix" at this stage. From my perspective this is largely a point in time thing. I think we should have fixed this earlier, but we didn't, and at this stage adoption of EF6 is high enough that I think a workaround for folks moving from 5 is acceptable. "Acceptable" being different from "ideal" - I think we should focus engineering effort on other items.

Clearing up for triage so that this can be discussed. If others feel strongly that this should be fixed, then I'm fine with us doing that.

**Comment by ErikEJ** [comment]
Only ever seen one customer raise this, so propose closing
