### ISSUE TITLE
EF 6.1.3 and Azure Security SqlInjection warning

### ISSUE THREAD

**Issue by jonnybee** [aspnet/EntityFramework6#307]
We are using EF 6.1.3 with a Code First model and we get a few Microsoft Azure SQL database security warnings concerning SqlInjection. I cannot get my head around how the Update SQL generated by EF can generate a SQL that is direct SQL like:

    update [table] set field = 'multi line value string' where [Id] = 123   

Which is what gets reported from the security tool. The common denominator is that is that value string contains an ' in the text.  When we run the code it generates parameter SQL and saves the values correctly like 

    update [table] set field = @p0 where [id] = @p1

When we check the database the fields contain the correct values. 
We do however use the SqlAzureExecutionStrategy in production but this warning still doesn't feel right. 

**Is this a real issue with EF or is this a false positive from the Microsoft Azure SQL database security?** 

We only use EF in our application to update these tables.

**Comment by ajcvickers** [comment]
We have no reason to believe that this is down to EF behavior. If this is still an issue. then can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
