### ISSUE TITLE
SqlCommand.Parameters having same variable declared twice

### ISSUE THREAD

**Issue by AlbertoMonteiro** [aspnet/EntityFramework6#31]
Hi, 

I am working in some interceptor for multi-tenant application and when I was doing  INSERT behavior, I found something strange.
Here is my code that change DbInsertCommandTree:

``` csharp
public class DbInsertCommandTreeHandler : CommandTreeHandlerBase
{
    private const string COLUMN_NAME = "TenantId";

    protected override bool CanHandle(DbCommandTree command)
    {
        return command is DbInsertCommandTree;
    }

    protected override DbCommandTree Handle(DbCommandTree command)
    {
        var insertCommandTree = command as DbInsertCommandTree;

        var dbSetClauses = insertCommandTree.SetClauses.Cast<DbSetClause>().ToList();

        var setClause = dbSetClauses.FirstOrDefault(HasColumn);
        if (setClause != null)
        {
            dbSetClauses.RemoveAll(HasColumn);
            dbSetClauses.Add(CreateSetClause(setClause));

            return new DbInsertCommandTree(insertCommandTree.MetadataWorkspace,
                insertCommandTree.DataSpace,
                insertCommandTree.Target,
                dbSetClauses.Cast<DbModificationClause>().ToList().AsReadOnly(),
                insertCommandTree.Returning);
        }
        return insertCommandTree;
    }

    private static DbSetClause CreateSetClause(DbSetClause expression)
    {
        var propertyExpression = expression.Property as DbPropertyExpression;
        return DbExpressionBuilder.SetClause(propertyExpression, propertyExpression.ResultType.Parameter("tenantId"));
    }

    private static bool HasColumn(DbSetClause setClause)
    {
        return (setClause.Property as DbPropertyExpression).Property.Name == COLUMN_NAME;
    }
}
```

When testing my code in test app, I received this exception:

```
The variable name '@tenantId' has already been declared. Variable names must be unique within a query batch or stored procedure.
```

So I added a breackpoint in my custom **IDbCommandInterceptor** in **ReaderExecuting** method. Then I saw that **DbCommand** had 10 parameters, first one was **tenantId** and last one **@tenantId**, I digged in my code to check were the first parameter came from. I didn't found it. The command tree generated from my DbInsertCommandTreeHandler produced this:

```
DbInsertCommandTree
|_Parameters
| |_tenantId : Edm.Int64
|_Target : 'target'
| |_Scan : CodeFirstDatabase.Contato
|_SetClauses
| |_DbSetClause
| | |_Property
| | | |_Var(target).Nome
| | |_Value
| |   |_'Alberto'
| |_DbSetClause
| | |_Property
| | | |_Var(target).Endereço_Rua
| | |_Value
| |   |_'Avenida F'
| |_DbSetClause
| | |_Property
| | | |_Var(target).Endereço_Bairro
| | |_Value
| |   |_'Benfica'
| |_DbSetClause
| | |_Property
| | | |_Var(target).Endereço_Complemento
| | |_Value
| |   |_null
| |_DbSetClause
| | |_Property
| | | |_Var(target).Endereço_Numero
| | |_Value
| |   |_1
| |_DbSetClause
| | |_Property
| | | |_Var(target).Endereço_Cep
| | |_Value
| |   |_0
| |_DbSetClause
| | |_Property
| | | |_Var(target).Telefone
| | |_Value
| |   |_'30211083'
| |_DbSetClause
| | |_Property
| | | |_Var(target).Celular
| | |_Value
| |   |_'86234779'
| |_DbSetClause
| | |_Property
| | | |_Var(target).Inativo
| | |_Value
| |   |_False
| |_DbSetClause
|   |_Property
|   | |_Var(target).TenantId
|   |_Value
|     |_@tenantId
|_Returning
  |_NewInstance : Record['Id'=Edm.Int64]
    |_Column : 'Id'
      |_Var(target).Id
```

So, I cloned EF repository and started to debug EF source code, and I realized that EF were adding the parameter **tenantId** twice.

In **System.Data.Entity.SqlServer.SqlGen.DmlSqlGenerator** at lines 248 ~ 267 EF create parameters from the **SetClauses**.

When code flow reach in **System.Data.Entity.SqlServer.SqlProviderServices** at lines 257 ~ 286 EF create SqlParameters from command tree parameters(**commandTree.Parameters**) and then add to **SqlCommand.Parameters**.

After that in lines 289 ~ 302 EF get parameters **generated from DmlSqlGenerator** and then add to SqlCommand.Parameters.

And then the **SqlCommand.Parameters** have parameter **tenantId** duplicated. One from **commandTree.Parameters** and another from **commandTree.SetClauses**.

I that behavior normal?

**Comment by AlbertoMonteiro** [comment]
@divega any feedback?

**Comment by divega** [comment]
@AlbertoMonteiro just to confirm, if you remove the interceptor, do you still see a failure?

**Comment by AlbertoMonteiro** [comment]
@divega no, it works properly

**Comment by AlbertoMonteiro** [comment]
@divega I created this repo with a project reproducing the issue.
https://github.com/AlbertoMonteiro/EFIssueSimulator

**Comment by AlbertoMonteiro** [comment]
@divega @rowanmiller any feedback?

**Comment by divega** [comment]
@AlbertoMonteiro thanks for putting together a repro. I haven't found any time to look into this so clearing up milestone so that we can design what to do with it in the next triage.

**Comment by AlbertoMonteiro** [comment]
@divega @rowanmiller I can try fix it and make a pull request, but I don't know where is the best place to put the unit test for this kind of issue involving a interceptor, can you tell me?

**Comment by divega** [comment]
If there is a bug in interception a test in test/EntityFramework/FunctionalTests/Interception/CommandTreeInterceptionTests.cs should be appropriate, but I am not sure that is the case.

**Comment by maumar** [comment]
@AlbertoMonteiro would the scenario work if DbInsertCommandTreeHandler.CreateSetClause you create a DbExpression representing constant with the proper value for the TenantId, rather than parameter (that you assign value later, in the MultiTenantInterceptor)? 

Something like:

```cs
        private static DbSetClause CreateSetClause(DbPropertyExpression propertyExpression)
            => DbExpressionBuilder.SetClause(
                propertyExpression,
                propertyExpression.ResultType.Constant(TenantId));
```

EF already parameterizes all constants in the DML statements as part of its SQL generation. 

We looked into enabling the scenario/approach you were trying, but EF has made a few assumptions around parameters in DML (i.e. we assume there would never be any created by the user). Fixing those assumptions requires changes in the providers, which makes it a non viable solution.

**Comment by maumar** [comment]
closing this as we believe we have found a reasonable workaround, please re-open if it doesn't work and we will re-evaluate and/or look for better workarounds.
