### ISSUE TITLE
Which version of Microsoft.EntityFrameworkCore.Tools.DotNet use with EntityFrameworkCore 2.0.0-preview2-final

### ISSUE THREAD

**Issue by AdrienTorris** [aspnet/EntityFramework6#313]
I have a project using ASP.NET Core version _2.0.0-preview2-final_ and Entity Framework Core _2.0.0-preview2-final_ and I don't find which version of `Microsoft.EntityFrameworkCore.Tools.DotNet` we have to use. 

I installed the version _2.0.0-preview2-final_ like it's says [in the announcement](https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-ef-core-2-0-preview-2/) but when I try to add a migration with the command `dotnet ef migrations add 201707101207_Initial -o Infrastructure/DbContextMigrations -c MyContext` I have the error : 

> dotnet: No executable found matching command "dotnet-ef"

Which version of `Microsoft.EntityFrameworkCore.Tools.DotNet` I have to use with Entity Framework Core _2.0.0-preview2-final_ ?

For information, this is my csproj:
```

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\DbContextMigrations\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>

</Project>

```

**Comment by AdrienTorris** [comment]
For information, I'm using Visual Studio Community 2017 Preview 2 version 15.3.0 Preview 3.0. And .NET Core 2.0 Preview 2 is installed.

**Comment by smitpatel** [comment]
If you are using `dotnet ef` inside `Package Manager Console` in Visual studio, you must cd into the directory containing csproj. By default PMC is rooted at solution folder. Consider using Powershell commands in Visual studio.

**Comment by divega** [comment]
@AdrienTorris also, for future reference, this repository is for EF version 6. I think you intended to create an issue for EF Core over at https://github.com/aspnet/EntityFramework/issues/.
