### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by JudeAlquiza** [aspnet/EntityFramework6#323]
Hi,

Just want to ask if there is a feature that supports nested transactions with entity framework ? like the one here in this stackoverflow thread
https://stackoverflow.com/questions/33728142/how-to-create-nested-transactions-in-entity-framework-using-transactionscope

Thanks!
Jude Alquiza.

**Comment by divega** [comment]
@JudeAlquiza in general EF (and EF Core) rely on the transactional capabilities or the underlying database system (note that `TransactionScope` is currently not supported in EF Core but the plan is to bring this feature back now that it exists in .NET Core and that will be supported in various relational database providers). 

Many commonly used databases do not have nested transaction capabilities. 

Also, note having nested `TransactionScope` instances does not necessarily imply code will be executed in nested transactions, e.g. if the database does not support nested transactions then only one transaction will be created.

**Comment by JudeAlquiza** [comment]
Hi @divega thank you so much for the reply :) my apologies for replying late
