### ISSUE TITLE
Correct license?

### ISSUE THREAD

**Issue by mirhagk** [aspnet/EntityFramework6#326]
The license on github says that this project is licensed under Apache, but the [nuget site](https://www.nuget.org/packages/EntityFramework) refers to a [different license](https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm) that is more restrictive.

Which is the appropriate license for this project?

**Comment by divega** [comment]
@mirhagk the source code is distributed under Apache 2.0 but the binaries are distributed under the Microsoft .NET Library license.
