### ISSUE TITLE
EdmxWriter.WriteEdmx Null Reference Exception when using DbCompiledModel in constructor

### ISSUE THREAD

**Issue by Cynicszm** [aspnet/EntityFramework6#327]
Hi,

We are getting an error when constructing a DbContext passing in a DbCompiledModel and trying to MigrateDatabaseToLatestVersion using Entity Framework 6.2 Beta 1

The DbCompiledModel is successfully retrieved from a DefaultDbModelStore via EdmxReader.Read(xmlReader, defaultSchema) then passed into the base constructor.

The Database Initializer is set to MigrateDatabaseToLatestVersion using the supplied context.

Database.Initialize(false) throws a Null Reference exception (Object reference not set to an instance of an object.), stack trace below.

Any help appreciated,
Thanks,
John

```
   at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer)
   at System.Data.Entity.Utilities.DbContextExtensions.<>c__DisplayClass1.<GetModel>b__0(XmlWriter w)
   at System.Data.Entity.Utilities.DbContextExtensions.GetModel(Action`1 writeXml)
   at System.Data.Entity.Utilities.DbContextExtensions.GetModel(DbContext context)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
```

**Comment by divega** [comment]
@Cynicszm thanks a lot for reporting this. 

Just to confirm, are you asserting that the same code was working correctly with EF 6.1.3 but is no longer working in EF 6.2 Beta 1?

If that is the case, there was actually a change that might have affected `EdmxWriter()` in 6.2 Beta 1: https://github.com/aspnet/EntityFramework6/commit/d03610af3b71732a29a5154261b65911e3b199c5. We can look into it but we would be very thankful if you can provide a repro.

**Comment by divega** [comment]
> Just to confirm, are you asserting that the same code was working correctly with EF 6.1.3 but is no longer working in EF 6.2 Beta 1?

@Cynicszm I realize after re-reading your bug report that you are actually using the feature that this changeset added. 

Still, a repro would be great.

**Comment by Cynicszm** [comment]
On holiday for the next week will look at a repro when I get back. Tracing it back, got as far as the failing line 67 
var builder = compiledModel.CachedModelBuilder.Clone();
CachedModelBuilder is null as the compiled model came about using the other constructor.

**Comment by Cynicszm** [comment]
Sorry for the delay. Please find attached. 

Using EdmxWriter.WriteEdmx in the parameterless constructor works fine. 

Using Database.Initialize or EdmxWriter.WriteEdmx  will fail as described above when a DbCompiledModel is passed into the second constructor.

[EFTestConsole.zip](https://github.com/aspnet/EntityFramework6/files/1245355/EFTestConsole.zip)

**Comment by ajcvickers** [comment]
The problem here is that the DbCompiledModel that is being used to create the context instance is not in the DbModelStore cache. This means that there is no way to look up the EDMX that it was created from and also there is no cached DbModelBuilder to build it from. Since Migrations relies on the EDMX to do diffs it cannot continue. 

For 6.2 we will generate a better exception. At present I don't have any good ideas for a better fix; it may be that using DbCompiledModel with Migrations will always require it to be in the model cache.
