### ISSUE TITLE
Mapping entity collections to IEnumerable instead of ICollection

### ISSUE THREAD

**Issue by explorer14** [aspnet/EntityFramework6#329]
Hi folks,

With EF Core I can expose a collection property of my domain entity as IEnumerable/IReadOnlyCollection and encapsulate the internal list from accidental changes to it that might risk breaking the consistency of my domain model.

Are there any plans to allow for similar flexibility in EF 6? I know there are workarounds for this but I would rather a mature infrastructure component such as EF 6 allow for that flexibility out of the box than me having to hack around it.

Thanks
Aman

**Comment by divega** [comment]
@explorer14 support for `IEnumerable<T>` collections navigation properties is indeed a new feature in EF Core. We don't have any plans to enable it in EF6.
