### ISSUE TITLE
Replace %VSnnnCOMNTOOLS% with $(DevEnvDir) in T4 templates

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#33]
In https://github.com/aspnet/EntityFramework6/commit/013d453bfe2476e0622aa310067d444ce8124470 I checked in a change to insert $(DevEnvDir) into the Dev15 version of various T4 template files, rather than the previous reference to %VS150COMNTOOLS%. This was because %VS150COMNTOOLS% no longer exists under the low-impact install.

This bug is to consider replacing %VS150COMNTOOLS% with $(DevEnvDir) for the builds for Devs 11, 12 & 14 as well.

**Comment by divega** [comment]
We should play it safe, e.g. test that things aren't broken. Possibly add logic to falls back to an envvar.

**Comment by lajones** [comment]
This was checked into release-6.1.3-tools-dev15-test with many changesets on 7/29/16
