### ISSUE TITLE
Instrument EF Tools wizard for usage data

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#332]
We would like to have more information about how much customers use each of the different options, e.g. code first from existing database, designer from new database, etc. to be able to make better decision on where we invest.

**Comment by divega** [comment]
@bricelam does this still need work before we close?

**Comment by bricelam** [comment]
It's not merged, and there was mention of possibly adding more details.

**Comment by divega** [comment]
Clearing up milestone to decide what to do in triage.

**Comment by ajcvickers** [comment]
@divega and @ajcvickers to decide what to do here.

**Comment by ajcvickers** [comment]
Closing this for now as the value to complete this is not high enough to trump any other work. We can also come back to it in the future.
