### ISSUE TITLE
Is it possible to use DbGeography in the docker container through mono?

### ISSUE THREAD

**Issue by pauloanalista** [aspnet/EntityFramework6#333]
Is there any possibility of running a .NET project that uses the entity framework using spatial data in a docker container through the mono?

**Comment by divega** [comment]
@pauloanalista I don't think this is possible, but I am not 100% sure. Entity Framework source code has been incorporated in the Mono distribution but I would expect the capabilities to vary depending on the target platform and database provider. 

In particular, `DbGeography` functionality depends on the EF database provider supplying extensive spatial type implementation, which in the case of our SQL Server provider relies on the underlying `SqlGeography` and `SqlGeometry` types from SQL Server and the support for them in SqlClient (SQL Server's ADO.NET provider). In turn, the implementation of `SqlGeometry` and `SqlGeograph` relies on native code, which tends to be platform specific. 

The piece that is less likely to exist in Mono is the implementation of the `SqlGeometry` and `SqlGeography` types themselves and the corresponding support for them in Mono's SQL Server ADO.NET provider.

I think if you want a more definitive answer it would be a good idea to re-ask this question in one of the [Mono mailing lists](http://www.mono-project.com/community/help/mailing-lists/) or in https://StackOverflow.com, where I am sure there are Mono experts that might know.
