### ISSUE TITLE
How to add UWP Project

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/EntityFramework6#338]
I am running on 6.0.0-preview2-25612-02 of Microsoft.NETCore.UniversalWindowsPlatform and try to add a EntityFramework SQLClient Package,.
no idea how to.

Message form Nuget is
Das Paket Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview1-26636 ist nicht mit uap10.0.16257 (UAP,Version=v10.0.16257) kompatibel. Paket Microsoft.EntityFrameworkCore.SqlServer 2.1.0-preview1-26636 unterstützt Folgendes: netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by ErikEJ** [comment]
You have to stay on version 1.1.2 for now (until a newer version of UWP comes later this year)

**Comment by hannespreishuber** [comment]
doenst compile with 1.1.2 several Errors with the .net base data types

**Comment by hannespreishuber** [comment]
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.0-preview2-25612-02</Version>
    </PackageReference>
  </ItemGroup>

**Comment by hannespreishuber** [comment]
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.0-preview2-25612-02</Version>
    </PackageReference>
  </ItemGroup>

**Comment by hannespreishuber** [comment]
`<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.0.0-preview2-25612-02</Version>
    </PackageReference>
  </ItemGroup>
  `

**Comment by smitpatel** [comment]
This issue was moved to aspnet/EntityFramework#9401
