### ISSUE TITLE
Synchronizationcontext with async calls

### ISSUE THREAD

**Issue by pmiddleton** [aspnet/EntityFramework6#344]
I have run into an interesting issue.

I have an async query which is part of a mvc 5 application.  The where clause of the query is performing an equity compare between a field on my entity and a custom property on a class which is abstracting away the asp.net session.

`.Where(c => c.NetworkId == SecurityManager.CurrentUser.CurrentNetworkId)`

When the query runs there is a high chance that HttpContext.Current is null.  I dug through the EF 6 code and see that DefaultSqlExecutionStrategy is calling ConfigureAwait(false) in ExecuteAsync.  This is causing the HttpContext to not be carried through to the continuation thread, therefore its up to dumb luck if I get the same thread on continuation or not.

I don't see a way to force EF 6 to pull the HttpContext through to the continuation.  Am I missing a setting I could be using?

At this point I think my only option is to capture my value into a temp variable outside of the Linq query.

**Comment by davidfowl** [comment]
> At this point I think my only option is to capture my value into a temp variable outside of the Linq query.

Yes

**Comment by pmiddleton** [comment]
Thanks for the answer, that is what I figured it would be.

From what I am reading I should have access to the context again in my code again after the EF call completes.  I don't have to worry about it going away for the rest of the request after the async call?

**Comment by davidfowl** [comment]
That's correct, the `ConfigureAwait` call would only affect the calls within EF itself, not calls outside of your code. It's an interesting questions whether or not the state should be restored when running the query (thats a tricky one).

/cc @divega
