### ISSUE TITLE
OLTP Support

### ISSUE THREAD

**Issue by kkocabiyik** [aspnet/EntityFramework6#350]
Is there anyway to support OLTP with EF 6.X just like EFCore?

**Comment by ajcvickers** [comment]
@kkocabiyik Can you be more specific about what you are asking for? EF6 supports both ADO.NET DbTransaction and System.Transactions.

**Comment by kkocabiyik** [comment]
Sorry for the late reply. The question was actually about adding fluent method something like .ForSqlServerIsMemoryOptimized() that is already added to EfCore.
