### ISSUE TITLE
Need a flag on runtime type DbProviderManifest to control whether the provider supports optimizing parameters in schema discovery queries

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#359]
In order to react to the conclusions of #195, we need to fork the behavior of the designer code that prepares schema discovery queries based on whether the provider supports collapsing parameters by value.

The idea is to:

1. Add a new virtual `bool` method on `DbProviderManifest`, `SupportsParameterOptimizationInSchemaQueries` (or any better name we can come up with), `false` by default.
2. Override it on the `SqlProviderManifest` to return `true`. 
3. Consider doing this also on `SqlCeProviderManifest`, depending on @ErikEJ's input.

**Comment by ErikEJ** [comment]
What should I do in order to verify this?

**Comment by divega** [comment]
@ErikEJ test Update Model From Database using the 6.2 beta1 version of the tools against the SQL CE provider.

**Comment by divega** [comment]
@ErikEJ In general if schema discovery with the SQL CE provider is only based on executing the Entity SQL queries generated by the tools against the schema discovery model it should be safe. 

Providers like Oracle have problems because they don't execute some of the queries and instead use pattern matching to detect them and call into other code passing the parameters.

**Comment by ErikEJ** [comment]
You can flip the switch for the SQLCE provider!

**Comment by ajcvickers** [comment]
Thanks @ErikEJ. I merged with the bit flipped for CE, so it should get the optimization once it is implemented in the tooling.
