### ISSUE TITLE
Crash When using proxies when debugger shows variable values.

### ISSUE THREAD

**Issue by bgurmendi** [aspnet/EntityFramework6#364]
How to reproduce:
     On Linux OS (Ubuntu 16.04)
     With Mono 3.0 to 5.2.0.224
     Open attached project. (With MonoDevelop or Rider) [Debugger_SIGSEGV_2.zip](https://github.com/aspnet/EntityFramework6/files/1320493/Debugger_SIGSEGV_2.zip)
     Start debugger session.
     When the execution stops do one of this actions:

- On 'Immediate' console: write 'entity'.
- View Locals pad.
- Watch entity variable.

Most likely the crash is due to Mono Runtime. But I dont have any response from Mono developer on this issue: https://bugzilla.xamarin.com/show_bug.cgi?id=57133

**Comment by bgurmendi** [comment]
This is the crash report [crash_report.txt](https://github.com/aspnet/EntityFramework6/files/1320507/crash_report.txt)

**Comment by ajcvickers** [comment]
@bgurmendi This is not something where we plan to update EF6 code unless there is something that is really a bug in the EF6 code. For that we would need more details, but as of now closing as external since it seems like something that needs to be fixed on the Mono side.
