### ISSUE TITLE
Using MapKey in addition with property

### ISSUE THREAD

**Issue by bdebaere** [aspnet/EntityFramework6#369]
I am currently working on a business project with extremely little control over the database structure. The database has the following tables: Item, VendorItemItem. Item is a simple entity table and VendorItemItem is a table linking Item and VendorItem together.

These two tables link to eachother, but not by traditional means. The foreign key in VendorItemItem does not link to the primary key of Item. Instead it links to another foreign key in Item.

Item
Id
OtherId

VendorItemItem
ItemOtherId
VendorItemId

This means I would like to use MapKey to accomplish this relationship with code first. However, MapKey apparently requires that the property is not used. Is there a way around this so I can still have the foreign key as a property in my Item object? Other applications will depend on this property and will not be able to insert records into VendorItemItem if it is not available.

Thank you for your time!

**Comment by ajcvickers** [comment]
@bdebaere This is a limitation in EF6 that is, unfortunately, not ever likely to get removed. Sometimes it can be worked around by changing which property EF thinks is the PK--for example try mapping OtherId as the PK.

EF Core supports this kind of relationship, but may not be suitable for other reasons.

**Comment by bdebaere** [comment]
@ajcvickers Thank you for your response. I cannot use this OtherId as PK because other tables are linked with the Id unfortunately.
MapToStoredProcedures and Entity splitting (hopefully with optional relationships) is not yet supported in EF Core as far as I know so we cannot switch yet.

If there is no possible workaround, then I thank you for your time.
