### ISSUE TITLE
Improve Performance of Package Load

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#37]
This is to track the internal push to improve package load times. @divega has more details - in particular an email titled "Deferred Project and Package Load".

**Comment by lajones** [comment]
Fix checked into release-6.1.3-tools-dev15-test branch with commits bdcf253, 0d4c527, 9b7a2ac & 82aa8bc.

**Comment by lajones** [comment]
The above changes were included into VS (RC.2) as of Nov 23, 2016.

**Comment by divega** [comment]
Closing as duplicate of #247 since the work didn't finished with this issue being closed.
