### ISSUE TITLE
EF doesn't recognize IDENTITY attribute with tinyint data type

### ISSUE THREAD

**Issue by JohnyL** [aspnet/EntityFramework6#370]
I'm using EF 6.2.0 Beta 1. Say, I have a simple entity:
```
CREATE TABLE Operator
(
    Id tinyint IDENTITY NOT NULL PRIMARY KEY,
    [Name] varchar(1000) NOT NULL
);
```
The entity is:
```
[Table("Operator")]
public class Operator
{
    public byte Id { get; set; }
    public string Name { get; set; }
}
```
When I try to create a new entry and save it
```
var @operator = new Operator { Name = "OperatorName" };
context.Operators.Add(@operator);
db.SaveChanges();
```
then I receive the following error:
```
SqlException: Cannot insert explicit value for identity column in table 'Operator' when IDENTITY_INSERT is set to OFF.
```
EF issues the following SQL:
```
exec sp_executesql N'INSERT [dbo].[Operator]([Id], [Name])
VALUES (@0, @1)
',N'@0 tinyint,@1 nvarchar(max) ',@0=0,@1=N'Operator1'
```

And here's the trick: as soon as I change the data type of Id column from **tinyint** to **smallint** and higher (and **byte** to **short** in class), then all is OK - the record is successfully saved. The issued SQL:
```
exec sp_executesql N'INSERT [dbo].[Operator]([Name])
VALUES (@0)
SELECT [Id]
FROM [dbo].[Operator]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()',N'@0 nvarchar(max) ',@0=N'Operator1'
```
Nowhere in [documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property) I found the limitation by type that can be used with IDENTITY property.

**Comment by ajcvickers** [comment]
@JohnyL Have you tried explicitly configuring it to be an identity column? For example,

```C#
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public byte Id { get; set; }
```

**Comment by JohnyL** [comment]
**@ajcvickers** Yes, thanks, that worked! But I didn't expect DatabaseGeneratedOption.Identity to be set explicitly since EF treats primary fields to be IDENTITY.

**Comment by ajcvickers** [comment]
EF6 makes int, short, long, properties Identity by convention, but not byte. I don't have a clear recollection of why this is, but I expect it is because byte is a very small key space.
