### ISSUE TITLE
New compile-time dependency added in Visual Studio 2017 15.3.x breaks current tools build

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#372]
We are hitting the issue described in https://developercommunity.visualstudio.com/content/problem/94821/vs-153-undocumented-breaking-changes.html

In summary, the we need a new dependency when building the designer with newer versions of VS 2017:

``` XML
    <Reference Include="Microsoft.VisualStudio.Shell.Interop.15.3.DesignTime, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
``` 

Without it you get:

> "Cannot find the interop type that matches the embedded interop type 'Microsoft.VisualStudio.Shell.Interop.IVsToolboxItemProvider2'. Are you missing an assembly reference?"

Working on solving this by adding it to EFToolsVsReferences.settings.targets, conditional on VisualStudioVersion = 15.0. This means we will require 15.3.x at least to build.

**Comment by ajcvickers** [comment]
Triage: We will continue to hack our way through deving (using VS 2013) and @bricelam will investigate getting a proper VS build done for 2017 using C.I. setup on unicorns420.
