### ISSUE TITLE
How to specify initial size and growth factor when creating database?

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFramework6#373]
I use an initializer that derives from DropCreateDatabaseAlways.  Is it possible to specify the initial size and growth factor of the database when it is created?

Thanks

**Comment by ajcvickers** [comment]
@sam-wheat There isn't any built-in way to do this. You could try implementing your own initializer based on DropCreateDatabaseAlways but with custom ADO.NET/SqlClient calls to do the actual database creation part.
