### ISSUE TITLE
SaveChanges takes a lot of time due to expensive looping in method MetadataHelper.GetAssociationsForEntitySet(EntitySetBase entitySetKey)

### ISSUE THREAD

**Issue by ravi-pathak** [aspnet/EntityFramework6#375]
This issue was discussed [earlier in 2012](https://social.msdn.microsoft.com/Forums/en-US/d642aa86-7a0e-4f84-9ed1-13e0b53f65a8/potential-performance-issue-in-systemdataobjectsentitystateentryacceptchanges?forum=adodotnetentityframework) on MSDN forums but it didn't go anywhere. We now have a genuine need to fix this problem as described here:

### Entity Model:
Order - root entity
OrderItem - 1-M child of Order

Order and OrderItem have a few FK associations with other master entities such as Customer and Product.

### Scenario:
We are creating a new Order and many OrderItems (~600,000) within a single instance of DbContext and calling SaveChanges in the end.

We found that DbContext.SaveChanges was taking a lot of time, so we decided to run our application with dotTrace Profiler, which reported following method as a hot-spot taking almost 70% time:

**System.Data.Common.Utils.MetadataHelper.GetAssociationsForEntitySet(EntitySetBase)**

DBContext Settings:
1. Configuration.AutoDetectChangesEnabled = false;
2. Configuration.ValidateOnSaveEnabled = false;

**Potential Solution:**
We made a small change to this method to avoid looping and use a dictionary instead to lookup for associations. 

`        private static readonly ConcurrentDictionary<EntitySetBase, List<AssociationSet>> _associationSetsForEntitySet = new ConcurrentDictionary<EntitySetBase, List<AssociationSet>>();
`

Then fixed the method to use the dictionary as follows:

        // requires: entitySet
        // effects: Returns the associations that occur between entitySet
        // and other entitySets. If none is found, returns an empty set
        internal static List<AssociationSet> GetAssociationsForEntitySet(EntitySetBase entitySetKey)
        {
            DebugCheck.NotNull(entitySetKey);

            return _associationSetsForEntitySet.GetOrAdd(
                entitySetKey, entitySet =>
                {
                    var result = new List<AssociationSet>();

                    foreach (var extent in entitySet.EntityContainer.BaseEntitySets)
                    {
                        if (Helper.IsRelationshipSet(extent))
                        {
                            var assocSet = (AssociationSet)extent;
                            if (IsExtentAtSomeRelationshipEnd(assocSet, entitySet))
                            {
                                result.Add(assocSet);
                            }
                        }
                    }
                    return result;
                });
        }

The performance **indeed improved significantly** as seen in the attached profiler snapshots:
![snapshots of getassociationsforentityset before and after optimization](https://user-images.githubusercontent.com/12440800/31534257-cd45a0cc-b013-11e7-8b3b-f4e19a098499.PNG)

**Comment by ajcvickers** [comment]
@ravi-pathak This looks like a great improvement. Would you consider submitting a pull request for this change? https://github.com/aspnet/EntityFramework6/wiki/Contributing

**Comment by ravi-pathak** [comment]
@ajcvickers I will submit a pull request soon. Thanks for your comment.

**Comment by IanYates** [comment]
Great to see EF6 can still get PRs accepted.  This looks like a great change for me too - I have nothing on the order of that number of changes in a single commit but sometimes could have 1000-2000 rows  (stocktake entries, etc) so I could see this still being a benefit.

**Comment by ravi-pathak** [comment]
@ajcvickers While looking at the latest code from master, I realized that caching of AssociationSets at EntitySet level is already in place and thus there is no need for me to create a pull request for this issue. 

Please this commit:

https://github.com/aspnet/EntityFramework6/commit/bc42e4985da66f020dd8f428c8600ed8bfacb770 

Since we are using the stable release 6.1.3 in production, we worked off the corresponding code branch (tagged 6.1.3) and optimized **just the method** that was reported as a hot-spot. I'll try my scenario with 6.2-beta1 and post the outcome here.

Any idea when we can expect EF 6.2?

**Comment by ajcvickers** [comment]
@ravi-pathak Thanks for finding that. We plan to release EF6.2 soon--we have been having some infrastructure issues that has delayed a number of things, but as of the end of last week we seem to be past them, so we're going to try to get this out soon now.
