### ISSUE TITLE
EF table names

### ISSUE THREAD

**Issue by JHeLiu** [aspnet/EntityFramework6#386]
Hi, I would like to ask a question, EF does it support the sub-form? Such as different table names.

**Comment by ajcvickers** [comment]
@JHeLiu Can you please explain in more detail what you mean?

**Comment by JHeLiu** [comment]
@ajcvickers 
Yes,
Is such a, for example, I put the database sub-table design, but its structure is exactly the same, in fact, in the traditional T-SQL string access to the database, is very easy, I only need to set the table on the dynamic settings, such as:
```
 var tableName = "Table_1";
 var sql = $"SELECT * FROM {tableName}";
```
1, Table_1 Table_2 Table_3, I can dynamically change the table name. But in EF I do not know how to change, I searched the information, but unfortunately, did not find.

2, EF first start will be a bit slow, so there is a better way to solve it?

3, I would like to close the EF generated additional query, I now turn off the additional T-SQL generated, but there will be a` select cast (serverproperty ('EngineEdition') as int)` database version of the query, oh, I do not want Want it. I just want me to execute what statement it is in the database to query what. So what is the way to get rid of it?

So please help me

**Comment by ajcvickers** [comment]
@JHeLiu We're having a little difficultly following exactly what you are asking for, but to try to answer your questions:
1. It's not clear how this relates to an ORM, but you can use the SqlQuery method if you really need to dynamically create queries like this.
2. It depends, but some things to look at are [pre-generated views](https://msdn.microsoft.com/en-us/library/dn469601(v=vs.113).aspx), [n-gen](https://msdn.microsoft.com/en-us/library/dn582034(v=vs.113).aspx), [model caching](https://github.com/aspnet/EntityFramework6/issues/275) and the [EF perf whitepaper](https://msdn.microsoft.com/en-us/library/hh949853(v=vs.113).aspx)
3. This is part of normal EF initialization when building a model.

**Comment by JHeLiu** [comment]
@ajcvickers Thank you for your answer O(∩_∩)O
