### ISSUE TITLE
EF Tools Update Model issue when provider reports nullable keys SEEMS NOT SOLVED in 6.2

### ISSUE THREAD

**Issue by stephanebo21** [aspnet/EntityFramework6#388]
Hi,
I posted an issue #243 ,normally planned to be integrated in the 6.2 release. But I encounter today the same problem.
I created a new class library project (Target framework 4.6) on Visual Studio 2015 Update 3, and use the new package nugget Entity Framework 6.2. 
![capture1](https://user-images.githubusercontent.com/23525106/32166251-8688a864-bd65-11e7-887d-d2d13e7a6bee.png)
![capture2](https://user-images.githubusercontent.com/23525106/32166265-8f03f958-bd65-11e7-8ff4-c93ed3736e4b.PNG)

I added in my config file this line (without it, it doesn't work):
![capture4](https://user-images.githubusercontent.com/23525106/32166393-f894c47e-bd65-11e7-9c4d-b1f8b2dd9b90.PNG)

  Then I created a new Entity Data Model (EF Designer from Database) and tried to add my view. I wasn't able to add my view in the model and receive this error:
Error 13101: Key part '----' for type '-----' is not valid. All parts of hte key must be non-nullable.
![capture3](https://user-images.githubusercontent.com/23525106/32166277-9a5543d4-bd65-11e7-9386-69c6ef711818.PNG)

Have I missed something ?
Thanks for your help.

Stephane

**Comment by ajcvickers** [comment]
@stephanebo21 This is an issue with VS tooling rather than the EF runtime. We haven't yet released an updated version of the tooling.

(@divega - we should move tooling issues out of 6.2; let's discuss when you are back.)

**Comment by divega** [comment]
@ajcvickers I created the tools-6.2.0 milestone and I have updated a couple of links to reflect the change.
