### ISSUE TITLE
Database first - ability to override default type mapping

### ISSUE THREAD

**Issue by Misiu** [aspnet/EntityFramework6#39]
i have simple table in MS SQL containing 2 columns:
ClientId - binary(8) primary key 
ClientName - varchar(30)

When I add that table to my model I can see that `ClientId` type = `Binary`

![snap 2016-07-29 at 09 26 38](https://cloud.githubusercontent.com/assets/1741838/17473686/14a9fdf2-5d52-11e6-8a0e-6495a0bf7d9d.png)

What I would like to do is to override that type so that inside C# code I will be able to use int instead of byte[].

`SELECT * FROM Clients WHERE ClientId = 0x0000000000000001` and `SELECT * FROM Clients WHERE ClientId = 1` are giving me same results so why not allow to specify target mapping.

This would only require simple CAST inside SQL and just for select operation, all other work fine.

I'm aware I can use stored procedures for select and updates or even use SQL view. But sometimes for very simple applications this would be big convenience.

It's easier to say `client with Id = 4067` than `client with Id =0x0000000000000FE3`

Can this be done?

I've posted same issue in [EF7 issue tracker](https://github.com/aspnet/EntityFramework/issues/6263). Currently I'm using EF 6.1.3 so I'd like to have this working it that version, but at some point I'll be moving to EF Core so I'd also like that feature working there.

**Comment by divega** [comment]
**EF Team Triage:** We are not planning to make changes in this area in EF6. If there is enough customer interest and a contributor is interested in sending a PR we may consider it.
