### ISSUE TITLE
Highly inefficient SQL code generated for inline data

### ISSUE THREAD

**Issue by logiclrd** [aspnet/EntityFramework6#392]
When a query requires that the results of another query be used in a way that cannot be directly expressed with a join, Entity Framework generates a virtual table of the results from the first query within the text of the second query. This is an example of what that virtual table looks like:

    SELECT 
        [Extent1].[ColumnName1] AS [ColumnName1], 
        [Extent1].[ColumnName2] AS [ColumnName2], 
        ...
    FROM  [dbo].[Table1] AS [Extent1]
    INNER JOIN  (SELECT 
        cast('11f56e2a-7bf1-41bd-9c5e-00620561ebbc' as uniqueidentifier) AS [C1]
        FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
    UNION ALL
        SELECT 
        cast('cfaf2c6f-1a11-4ef3-b7cb-01dc00c1dd86' as uniqueidentifier) AS [C1]
        FROM  ( SELECT 1 AS X ) AS [SingleRowTable2]
    UNION ALL
        SELECT 
        cast('df712b04-a1cc-4f5c-b1d2-02542b173b57' as uniqueidentifier) AS [C1]
        FROM  ( SELECT 1 AS X ) AS [SingleRowTable3]
    UNION ALL
        SELECT 
        cast('414219e0-8167-437d-8792-026a2711c595' as uniqueidentifier) AS [C1]
        FROM  ( SELECT 1 AS X ) AS [SingleRowTable4]
    UNION ALL
        SELECT 
        cast('54110019-087a-4520-1e94-02761118e3d6' as uniqueidentifier) AS [C1]
        FROM  ( SELECT 1 AS X ) AS [SingleRowTable5]
    UNION ALL
        ...

This syntax is extremely verbose, producing very large queries that waste a great many characters for the data being included (especially if that data is of a concise type such as `INT`).

This could be expressed in the following way, using Table Value Constructors:

    SELECT 
        [Extent1].[ColumnName1] AS [ColumnName1], 
        [Extent1].[ColumnName2] AS [ColumnName2], 
        ...
    FROM  [dbo].[Table1] AS [Extent1]
    INNER JOIN (VALUES
        (cast('11f56e2a-7bf1-41bd-9c5e-00620561ebbc' as uniqueidentifier)),
        (cast('cfaf2c6f-1a11-4ef3-b7cb-01dc00c1dd86' as uniqueidentifier)),
        (cast('df712b04-a1cc-4f5c-b1d2-02542b173b57' as uniqueidentifier)),
        (cast('414219e0-8167-437d-8792-026a2711c595' as uniqueidentifier)),
        (cast('54110019-087a-4520-1e94-02761118e3d6' as uniqueidentifier)),
        ...
        (cast('606bf1e5-f2b1-4428-815d-039121e28f13' as uniqueidentifier)) AS [InlineDataTable1] ([C1])
    ...

Even if this feature is not available in the SQL Server version being used (I believe they were introduced in SQL Server 2008, 10 years ago now), the `SELECT` and `UNION ALL` syntax can be substantially abbreviated by completely omitting the `FROM` clause:

    SELECT 
        [Extent1].[ColumnName1] AS [ColumnName1], 
        [Extent1].[ColumnName2] AS [ColumnName2], 
        ...
    FROM  [dbo].[Table1] AS [Extent1]
    INNER JOIN (SELECT cast('11f56e2a-7bf1-41bd-9c5e-00620561ebbc' as uniqueidentifier) AS [C1]
      UNION ALL SELECT cast('cfaf2c6f-1a11-4ef3-b7cb-01dc00c1dd86' as uniqueidentifier) AS [C1]
      UNION ALL SELECT cast('df712b04-a1cc-4f5c-b1d2-02542b173b57' as uniqueidentifier) AS [C1]
      UNION ALL SELECT cast('414219e0-8167-437d-8792-026a2711c595' as uniqueidentifier) AS [C1]
      UNION ALL SELECT cast('54110019-087a-4520-1e94-02761118e3d6' as uniqueidentifier) AS [C1]
        ...

This change has the potential to significantly reduce the raw quantity of query data that needs to be passed to the server for certain types of queries, and though I have not tested it, I imagine it might have a small impact on performance as well.

**Comment by ajcvickers** [comment]
@logiclrd Can you post an example of the LINQ query that results in this kind of SQL generation?

**Comment by logiclrd** [comment]
Sure.

I have an `IQueryable<ActivationKeys> activationKeys` that is derived from calling the `SqlQuery` method on `DbSet<ActivationKeys>`, and I have an `IQueryable<ActivationKeySecrets>` that is actually in this case the `DbSet<ActivationKeySecrets>` itself.

The query can be constructed in either of these ways (I believe they are equivalent under the hood):

	var results = activationKeySecrets.Join(
		activationKeys.Select(key => key.ActivationKeyID),
		keySecret => keySecret.ActivationKeyID,
		activationKeyID => activationKeyID,
		(keySecret, key) => keySecret);

...or:

	var results =
		from keySecret in activationKeySecrets
		join activationKeyID in activationKeys.Select(key => key.ActivationKeyID)
		on keySecret.ActivationKeyID equals activationKeyID
		select keySecret;

In this scenario, because the `activationKeys` query isn't based on an expression tree (and possibly for other reasons, I am not an expert!), Entity Framework doesn't have a way to combine the queries into a single, cohesive `JOIN` in the database, so instead, it runs the `activationKeys` query, extracts its results, and then encodes the results themselves verbatim into the query it generates for the `join`. (I found that I had to extract the `ActivationKeyID` property from the elements of `activationKeys` prior to the `join`, otherwise Entity Framework wanted to serialize the entire `ActivationKey` objects into the query as scalars, which it couldn't do because it is not a scalar/primitive type.)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
