### ISSUE TITLE
The entity type {typename} is not part of the model for the current context.

### ISSUE THREAD

**Issue by ocdi** [aspnet/EntityFramework6#396]
I have just upgraded to EF6.2 and enabled the new model caching feature. My app has multiple EF DbContexts in the same application. Since deploying the build with these upgrades I have been getting the above exception. The only thing that is fixing it is removing the .edmx files and restarting the app pool.

It seems that when the app pool is recycled and the cache is used, that it is getting this error. I've kept a diff of the generated files and there are zero differences.

I'll do some investigation today but if anyone else has had this or has some pointers to what might be causing it, that would be great.

**Comment by ajcvickers** [comment]
@ocdi Can you post some code showing how you are using the model caching?

**Comment by ocdi** [comment]
@ajcvickers I think I have worked out what is going on. There is a DbContext that doesn't have the explicit DbConfigurationType attribute assigned. I know from previous experience that you can have a single configuration class per solution. It seems that the context without this attribute is the one that was having the entity type issue. Does that sound right?

**Comment by ajcvickers** [comment]
@ocdi Hard to say without doing more investigation. Certainly if you have more than one DbConfiguration in the same app-domain, then that is likely to cause issues.

**Comment by ocdi** [comment]
@ajcvickers Thanks, there is only a single DbConfiguration in the app domain, however it appears to use that configuration on all DbContexts regardless of whether the attribute is on there or not. The contexts are in separate assemblies pulled in by our ASP.NET MVC app for different plugin functionality. This had been working fine until I enabled the context model store on the DbConfiguration class. I can clearly see the .edmx xml file being stored for the context without this attribute but for some reason it is not getting the correct model definition when being used. If this behaviour is intended then it might be worth making a note that all contexts will require the DbConfigurationType attribute on it.

**Comment by ajcvickers** [comment]
@ocdi DbConfiguration is global (app-domain) wide configuration, so there is only ever one being used. One way to ensure that this is the one you want is to use the DbConfigurationType attribute. I'll look into the docs to see if they should be updated to make this clearer.
