### ISSUE TITLE
Using DefaultDbModelStore throws exception

### ISSUE THREAD

**Issue by srudin** [aspnet/EntityFramework6#404]
I posted this here before: https://github.com/aspnet/EntityFramework6/issues/275
But this issue is closed already and maybe I should create a seperate issue anyway so here we go.

The new feature from 6.2 "Reduce start up time by loading finished code first models from a persistent cache" is not working for me.

What I did is very simple and I think exactly the way it's supposed to be done:

I saved the model using
EdmxWriter.WriteEdmx(context, writer);

In my DbConfiguration implementation I set
SetModelStore(new DbModelStore());

DbModelStore is my implementation of DefaultDbModelStore where I simply overwrite GetFilePath().

When making the first call to EntitySet I get
InvalidOperationException: The entity type EdmMetadata is not part of the model for the current context.
System.Data.Entity.Internal.InternalContext.UpdateEntitySetMappingsForType(Type entityType) +273
System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +31
System.Data.Entity.Internal.Linq.InternalSet1.Initialize() +77 System.Data.Entity.Internal.Linq.InternalSet1.AsNoTracking() +29
System.Data.Entity.Infrastructure.DbQuery1.AsNoTracking() +75 System.Data.Entity.Internal.EdmMetadataRepository.QueryForModelHash(Func2 createContext) +159
System.Data.Entity.Internal.ModelCompatibilityChecker.CompatibleWithModel(InternalContext internalContext, ModelHashCalculator modelHashCalculator, Boolean throwIfNoMetadata, DatabaseExistenceState existenceState) +120
System.Data.Entity.Internal.InternalContext.CompatibleWithModel(Boolean throwIfNoMetadata, DatabaseExistenceState existenceState) +77
System.Data.Entity.CreateDatabaseIfNotExists1.InitializeDatabase(TContext context) +155 System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action) +71 System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization() +482 System.Data.Entity.Internal.RetryAction1.PerformAction(TInput input) +174
System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action1 action) +273 System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +20 System.Data.Entity.Internal.Linq.InternalSet1.Initialize() +77
System.Data.Entity.Internal.Linq.InternalSet1.AsNoTracking() +29 System.Data.Entity.Infrastructure.DbQuery1.AsNoTracking() +75
[my call to EntitySet]

I have been able to get it to work when I create a DbCompiledModel instead:
var model = EdmxReader.Read(reader, "dbo");

I can then pass the model to the constructor of the context. However this is much more complicated mostly because of the stupid null check of the model in the constructor (!) so I have to make sure to call the right constructor overload depending on whether I already have a saved model or not.

A fix for the null check or even better an explanation why the DefaultDbModelStore is not working would be appreciated. At the moment I consider both to be bugs.

**Comment by ajcvickers** [comment]
@srudin I don't believe that the feature is intended to be used in that way. You should not need to read/write EDMX files manually. Instead you should just need to configure the model store using something like this:
```C#
public class MyDbConfiguration : DbConfiguration
{
    public MyDbConfiguration() : base()
    {
        this.SetModelStore(new DefaultDbModelStore(Directory.GetCurrentDirectory())); 
    }
}
```
(Taken from https://blogs.msdn.microsoft.com/dotnet/2017/05/23/announcing-ef-6-2-beta-1/)

**Comment by srudin** [comment]
Hm yes, your are right. Using it like this works. However I don't understand the difference between this and my solution which is basically nothing else but a different file path. The generated files are binary identical.

I was using it this way because I followed this blog post: https://www.fusonic.net/en/blog/ef-cache-deployment/
