### ISSUE TITLE
Wiki - Building the Runtime broken link

### ISSUE THREAD

**Issue by brandondahler** [aspnet/EntityFramework6#406]
The Sql Server Compact 3.5 link on https://github.com/aspnet/EntityFramework6/wiki/Building-the-Runtime no longer works.  It should be updated to https://www.microsoft.com/en-us/download/details.aspx?id=5783.

**Comment by ErikEJ** [comment]
The link already points to that url !?

**Comment by ajcvickers** [comment]
Looks like this was an issue with the download site that has now been fixed.
