### ISSUE TITLE
No git tag created for 6.2.0

### ISSUE THREAD

**Issue by brandondahler** [aspnet/EntityFramework6#408]
It appears that there is a release-6.2.0 branch, but there isn't git tag created for the 6.2.0 release yet.  Presumably it would be created to point at 1ebb961115f07aaaffafd131310a0e1ac7aaaf6f.

**Comment by Seabizkit** [comment]
anyone looking into this, its like the project has been abandoned, which is weird as i know thousands of people are actively using EF6.
