### ISSUE TITLE
Consider making DbModelStore registration provider specific

### ISSUE THREAD

**Issue by J-Hauser** [aspnet/EntityFramework6#413]
As the generated Edmx-File has provider-specific information it seems not consistent to use one DbModelStore for different Providers.  

Also it is different from the way IDbModelCacheKey is working and could break when used together. (Differnt cacheKey per Provider but same DbCompiledModel).  

Currently it is possible to save provider-specific Edmx-Files to provider-specific paths, but i can not find a way to supply the provider-informations to the TryLoad() and TryGetEdmx()-Methods of DbModelStore. 

Looking through LazyInternalContex.CreateModel() and EdmxWriter.WriteEdmx() the necessary information seem to be present via the Connection- or ModelProviderInfo-Properties of LazyInternalContext and could be passed to the DbModelStore from there.

This is not so much an issue for production (but could be, if one DbModelStore generated DbCompiledModel could be used against different database types. Not very common, i guess, perhaps some homegrown replication-tool or having different sub-DbContexts, pointing to different Databases, using the same DbCompiledModel via IDbModelCacheKey), but for integration tests, where one would like to test queries against different providers without having to create parallel structures and the need for a new  AppDomain per provider-specific test.

**Comment by ajcvickers** [comment]
@J-Hauser This does seem to be a limitation in the use of DbModelStore; we would certainly consider a PR to remove the limitation, but we don't plan on working on it in the EF team. @j-Edge, who submitted the PR that introduced this feature might also be interested in submitting a new PR. We will re-open the issue if a PR is submitted.
