### ISSUE TITLE
Unique multi column indexes is not created correctly

### ISSUE THREAD

**Issue by vikbo** [aspnet/EntityFramework6#416]
If I only have one unique multi column index defined in the EntityTypeConfiguration class for a table the index is created correctly.

In the configuration class:
```C#
this.Property(t => t.fk_Person)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 0 }));
this.Property(t => t.Typ)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 1 }));
```
In the generated migration class:
```C#
.Index(t => new { t.fk_Person, t.Typ }, unique: true, name: "_WM_UC_PersonAdress_PersonAndTyp")
```
When I after that added one more index to this class and generated a new migration this happens.

In the configuration class:
```C#
this.Property(t => t.fk_Person)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 0 }));
this.Property(t => t.Typ)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 1 }));

this.Property(t => t.fk_Person)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndAdressrad1")  { IsUnique = true, Order = 0 }));
this.Property(t => t.Adressrad1)
  .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndAdressrad1")  { IsUnique = true, Order = 1 }));
```
In the generated migration class:
```C#
DropIndex("dbo.PersonAdress", "_WM_UC_PersonAdress_PersonAndTyp");
CreateIndex("dbo.PersonAdress", new[] { "fk_Person", "Adressrad1" }, unique: true);
CreateIndex("dbo.PersonAdress", "Typ", unique: true, name: "_WM_UC_PersonAdress_PersonAndTyp");
```
Error 1: The allready existing unique index "_WM_UC_PersonAdress_PersonAndTyp" should remain unchanged, but it is dropped and replaced with a new unique index with the same name but it now only includes the field "Typ". The "fk_Person" is lost.

Error 2: The name of the new index "_WM_UC_PersonAdress_PersonAndAdressrad1" is lost.

Observe: Almost the same error happened when I added two indexes in a similar way, in another table that did not previosly have any indexes. Error 2 did not happen then (possibly I remember wrong) but Error 1 did.

Out of curriosity I tested the new index syntax in EF 6.2, for the new index, to see if that solves it or makes any difference.

In the configuration class:
```C#
this.Property(t => t.fk_Person)
                .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 0 }));
this.Property(t => t.Typ)
                .HasColumnAnnotation(IndexAnnotation.AnnotationName, new IndexAnnotation(new IndexAttribute("_WM_UC_PersonAdress_PersonAndTyp")  { IsUnique = true, Order = 1 }));

this.HasIndex(p => new { p.fk_Person, p.Adressrad1 }).IsUnique();
```

In the generated migration class:
```C#
DropIndex("dbo.PersonAdress", "_WM_UC_PersonAdress_PersonAndTyp");
CreateIndex("dbo.PersonAdress", new[] { "fk_Person", "Adressrad1" }, unique: true);
CreateIndex("dbo.PersonAdress", "Typ", unique: true, name: "_WM_UC_PersonAdress_PersonAndTyp");
```
So, exactly the same error happens, which seems rather logical.

Using the new EF 6.2 syntax for both indexes also result in the same error.

**Comment by ajcvickers** [comment]
@vikbo The index annotations cannot be used like that because each property is only allowed to have one annotation with a given name. See #56 for how to use the annotations for multiple indexes.
