### ISSUE TITLE
OData+EF on inherited back-navigations

### ISSUE THREAD

**Issue by raffaeler** [aspnet/EntityFramework6#42]
This is the same issue reported here: https://entityframework.codeplex.com/workitem/2903
and cross-posted here: https://github.com/OData/odata.net/issues/679

We have troubles using OData queries on a service based on EntityFramework. 
The problem arises when we try to expand inherited back-navigation properties. 
In attachment you can find a minimal example which reproduces the problem.

We have entities in the following hierarchy: 
Base-->Derived-->DerivedDerived-->DerivedDerivedDerived 
A back-navigation is declared on "Base" and queried on all four entity-types just to find that it only works on "Base" and "DerivedDerivedDerived" (i.e. only the least and most extended types).

The queries we tried are:
[...]/odata/Base?$expand=BackNav
[...]/odata/Derived?$expand=BackNav
[...]/odata/DerivedDerived?$expand=BackNav
[...]/odata/DerivedDerivedDerived?$expand=BackNav

Only cases 1 and 4 are working.

Cases 2 and 3 throw exception: 
{ "error":{ "code":"","message":"An error has occurred.","innererror":{ "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{ "message":"An error occurred while preparing the command definition. See the inner exception for details.","type":"System.Data.Entity.Core.EntityCommandCompilationException","stacktrace":" at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)\r\n at ...

[OdataTest.zip](https://github.com/aspnet/EntityFramework6/files/413266/OdataTest.zip)

**Comment by divega** [comment]
The external issue is now tracked at https://github.com/OData/WebApi/issues/792.

**Comment by divega** [comment]
**Triage:** we believe this is an external issue tracked in https://github.com/OData/WebApi/issues/792 and we won't track it as an EF issue.
