### ISSUE TITLE
Removing a child entity.

### ISSUE THREAD

**Issue by chrysikos** [aspnet/EntityFramework6#423]
When removing a child entity from a collection EF will leave it as orphan  removing just the foreign key.
I don't want to explicitly remove it using the DbContext. Is there a way to do that?

**Comment by ajcvickers** [comment]
@chrysikos You'll need to do something like override SaveChanges. I wrote a blog post on it a long time ago: https://blog.oneunicorn.com/2012/06/02/deleting-orphans-with-entity-framework/

**Comment by CADbloke** [comment]
you may also consider: https://stackoverflow.com/questions/502501/database-to-delete-or-not-to-delete-records Hope it helps.
