### ISSUE TITLE
The item with identity '' already exists in the metadata collection foreign key

### ISSUE THREAD

**Issue by padmanabanravikumar** [aspnet/EntityFramework6#427]
we have migrated our exiting entity framework edmx file based model generation to POCO based object model generation using EntityFramework Reverse POCO Generator.

Now we are getting error like The item with identity '' already exists in the metadata collection foreign key.

If we skip foreign keys in our model then in it works, but we can't to do so because its a huge project with more than 1000 tables are there. and we are using lazy load syntax and reverse foreign key navigation properties.

**Comment by padmanabanravikumar** [comment]
I have attached the sample files

[model.cs](https://github.com/aspnet/EntityFramework6/files/1559255/model.txt)
[database.sql](https://github.com/aspnet/EntityFramework6/files/1559266/database.txt)

The item with identity 'Student_Login' already exists in the metadata collection

Is there any way to resolve the problem?

**Comment by ajcvickers** [comment]
Note for triage: looks like a dupe (possible same root cause) as #308
