### ISSUE TITLE
Package manager prompt

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#434]
From VS Feedback:

Package manager prompt is not restored after sucessfully completing add-migration or update-database operation.

PM> update-database
infoinfo: 
Applying migration '20171216085326_IssueEditedBy'.
Done.

Closing the Package Manager Console does not help as it is greyed out on the View -> Other Windows list.

Have to restart Visual Studio to get the functionality back.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by GrahamBonzoWright** [comment]
After running add-migration the prompt does not return.
This is because an instance of the dotnet process is still running.
Killing this process using Task Manager completes the action in Visual Studio and the prompt is restored and I can continue to work without restarting Visual Studio.
The dotnet process is also left running after update-database  from the VS package manager console.

I am using MariaDb and the Pomelo.EntityFrameworkCore.MySql NuGet package in a EF Core / AspNet Core 2 solution.

**Comment by ajcvickers** [comment]
@GrahamBonzoWright Can you please provide a full project/solution that reproduces what you are seeing?

**Comment by GrahamBonzoWright** [comment]
[IssueTracker.zip](https://github.com/aspnet/EntityFramework6/files/1616116/IssueTracker.zip)

**Comment by GrahamBonzoWright** [comment]
[IssueTracker.zip](https://github.com/aspnet/EntityFramework6/files/1616243/IssueTracker.zip)

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/EntityFrameworkCore/issues/10699 since this is an EF Core scenario.
