### ISSUE TITLE
Allow derived entities with inherited navigation properties to use same column for foreign key

### ISSUE THREAD

**Issue by justintconroy** [aspnet/EntityFramework6#443]
Using Table Per Hierarchy inheritance, if a base class has a navigation property to some other table, but that foreign table references the derived entities in its navigation properties, entity framework will require that there be separate columns for each derived entity's foreign keys to that other table. For example, if we have the following model:

```csharp
public class Foreign
{
    public int Id { get; set; }

    public virtual ICollection<Base> Bases { get; set; }
    public virtual ICollection<A> As { get; set; }
    public virtual ICollection<B> Bs { get; set; }
}

public abstract class Base
{
    public int Id { get; set; }
    public string MyProperty { get; set; }

    public int ForeignId { get; set; }
    public virtual Foreign Foreign { get; set; }
}

public class A : Base
{
}

public class B : Base
{
}
```

The table generated by migrations creates `Foreign_Id` and `Foreign_Id1` properties to act as the foreign key for `A` and `B` respectively. The desired behavior would be to allow both derived types to map the foreign key column to `Foreign_Id`.

Attempting to override the column name with a mapping is simply ignored and EF insists on using a different name than specified in the mapping (i.e. continuing to try to fetch the property from `Foreign_Id1` instead of the explicitly mapped column `Foreign_Id`).

**Comment by justintconroy** [comment]
A little bit of an update to this. I found a way to work around this, though it's still less than ideal, in my opinion.

At first, I tried to work with the multiple columns for "different" foreign keys. I found that I couldn't rename those columns in the database, so I was stuck with e.g., `Foreign_Id1` types of names, rather than being able to change them to something like `Foreign_IdA` or whatever. I considered this unacceptable, so I tried a few different things.

Ultimately, I removed the navigation properties `As` and `Bs` from `Foreign` and only have a `Bases` navigation property. Then, any time I wanted only one of the types, I would do `Foreign.Bases.OfType<A>`. This works, but it would still be much nicer if I could just setup my model to do `Foreign.As` instead. Even if it was just some sort of syntactic sugar coating over the `OfType` method.

**Comment by ajcvickers** [comment]
@justintconroy Sorry for the slow response. First, if there are relationships from both the base class and a derived class to the same principal, then they must use different FKs because the these are different relationships that could both be present on any instance. If the base class is abstract, meaning that there won't actually be an entities of this type, then one relationship could be considered a view over the other relationship, but this is not supported by EF mapping.

However, if there are no relationships referencing the base class explicitly, then the two derived classes can share the same navigation property and FK in the database. However, EF mapping is still limited to the properties being declared on the derived types. For example:
```C#
public class Foreign
{
    public int Id { get; set; }
    public virtual ICollection<A> As { get; set; }
    public virtual ICollection<B> Bs { get; set; }
}

public abstract class Base
{
    public int Id { get; set; }
    public string MyProperty { get; set; }
}

public class A : Base
{
    public int ForeignId { get; set; }
    public virtual Foreign Foreign { get; set; }
}

public class B : Base
{
    public int ForeignId { get; set; }
    public virtual Foreign Foreign { get; set; }
}

public class SizTwoContext : DbContext
{
    protected override void OnModelCreating(DbModelBuilder modelBuil
    {
        modelBuilder.Entity<A>()
            .Property(e => e.ForeignId)
            .HasColumnName(nameof(A.ForeignId));
        
        modelBuilder.Entity<B>()
            .Property(e => e.ForeignId)
            .HasColumnName(nameof(B.ForeignId));
    }

    public DbSet<Foreign> Foreigns { get; set; }
    public DbSet<A> As { get; set; }
    public DbSet<B> Bs { get; set; }
    public DbSet<Base> Bases { get; set; }
}

```
Maps to the following tables:

```sql
CREATE TABLE [dbo].[Bases] (
    [Id] [int] NOT NULL IDENTITY,
    [MyProperty] [nvarchar](max),
    [ForeignId] [int],
    [Discriminator] [nvarchar](128) NOT NULL,
    CONSTRAINT [PK_dbo.Bases] PRIMARY KEY ([Id])
)

CREATE TABLE [dbo].[Foreigns] (
    [Id] [int] NOT NULL IDENTITY,
    CONSTRAINT [PK_dbo.Foreigns] PRIMARY KEY ([Id])
)
```

**Comment by vertonghenb** [comment]
Can this be done without the use of the `ForeignKeyId` properties? Just the navigational ones?

**Comment by RamunasAdamonis** [comment]
Hi @ajcvickers I literally copied your example to new project template and by generating the migration I got following:

```
                    table.ForeignKey(
                        name: "FK_Bases_Foreigns_ForeignId",
                        column: x => x.ForeignId,
                        principalTable: "Foreigns",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Bases_Foreigns_ForeignId1",
                        column: x => x.ForeignId,
                        principalTable: "Foreigns",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
```

It still creates two foreign keys.

**Comment by RamunasAdamonis** [comment]
P.S. I am using EF core, so maybe I shouldn't expected the same behavior.
