### ISSUE TITLE
Blank T-SQL script for AlterTableAnnotations

### ISSUE THREAD

**Issue by mdoust** [aspnet/EntityFramework6#446]
- EntityFramework 6.1.3
- Microsoft SQL server express 2016

We are using [EntityFramework.DynamicFilters](https://github.com/zzzprojects/EntityFramework.DynamicFilters) library in a project of ours. After defining a filter and executing `AddMigration` command, a migration was created with following content in it's Up method:
```csharp
AlterTableAnnotations(
  "dbo.Accounts",
   c => new
     {
       Id = c.String(nullable: false, maxLength: 128),
       InternationalBankAccountNumber = c.String(maxLength: 34),
       PhoneNumber = c.String(nullable: false, maxLength: 16),
       ...
     },
   annotations: new Dictionary<string, AnnotationValues>
   {
     { 
       "DynamicFilter_Account_AccountsDefaultScope",
       new AnnotationValues(oldValue: null, newValue: "EntityFramework.DynamicFilters.DynamicFilterDefinition")
     },
   });
```
Next step for us was generating an SQL script to be executed on our production server. Hence `Update-Database -Script` command was executed but we got a blank SQL file (only an INSERT command for migration itself.) So my question is whether it's natural behavior for `AlterTableAnnotations` to be ignored here?

Even when we ran the Update-Database without -Script flag (but with -Verbose flag,) no corresponding SQL script was observed.

**Comment by ajcvickers** [comment]
@mdoust The annotation will not have any impact unless there is something reading it and acting on it. That would seem to be a question for the EntityFramework.DynamicFilters folks.
