### ISSUE TITLE
EF - A member of the type, 'X', does not have a corresponding column in the data reader with the same name.

### ISSUE THREAD

**Issue by antoniogarcez** [aspnet/EntityFramework6#455]
Hi,

I have a class that represents one of my tables (I used EntityFramework with Code-First):

```c#
    [Table("Logística$Sales Invoice Header")]
    public partial class Logística_Sales_Invoice_Header
    {
        [Column(TypeName = "timestamp")]
        [MaxLength(8)]
        [Timestamp]
        public byte[] timestamp { get; set; }

        [Key]
        [StringLength(20)]
        public string No_ { get; set; }

        [Column("Sell-to Customer No_")]
        [Required]
        [StringLength(20)]
        public string Sell_to_Customer_No_ { get; set; }
```

And when I am trying to pass a result of a query to an instance of this class, shows this error:

> The data reader is incompatible with the specified 'FAMO.BaseItems.Database.urano.famNAV.Logística_Sales_Invoice_Header'. A member of the type, 'Sell_to_Customer_No_', does not have a corresponding column in the data reader with the same name.

Query:
```sql
SELECT a.* FROM [Logística$Sales Invoice Header] AS a INNER JOIN [Logística$Sales Invoice Line] AS b ON a.No_ = b.[Document No_] WHERE 1 = 1 AND b.Type = 2 AND a.[Bill-to Customer No_] = 'IC00029' AND b.No_ = 'XFMR2812B' AND b.[Cross-Reference No_] = '20M39' AND a.[Document Date] >= CONVERT(datetime, '02/01/2018', 103) AND a.[Document Date] <= CONVERT(datetime, '01/02/2018', 103)
```

Can you help me?

**Comment by ajcvickers** [comment]
@antoniogarcez Can you please post the full exception message and stack trace? Also, what version of EF Core and what database provider are you using?

**Comment by antoniogarcez** [comment]
Hi,

I found the solution because I created a custom class that binded the result of query.

Thanks,
António Garcez
