### ISSUE TITLE
Allow changing the schema name

### ISSUE THREAD

**Issue by kumards** [aspnet/EntityFramework6#459]
The current implementation looks for schema name in the resource file. This disallows from configuring based on the environments like Dev, Staging and Production. There should be an easy way to change it.

Changing the schema from SetDefaultHistoryContext of DbConfiguration class throws an exception of 
"Automatic migrations that affect the location of the migrations history system table (such as default schema changes) are not supported. Please use code-based migrations for operations that affect the location of the migrations history system table."

https://github.com/aspnet/EntityFramework6/blob/276281f09118b78e74745e2dd063bcfaf50fa4ec/src/EntityFramework/Migrations/DbMigrator.cs#L788

**Comment by ajcvickers** [comment]
@kumards Are you asking for this to work with automatic migrations? If so, then the answer is no because it becomes very easy for things to go wrong--we spent a lot of time in this area and decided that the best way to handle this is to not enable it with automatic migrations.

**Comment by kumards** [comment]
Our database team doesn't allow automatic migration. Also, the DB connection string uses the limited privileged username that would disallow DDL scripts. So we generate the db script using implementation something like this

```
var scriptor = new MigratorScriptingDecorator(migrator);
string script = scriptor.ScriptUpdate(sourceMigration: null, targetMigration: null);
```
Without flexibility over schema name, we are forced to keep the schema name across the environments.
