### ISSUE TITLE
Generated file is using ANSI

### ISSUE THREAD

**Issue by tiayi** [aspnet/EntityFramework6#461]
The files generated by command such as 'enable-migration', ' add-migration' is using ANSI.
I'm not sure it's a bug.
Why don't use utf-8?

**Comment by CZEMacLeod** [comment]
@tiayi @leotsarev 
The [`MigrationWriter`](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework.PowerShell/Migrations/Utilities/MigrationWriter.cs) class takes the code generated in a [`ScaffoldedMigration`](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Migrations/Design/ScaffoldedMigration.cs) which are just strings for the `UserCode` and `DesignerCode` properties and uses an extension on `EnvDTE.Project` in the [`ProjectExtensions.cs`](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework.PowerShell/Migrations/Extensions/ProjectExtensions.cs) file to add the file to the project.
The MigrationCodeGenerators for c# and vb.net both use a [StringWriter setup with CultureInfo.InvariantCulture](https://github.com/aspnet/EntityFramework6/blob/276281f09118b78e74745e2dd063bcfaf50fa4ec/src/EntityFramework/Migrations/Design/CSharpMigrationCodeGenerator.cs#L92), although neither set the Encoding property.
This uses the basic [`System.IO.File.WriteAllText`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext) method to write out the string to the file. No encoding is given so it probably uses the Current UI locale.
I think it would definitely make sense to change this to UTF-8 and think it would only require changing the line in `ProjectExtensions.cs` `AddFile` method to `File.WriteAllText(absolutePath, contents,Text.Encoding.UTF8);`
I don't know if this would break any unit tests or have any detrimental effect, but I imagine a PR for this would be pretty easy to submit.

**Comment by leotsarev** [comment]
Question is — do we need to generate it as UTF-8 with BOM?

**Comment by ajcvickers** [comment]
@tiayi Can you be specific about what problems this is causing?

**Comment by leotsarev** [comment]
@ajcvickers  For example, we use migrations to add new instance of subscription types and user parameters. Developers add empty migration and use ```Sql("INSERT INTO")``` to add subscription. They had not to forget to manually change file encoding, or Russian symbols will be trashed in source control.

**Comment by tiayi** [comment]
@ajcvickers
I generated the migration files and input some basic data into Configuration.cs.
These data has Chinese characters. 
The CI server didn’t install the GB2312.
So these Chinese character data in DB is unreadable.
