### ISSUE TITLE
Unable to update column which is part of a unique constraint

### ISSUE THREAD

**Issue by agpreynolds** [aspnet/EntityFramework6#469]
Hello

I have an object set up as follows:

```
public class Template
{
        [Key, Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Key, Column(Order = 1)]
        [ForeignKey("Account")]
        public Guid AccountId { get; set; }

        [Key, Column(Order = 2)]
        [Required]
        [RegularExpression("^[^<>]+$", ErrorMessage = "The Name contains invalid characters.")]
        [StringLength(50)]
        public string Name { get; set; }

        public virtual Account Account { get; set; }
}
```

Id is the primary key of the table
AccountId is a foreign key on another table
The combination of name and accountId is a unique constraint.

When I attempt to update the name field, to a new value which does not violate the constraint I receive the following error:

> The property 'Name' is part of the object's key information and cannot be modified. 

I don't understand why I can update this field in raw sql but not using entity framework?

For information I am using v6.2

**Comment by ajcvickers** [comment]
@agpreynolds The Key annotations make all three properties part of the primary key for the entity. EF does not allow primary key values to be mutated.

**Comment by agpreynolds** [comment]
Yes they do, thanks for pointing out my error. Took the key annotations off of the AccountId and Name fields and all working correctly now
