### ISSUE TITLE
Bug: v6.1.3 (& v6.1.2): Deferred LINQ execution (/multi-statement) bug

### ISSUE THREAD

**Issue by DennisVM-D2i** [aspnet/EntityFramework6#470]
https://social.msdn.microsoft.com/Forums/en-US/d1c66ddb-33fd-4b6b-881b-30d911dd0a4f/bug-v613-deferred-linq-execution-multistatement-bug?forum=adodotnetentityframework

Guys & Gals, unless I don't understand a subtlety of how EF works/should work, you seem to have a bug with v6.1.3, when breaking-up LINQ queries across separate C#-statements; e.g. this works:

            var fullQry =
                dbCtx.BldAs.AsNoTracking().ToList();
But this throws an exception:

            var qry =
                (IQueryable<BldA>)dbCtx.BldAs;
            qry =
                qry.AsNoTracking();
(It seems like either invoking '.Include()' or '.ToList()' within the same statement causes things to work / the required/full initialisation to take place.)
I'm probably wrong but it looks like the _entitySet' member variable of the 'InternalSet' class is badly/only-just initialised (- only one of the properties looks like it's been initialised?!?), just enough to block the (following) full-blown initialisation from been invoked -
    public virtual void Initialize()
    {
      //  Would work fine if this was null or if _entitySet was properly/fully initialised; e.g. 'set next statement' in VS past this works fine as the following creation & initialisation then gets called
      if (this._entitySet != null)
        return;
      //  The creation of the value (for the initialisation of the '_entitySet')
      EntitySetTypePair andBaseTypeForType = base.InternalContext.GetEntitySetAndBaseTypeForType(typeof (TEntity));
      if (this._entitySet != null)
        return;
      //  Take's the created value - within the 'Pair' and initialises/sets the value of '_entitySet' with it
      this.InitializeUnderlyingTypes(andBaseTypeForType);
    }

The following exception is thrown:

Server Error in '/' Application. 

Value cannot be null.
Parameter name: queryString 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: queryString

Source Error: 

Line 20:                 (IQueryable<BldA>)dbCtx.BldAs;
Line 21: 
Line 22:             qry =
Line 23:                 qry.AsNoTracking();
Line 24: 

Source File: D:\Tmp\Tests\Ts-Mvc-WebApp-EF-1\Ts-Mvc-WebApp-EF-1\Controllers\HomeController.cs    Line: 22 

Stack Trace: 

[ArgumentNullException: Value cannot be null.
Parameter name: queryString]
   System.Data.Entity.Utilities.Check.NotNull(T value, String parameterName) +6470582
   System.Data.Entity.Core.Objects.ObjectContext.CreateQuery(String queryString, ObjectParameter[] parameters) +38
   System.Data.Entity.Internal.Linq.InternalSet`1.CreateObjectQuery(Boolean asNoTracking, Nullable`1 streaming, IDbExecutionStrategy executionStrategy) +99
   System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking() +51
   System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking() +46
   System.Data.Entity.QueryableExtensions.AsNoTracking(IQueryable`1 source) +139
   Ts_Mvc_WebApp_EF_1.Controllers.HomeController.Index() in D:\Tmp\Tests\Ts-Mvc-WebApp-EF-1\Ts-Mvc-WebApp-EF-1\Controllers\HomeController.cs:22
   lambda_method(Closure , ControllerBase , Object[] ) +61
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14

I've created an MVC 5 web-app in VS 2017 Community Edition, containing the following source-code, as a test-bed to prove the point:

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var dbCtx = new AppDbCtx();
            var dbCtxInit = new ApplicationDbInitializer();
            dbCtxInit.InitializeDatabase(dbCtx);
            var qry =
                (IQueryable<BldA>)dbCtx.BldAs;
            qry =
                qry.AsNoTracking();
            var fullQry =
                dbCtx.BldAs.AsNoTracking().ToList();
            return View();
        }

namespace Ts_Mvc_WebApp_EF_1.Data
{
    public class BldA
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

using System.Data.Entity;
namespace Ts_Mvc_WebApp_EF_1.Data
{
    public class AppDbCtx : DbContext
    {
        public AppDbCtx()
            : base(@"DefaultConnection")
        {
        }
        public IDbSet<BldA> BldAs { get; set; }
    }
}

using System.Data.Entity;
namespace Ts_Mvc_WebApp_EF_1.Data
{
    public class ApplicationDbInitializer : CreateDatabaseIfNotExists<AppDbCtx>
    {
    }
}
<package id="EntityFramework" version="6.1.3" targetFramework="net471" />

  <connectionStrings>
    <add name="DefaultConnection" connectionString="Data Source=.\MySqlServer2016Instance; Initial Catalog=Ts-Mvc-WebApp-EF-1; Integrated Security=SSPI" providerName="System.Data.SqlClient" />
  </connectionStrings>

Further to my bug discovery; it seems it's also (/first) broke(n) in v6.1.2, but is fine for the surrounding versions, v6.1.1 and v6.2.0, so:
    v6.2.0 - Pass
    v6.1.3 - Fail
    v6.1.2 - Fail
    v6.1.1 - Pass
    v6.0.2 - Pass

F.Y.I. Seems to me (in the meantime / assuming it'll be fixed upon the v6.1.x stream at some point) like you probably have 3 choices for this EF (v6.1.3-v6.1.2) bug - either option not so clear-cut

1) upgrade to EF v6.2.0 - but that *might* be a leap to far / bring it's own compatibility and/or new issues, or

2) downgrade to EF v6.1.1 but only as long as you're *not* using 'AutoMapper.EF6' (- which has EF version >= 6.1.3 as one of its 'dependencies'), or

3) call the 'Include()' (or other ? same-side-effect) method - to force the initialisation to occur as a side-effect (- assuming you can / you've something (& it is also small) to include)

**Comment by ajcvickers** [comment]
Closing, since it is working in the 6.2 release and we don't have any plans to port to a patch release for 6.1.
