### ISSUE TITLE
Insert Expression into MemberInit

### ISSUE THREAD

**Issue by bdebaere** [aspnet/EntityFramework6#474]
I need to expand an object with more information. Normally I would use DTO's for this, but this stops navigation properties from working. I need both navigation properties and extra properties because OData will expose these entities. This is a requirement set upon me, not by me.

For example
```csharp
public class Item
{
    public int Id { get; set; }

    public int Amount { get; set; }

    public virtual ICollection<SubItem> SubItems { get; set; }
}

public class SubItem
{
    public int Id { get; set; }

    public int Quantity { get; set; }

    public int UnitPrice { get; set; }

    public virtual Item { get; set; }
}
```
I need to fill `SubItems.Sum(s => s.Quantity * s.UnitPrice)` into `Amount`. It's possible to do this with AutoMapper or ExpressionFramework. I can also do it myself without issue. It's combining the navigation properties with extra properties where it gets hard.

My first idea was to map `Item` to `DtoItem` with the extra property `Amount` but then I find myself unable to create an expression tree because of circular reference. I need to specify how to create `DtoItem` and for `DtoItem.SubItems` I need to specify how to create `DtoSubItem` which in turn will again lead to `DtoSubItem.DtoItem` needing to know how to be created.
```csharp
        public static Expression<Func<TSourceType, TDestinationType>> Transform<TSourceType, TDestinationType>()
        {
            Type sourceType = typeof(TSourceType);
            Type destinationType = typeof(TDestinationType);
            ParameterExpression sourceParameter = Expression.Parameter(sourceType);

            NewExpression constructor = Expression.New(destinationType);
            List<MemberAssignment> memberBindings = new List<MemberAssignment>();

            IEnumerable<PropertyInfo> destinationProperties = destinationType
                .GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanWrite);

            foreach (PropertyInfo destinationProperty in destinationProperties)
            {
                PropertyInfo sourceProperty = sourceType.GetProperty(destinationProperty.Name, BindingFlags.Instance | BindingFlags.Public);

                if (sourceProperty == null)
                {
                    continue;
                }
                LambdaExpression sourcePropertyAccessor = Expression.Lambda(Expression.Property(sourceParameter, sourceProperty), sourceParameter);

                if (sourceProperty.Name == "Amount") // Just test code
                {
                    sourcePropertyAccessor = Accessor<Item>.ExtractFrom(e => e.SubItems.Count);
                }

                memberBindings.Add(Expression.Bind(destinationProperty, new ReplaceVisitor(sourcePropertyAccessor.Parameters[0], sourceParameter).Visit(sourcePropertyAccessor.Body)));
            }

            Expression body = Expression.MemberInit(constructor, memberBindings);

            return Expression.Lambda<Func<TSourceType, TDestinationType>>(body, sourceParameter);
        }
    }
```

My second idea was to map `Item` to `Item` and insert the `Expression` into the `MemberInit` node by replacing the `MemberBinding` I need to and not touching anything else. This way I was hoping to leave the entity creation to Entity Framework and only replace a single part that I want. However any attempt to map Item to Item is met with "The entity or complex type 'Item' cannot be constructed in a LINQ to Entities query". On top of this I also cannot seem to get to the MemberInit node which Entity Framework calls.

Note: I cannot use `public int Amount { get { return SubItems.Sum(s => s.Quantity * s.UnitPrice); }` because this will cause selecting just this column to fail since it is not mapped to a database column.

Can you point me in the right direction?

**Comment by ErikEJ** [comment]
Partial classes with NotMapped properties?

**Comment by bdebaere** [comment]
@ErikEJ Hi, I'm not sure if I get what you mean but I forgot to mention (I added it now) that I cannot use `public int Amount { get { return SubItems.Sum(s => s.Quantity * s.UnitPrice); }` because only selecting this column will fail then.

**Comment by ajcvickers** [comment]
@bdebaere I have read through this several times and thought about it and we discussed it as a team in triage, but so far we can't come up with any way you can do this with EF6. I think this is just beyond the capability of EF6 to map.
