### ISSUE TITLE
EntityFramework package (not core), has bad frameworkassembly values

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#48]
_From @rrelyea on August 8, 2016 21:5_
### Steps to reproduce

originally filed as: https://github.com/NuGet/Home/issues/3279
**Repro Steps:**
1. Create a new project C#-> Windows 8->Windows Runtime Component (Windows 8.1).
2. Right-click the project node and click "Manage NuGet Packages…" menu to start package manager.
3. Install package “EntityFramework”, and verify it can be installed.

**Expected Result:**
The package “EntityFramework” can be installed correctly.

**Actual Result:**
The package “EntityFramework” can’t be installed as below screenshot.

![untitled841](https://cloud.githubusercontent.com/assets/20632775/17431510/f8150424-5b2c-11e6-9642-e5a3735887e3.png)

**Note:**
It happened on Dev14 U3+NuGet Dev 1731(3.6.0.1731).
It repro on any version of package “EntityFramework”.
It also repro on Dev14 U3 (NuGet 3.4.4.1321).
### The issue

NuGet sees 
`<FrameworkAssembly` ... TargetFramework="" />
TargetFramework should not be empty, but should be Net40 or Net45.

When you don't specify a framework, nuget thinks this works in all TFMs. Thus the package seemed to install on this Win8.1 project, while it should fail.
### Further technical details

None.

_Copied from original issue: aspnet/EntityFramework#6272_

**Comment by ErikEJ** [comment]
EF 6 is not supported on Windows Runtime (WinRT) Components, I believe....

**Comment by divega** [comment]
> __Expected Result:__
> The package “EntityFramework” can be installed correctly.

This will never work for EF6, so the fix we can do is to make sure the package won't be listed for platforms that it doesn't support.

**Comment by bricelam** [comment]
So I tried this before a long time ago, but I couldn't remember why it didn't work. Looking into it again, it's because we have `content` (for App.config). There is no way to have framework-specific content, so the package will always install on any framework no matter what restrictions we put on lib, tools, dependencies, or frameworkAssemblies.

**Comment by bricelam** [comment]
So we can either
1. Fix the `targetFramework` attribute so the error goes away and it "successfully" installs (with nothing in your project) on any framework.
2. Do nothing so you'll continue to get an obscure error on other frameworks.

**Comment by ErikEJ** [comment]
Plague or cholera, as we say in Danish

**Comment by divega** [comment]
@bricelam does this help? https://github.com/NuGet/Home/issues/2969#issuecomment-225932621

**Comment by bricelam** [comment]
Oh weird, I couldn't find that anywhere in the documentation. I'll give it a try.

**Comment by bricelam** [comment]
It worked. And it's [documented](https://docs.nuget.org/ndocs/create-packages/supporting-multiple-target-frameworks#content-files-and-powershell-scripts). 🐑
