### ISSUE TITLE
Entity Frameworks MySql.Data connection Error.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#486]
From VS Feedback:

I have a Asp.net MVC application that uses an MySql database and Asp.net Identity for authentication. I have customised the UserStore but when i try to register a new user i get the error "System.ArgumentNullException: Value cannot be null. Parameter name: entity ". When digging deeper using the tool tips and drilling into the exception i found on the  "Database Connection" 3 properties return "NullReferenceExceptions". Properties are "IsPasswordExpired", "Server Thread" and "Server version". I have attached screen shots of the exceptions. The Exception says that the "Namespace 'Data' does not exsist in my project namespace". I have checked all references in my project and its their. I have attached screen shots of my EF version, MySql.Data version. I have searched on google and StackOverflow but found no relevant info. I have also uninstalled adn re-installed Nuget packages  "MySql.data " and "MySql.Data.Entity" with no success.

Hope you can assist. Please let me know if you need additional info.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by NicoSlabbert** [comment]
Hi Arthur,

I will upload my project a bit later. My apologies for the lack of info.

**Comment by NicoSlabbert** [comment]
Good day,

I have uploaded my project. Link is: [https://github.com/NicoSlabbert/AgriAssure](url).

Regards

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
