### ISSUE TITLE
Generate SQL outside of VS

### ISSUE THREAD

**Issue by nojaf** [aspnet/EntityFramework6#490]
Hi, I'd like to run

```update-database -ConfigurationTypeName MyConfigType -script -force``` outside of VS.
Is this possible using the `migrate.exe` tool, what does [ScriptFile](https://github.com/aspnet/EntityFramework6/blob/master/src/Migrate/Arguments.cs#L47) do in this case?
I would like to have the SQL script only.

**Comment by ErikEJ** [comment]
What have you tried?

**Comment by nojaf** [comment]
```
.\migrate.exe "Portal.Data" "MyContextConfig"
  /scriptFile "C:\Temp\migrate.sql" /startUpDirectory "C:\TFS\Code\Client\Product.Portal.Web"
```

`Portal.Web` is the root of an ASPNET MVC project. Not sure if that should be the bin folder or not?

**Comment by nojaf** [comment]
This was silly, I needed to add `=` or `:` between the optional arguments.
F.ex `/scriptFile`**:**`"C:\Temp\blah.sql"`
