### ISSUE TITLE
EF6 Cascading Delete failing when setting EntityState = Deleted

### ISSUE THREAD

**Issue by drewwilliams1982** [aspnet/EntityFramework6#500]
I have two entities, defined using EF Code First Fluent API; Grade that contains many Students. The mapping for Grade is:
```C#
   modelBuilder.Entity<Grade>()
            .Map(m =>
            {
                m.ToTable("Grade");

                m.Property(g => g.GradeId).HasColumnName("GradeId");
                m.Property(g => g.GradeName).HasColumnName("GradeName");
            })
            .HasKey(g => g.GradeId)
            .HasMany(g => g.Students).WithRequired(s => s.Grade).HasForeignKey(s => s.GradeId);
```
As you can see, it is a required relationship between Grade and Student. The mapping for Student is a straightforward mapping.

When I delete the Grade I want to cascade delete the associated Students. I don't mind how I do this, either letting EF cascade the delete, or letting the database handle it.

Using the existing infrastructure available to me, the way we currently delete is along the lines of:
```C#
        using (var ctx = new SchoolContext())
        {
            var grade = ctx.Grades.Include(gr => gr.Students).FirstOrDefault();
            ctx.Entry(grade).State = EntityState.Deleted;
            ctx.SaveChanges();
        }
```
This throws an InvalidOperationException (The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted).

If I use the DbSet to remove the entity, then it works fine. I.e.
```C#
        using (var ctx = new SchoolContext())
        {
            var g = ctx.Grades.Include(gr => gr.Students).FirstOrDefault();
            ctx.Grades.Remove(g);
            ctx.SaveChanges();
        }
```
This way, EF handles the cascade and deletes the Students itself. However, this would be a massive change to our existing infrastructure.

What is the difference between these two methods of deleting? Why does setting the state on the entity entry cause "conceptual nulls" to be detected, but not when deleting via the DbSet?

How can I delete via setting the state so that either EF cascades the delete, or the database is left to manage it?

**Comment by ajcvickers** [comment]
@drewwilliams1982 We discussed this as a team and looked at some history, and while it's not clear to us now why the behavior of setting the Deleted state is different than calling Remove, we unfortunately cannot now change this without it breaking existing applications.
