### ISSUE TITLE
IndexAttribute or IndexAnnotation not working while initializing MySQL

### ISSUE THREAD

**Issue by euyuil** [aspnet/EntityFramework6#51]
I haven't tested with SQL Server yet and am not sure if the issue is only for MySQL.

Package versions:
* EntityFramework 6.1.3
* MySql.Data 6.9.9
* MySql.Data.Entity 6.9.9

Simplified code:
```
public class MyDbContext : DbContext
{
    public MyDbContext() : base("MyDbContextConnectionString")
    {
        Database.SetInitializer(new MyDbInitializer());
    }

    public DbSet<User> Users { get; set; }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        // The following code doesn't work either.
        // modelBuilder.Entity<User>()
        //     .Property(e => e.Mobile)
        //     .HasColumnAnnotation(
        //         IndexAnnotation.AnnotationName,
        //         new IndexAnnotation(new IndexAttribute("IX_Mob") { IsUnique = true }));
    }
}

public class MyDbInitializer : DropCreateDatabaseAlways<MyDbContext>
{
}

public class User
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    [Index(IsUnique = true)]
    public string Mobile { get; set; }
}

internal static void Main(string[] args)
{
    using (var context = new MyDbContext())
    {
        // ...
    }
}
```

I expect the table to be created with a primary key `Id` and a unique index for column `Mobile`. But the result was that a primary key index for `Id` was created, and a redundant unique index for `Id` was also created, but the expected unique index for `Mobile` was not.

Screenshots from MySQL Workbench:

![s1](https://cloud.githubusercontent.com/assets/1539596/17858612/f354c71e-68b8-11e6-8b81-c1eac1de1176.png)

![s2](https://cloud.githubusercontent.com/assets/1539596/17858626/f9d23c52-68b8-11e6-807e-272dfa6d3ce7.png)

Full code and project files:

[eftest.zip](https://github.com/aspnet/EntityFramework6/files/430385/eftest.zip)

**Comment by divega** [comment]
@euyuil I am not familiar enough with the MySQL provider to know for sure, but this might be a limitation if support for index migrations operations was not added. If you can prove that this works with SQL Server but not with MySQL, I would encourage you to file a bug. I believe https://bugs.mysql.com/ is the right place to do so.

cc @gmartinezsan.

**Comment by divega** [comment]
**EF Team Triage:** Closing as with the current information we believe this issue is external to EF and not actionable for the EF team. Hopefully the information provided can help redirect the issue to the owners of the MySQL provider where it can be addressed.

**Comment by gmartinezsan** [comment]
Hi, I added a bug so you can follow up @euyuil if you like. We'll check if there is any issue in the MySQL provider.

Here's the link of the bug.
http://bugs.mysql.com/bug.php?id=82828

Feel free to subscribe.

Thanks!
