### ISSUE TITLE
Navigation property encapsulation

### ISSUE THREAD

**Issue by chrysikos** [aspnet/EntityFramework6#513]
Is it possible to configure mapping with protected navigation properties?

```
    public class Customer
    {
        public int ID { get; protected set; }
        public string CompanyName { get; protected set; }

        protected Customer()
        {
            this.BranchOffices = new HashSet<BranchOffice>();
        }


        protected virtual ICollection<BranchOffice> BranchOffices { get; set; }

        public IEnumerable<BranchOffice> GetBranchOffices()
        {
            return item only in a specific range.
        }
   }
```

**Comment by jlchavez** [comment]
You can use "internal protected" so that it can be seen by derived types and your own assembly, so that it is visible for setting it up with FluentApi on a OnModelCreating method on the DbContext derived class or on a EntityTypeConfiguration<BranchOffice> derived class.

The following sample completes your code

```
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;

namespace Sample
{
    public class BranchOffice
    {
       public int ID { get; protected set; }
       public string CompanyName { get; protected set; }

       internal protected virtual Customer Customer { get; set; }
    }

    class BranchOfficeConfiguration : EntityTypeConfiguration<Customer>
    {
        public BranchOfficeConfiguration()
        {
            this.HasKey(x => x.ID);
            this.HasRequired(x => x.Customer).WithMany(x => x.BranchOffices).HasForeignKey(x => x.CustomerID);
        }
    }

    class MyContext : DbContext
    {
        public MyContext (string connectionString) : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           modelBuilder.Configurations.Add(new BranchOfficeConfiguration());
           base.OnModelCreating(modelBuilder);
        }
    }
}
```

**Comment by chrysikos** [comment]
My apologies because I wasn't so clear about my problem. For my current project I use DDD approach. Firstly, Domain layer is physically separated in different assembly from Persistence layer. So, the “internal protected” doesn’t fit in this situation. Secondly, in Domain layer I have many Aggregates each with its own Aggregate Root and I don’t want domain model from different Aggregates to have access directly to a “model” with Navigation property because this is a potential violation of model invariants. 


`   public class ClientAggregate
    {
        private Order _order;

        public ClientAggregate()
        {
            this._order = new Order();
        }

        public void DoSomething()
        {
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
            this._order.OrderItems.Add(new OrderItem());
        }
    }


    public class Order : AggregateRoot<Guid>
    {
        public virtual ICollection<OrderItem> OrderItems { get; set; }


        public void Add(OrderItem orderItem)
        {
            if(OrderItems.Count >= 5)
                throw new InvalidOperationException("5 items per order.");


            OrderItems.Add(orderItem);
        }
    }
`

**Comment by ajcvickers** [comment]
@chrysikos See https://blog.oneunicorn.com/2012/03/26/code-first-data-annotations-on-non-public-properties/
