### ISSUE TITLE
Migration silently fails to set identity

### ISSUE THREAD

**Issue by klamfeldt** [aspnet/EntityFramework6#52]
Hi

I cant change a Primarey key from being not identity to be Identity. The migration file looks correct but column is still not Identity after db update. Looks like there is a workitem om codeplex aswell, se below.

https://entityframework.codeplex.com/workitem/509

**Comment by bricelam** [comment]
Note to assignee: Having `identity: true` on the `AlterColumnOperation` is OK if the column was created with `IDENTITY`.

**Comment by divega** [comment]
**Triage:** we are not planning to do this in EF6.x at this point but we will do it in EF Core 1.x.
