### ISSUE TITLE
Db Migration Fails when trying to update.

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#53]
_From @rufio620 on August 20, 2016 3:13_
### Steps to reproduce

I added a new table to my database which participates in a one to many  relationship with another table. When I scaffold the migration I get the following code.

``` c#
public override void Up()
        {
            CreateTable(
                "TemplateDefinition",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        BusinessDomainId = c.Guid(nullable: false),
                        InputViewModelId = c.Guid(),
                        SystemName = c.String(nullable: false, maxLength: 255),
                        TemplateMarkup = c.String(),
                        InvariantId = c.Guid(nullable: false),
                        DisplayName = c.String(nullable: false, maxLength: 255),
                        Description = c.String(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("BusinessDomainDefinition", t => t.BusinessDomainId, cascadeDelete: true)
                .ForeignKey("ViewModelDefinition", t => t.InputViewModelId)
                .Index(t => t.BusinessDomainId)
                .Index(t => t.InputViewModelId);

        }
```

Upon applying this migration I get the following error.

```
Applying explicit migrations: [201608200256366_MigTemplateDefs].
Applying explicit migration: 201608200256366_MigTemplateDefs.
The Foreign Key on table 'TemplateDefinition' with columns 'InputViewModelId' could not be created because the principal key columns could not be determined. Use the AddForeignKey fluent API to fully specify the Foreign Key.
```

The BusinessDomainDefinition table was created in a previous migration and has a primary key. There are also several other 1 to many child tables created in the initial migration that are applied without the same error. 
### The issue

EF Migrations should be able to apply this without an issue. It is a simple 1 to many relationship. If I delete all migrations and re scaffold the entire database the update works without any problem. 

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
### Further technical details

EF Version 6.1.3
Visual Studio 2015 Community

Other details about my project setup:

_Copied from original issue: aspnet/EntityFramework#6378_

**Comment by divega** [comment]
@rufio620 could you provide a full repro? The full project would be ideal, but otherwise the model could help if it repros consistently.

**Comment by rufio620** [comment]
I'll put together a repro project today or tomorrow and post it.

**Comment by rufio620** [comment]
Attached is a repro project. There is a sql server 2012 database backup that has the first migration run. If you open the solution build and run update-database the error should be reproduced. Everything seems to run without issue if all the changes are scaffolded into a single migration. Let me know if you need any additional information. Thanks for your help.

```
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201608310542208_CreateChildEntity].
Applying explicit migration: 201608310542208_CreateChildEntity.
The Foreign Key on table 'ChildEntity' with columns 'ParentId' could not be created because the principal key columns could not be determined. Use the AddForeignKey fluent API to fully specify the Foreign Key.
```

[EF6_Issue53.zip](https://github.com/aspnet/EntityFramework6/files/446487/EF6_Issue53.zip)

**Comment by rowanmiller** [comment]
I did not get to this one before vacation. Clearing up in case someone else wants to take it while I am out. Feel free to assign back to me to deal with when I get back if you want 😄.

**Comment by smitpatel** [comment]
I investigated this. The issue is arising due to this
`modelBuilder.HasDefaultSchema(string.Empty);`

The default schema is set as empty string and is reflected in generated migrations but when we try to apply migration, instead of picking empty string as default schema we get dbo. Probably somewhere we converted empty string to null and default schema logic picks dbo when null. Due to this while populating FK operation, it is not able to find the principal entity type. (the name in XML doesn't contain dbo but node we are searching for does). And exception is thrown because no PK found (because principal end not found).
This works fine if the principal table is created in same migration because if we cannot find it in EDMX model we look for CreateTableOperation in same migration to locate principal table.

Changing default schema to something else or removing the configuration also works correctly.

**Comment by kenchen20050821** [comment]
if i don't do that
modelBuilder.HasDefaultSchema(string.Empty);
EF.Extend could not work well with the "dbo" issue...

**Comment by rufio620** [comment]
There are definite issues with the way this works currently. Especially across providers. Entity framework migrations does not provide a way of generating scripts that are schema agnostic. For internal enterprise apps hard coding the schema may be acceptable but for products it is not. Consumers of a software product may install the schema anywhere. Without this line schema is generated with hard coded dbo and with oracle the connecting schema name. With it the generation throws an exception. This breaks any ci generation of script updates. This really seems like a defect that should be addressed unless there is some other work around to generating scripts without hard coded schema that I am not aware of.
