### ISSUE TITLE
Change return type of DbContext.Set from DbSet<T> to IDbSet<T>

### ISSUE THREAD

**Issue by jinek** [aspnet/EntityFramework6#536]
Current signature does not allow to use own implementation of IDbSet<T>.
Current implementation does not allow to use InitializeSets to initialize context with custom implementation if IDbSet<T>:

```
    public class TestContext : DbContext
    {
        public override DbSet<TEntity> Set<TEntity>()
        {
            return new MyCustomSet<TEntity>(base.Set<TEntity>());
        }
    }
```
(compilation error as MyCustomSet can not be converted to DbSet)

### Further technical details
EF version: 6.0

**Comment by ajcvickers** [comment]
@jinek This is not something we can do at this time because it would be a big breaking changes for all existing applications that assume Set returning a DbSet.

**Comment by jinek** [comment]
May be it is possible to introduce "IDbProperSet" (to be returned) and create an inheritor of DbSet to leave backward compatibility?

**Comment by jinek** [comment]
If application assume DbSet will be returned, inheritor is assumed too, right?

**Comment by jinek** [comment]
Also one more virtual method can be introduced, that will leave all other methods as is

**Comment by Erutan409** [comment]
@jinek Did you ever figure this out?

**Comment by jinek** [comment]
> @jinek Did you ever figure this out?

As I remember I did dynamic module generation and substituted few methods using MonoMod.RuntimeDetour, and very next time I did another hack creating IList implementation to implement special processing of linq queries.
I don't own the code now, sorry. 
But now i think, if it costs the thing, just fork the repo and change the return type may be?
