### ISSUE TITLE
Windows 10 (1803) - Entity Framework Error after updating Windows - “The incoming tabular data stream (TDS) remote procedure call > (RPC) protocol stream is incorrect”

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/EntityFramework6#537]
Hi there, 

I found some of my queries are not working after updating to Windows 10 version 1803. I can confirm that the same code works on machines without this update. 

The error I keep getting is this:
```sql
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 2 (""): Data type 0x00 is unknown.
```

Interestingly if I make the query non async then everything seems to work. Has something changed since Windows 10?

**Other users have also indicated having the same problem**
https://stackoverflow.com/questions/50340258/entity-framework-error-after-updating-windows-the-incoming-tabular-data-strea

### Further technical details
EF version: 6.2
Database Provider: Azure SQL Server
Operating system: Windows 10 (1803) - April 2018 update 
IDE: Visual Studio 2017 15.7

**Comment by chainbridgetech** [comment]
I can report that I received the same error after updating to 1803. A system restore back to 1709 has temporarily fixed the problem.

**Comment by ErikEJ** [comment]
Sounds like a SqlClient bug, not an EF6 issue

**Comment by dotnetshadow** [comment]
@ErikEJ Any idea where I can report this?

**Comment by ErikEJ** [comment]
I am sure the EF team will know who to notify

**Comment by divega** [comment]
@dotnetshadow Thanks for reporting this. I am going to be moving this issue to https://github.com/Microsoft/dotnet/issues, which is where issues for SqlClient on .NET Framework are tracked. In the meantime, it would be great if you could provide a repro project.

**Comment by divega** [comment]
This issue was moved to Microsoft/dotnet#749
