### ISSUE TITLE
Investigate and Re-enable TextTemplating Unit Tests

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#541]
When we switched to VS 15.6 Preview 7 on the Dev15 CI machine, 5 tests stopped working:

- CodeFirstModelGeneratorTests.Generate_returns_code_when_cs_and_customized
- CodeFirstModelGeneratorTests.Generate_returns_code_when_vb_and_customized
- CodeFirstModelGeneratorTests.Generate_throws_when_error_in_context_template
- CodeFirstModelGeneratorTests.Generate_throws_when_error_in_entity_type_template
- TextTemplatingHostTests.ProcessTemplate_returns_result

These all look like they have something to do with TextTemplating not working because the compile step of text templating was expecting to find DLLs which were no longer available or not available in the places VS was searching. This does *not* affect actual text templating so it appears to be a problem just with how the unit tests are setup.

So we commented out those tests for now, but we should investigate and re-enable those 5 tests as soon as we can.

**Comment by ajcvickers** [comment]
@lajones Could this be related to the VS 2019 T4 issues?
