### ISSUE TITLE
EF.Functions.Like translate to strange SQL

### ISSUE THREAD

**Issue by proms2018** [aspnet/EntityFramework6#542]
I'm doing this:

```
var lst2 = from c in dbCtx.Estados where EF.Functions.Like("Estado", "%Sur") select c;
var res = lst2.ToArray();

```
And it translates into:

```
exec sp_executesql N'SELECT [c].[Id], [c].[Estado]
FROM [Estados] AS [c]
WHERE @__Like_0 = 1',N'@__Like_0 bit',@__Like_0=0
```

And doing this also:

```
var lst2 = dbCtx.Estados.Where(c => EF.Functions.Like("Estado", "%Sur"));
var res = lst2.ToArray();
```

Same results:

```
exec sp_executesql N'SELECT [c].[Id], [c].[Estado]
FROM [Estados] AS [c]
WHERE @__Like_0 = 1',N'@__Like_0 bit',@__Like_0=0
```

Any ideas why?
Thanks

**Comment by maumar** [comment]
@proms2018 it's because the arguments to Like function are not correlated with entities, so EF determines the result can be computed without accessing the database. If one of the arguments was a column reference it will get translated to server LIKE function.
