### ISSUE TITLE
Respond to Changes in EnvDTE.ProjectKind

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#547]
A change is being made to `EnvDTE.ProjectKind`. We will need to look through our code and make sure everything is still working and make changes as appropriate. See email on 5/24/18 titled "Breaking change: Project.Kind for C#/VB/F# CPS projects is changing". Quick summary:

Language | Previous Project.Kind | New Project.Kind
-- | -- | --
C# | {9A19103F-16F7-4668-BE54-9A1E7A4F7556} | {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
Visual Basic | {778DAE3C-4631-46EA-AA77-85C1314464D9} | {F184B08F-C81C-45F6-A57F-5ABD9991F28F}
F# | {6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705} | {F2A71F9B-5D33-465A-A702-920D77279786}

**Comment by ErikEJ** [comment]
Noooo - when will this happen??

**Comment by ajcvickers** [comment]
@ErikEJ To clarify a bit more:
> We’re making a breaking change to the return value of EnvDTE.Project.Kind for managed C#, Visual Basic and F# projects that open in the Common Project System (CPS). These are traditionally .NET Core/ASP.NET Core/.NET Standard projects, however, can also target .NET Framework in certain scenarios.

> This value has been changed to match their equivalent in the native project system (.NET Framework, Xamarin, UWP and Portable). This change does not affect the native C#/VB project systems.

**Comment by ErikEJ** [comment]
Thanks!

**Comment by ajcvickers** [comment]
Since EF6 doesn't support the new-style projects anyway, this is unlikely to be an issue for us. It could actually make things work, although there will likely still need to be more work done as part of the Core port.
