### ISSUE TITLE
use ef6 and mysql 

### ISSUE THREAD

**Issue by webvn123** [aspnet/EntityFramework6#558]
i had use ef code first to create database,and i used charset = utf8 in <connectionStrings>
but the  generate database charset is latin1 -- cp1252 West European.
before i use unity to mapping the identity tables ,i can insert chinese to tables
if the mapping error Cause fail to generate database ?
are you help me ?
oh! my english so bad!!

**Comment by jawn** [comment]
Sounds like an excellent question for stackoverflow.
