### ISSUE TITLE
Code First related internal classes for non SQL Servers

### ISSUE THREAD

**Issue by VishDev2018** [aspnet/EntityFramework6#560]
Hi,
 we are investigating into the work involved in supporting Code First for one of our Database Servers and as a first step, we were looking into Create Database and Create Table from models workflow. We need to access some of the internal classes of MS Entity Framework(DatabaseTableChecker and DatabaseExistenceState as examples). Can you please let us know what is the best practice for using these? Also, we see the DefaultScheme being tied to dbo which is not our default schema. Are there any design guidelines for supporting code first workflow?

Thanks for the help
Vishwa

**Comment by ajcvickers** [comment]
@VishDev2018 Internal classes are internal to the EF code and should not be used from your code. With regard to "design guidelines for code first workflow" can you be more specific?

**Comment by VishDev2018** [comment]
Thanks for your quick response. 
I understand the intent of Internal namespace, but what is not clear is, if other providers of EntityFramework have to support Code First workflow, what are the guidelines. For example, if we use the existing EF workflow, it has code suited to SQL Server. We see code such as DefaultSchema as dbo which is not valid for others. I assume there must be some guidelines for other providers on how to use existing infrastructure and classes such as Database Initializers, CreateDatabaseIfNotExists, InternalContext etc. Specifically, I am looking for what to re-use and how and what custom code we have to develop specific to our providers.
