### ISSUE TITLE
Change default value of useSuppliedContext to true in MigrateDatabaseToLatestVersion

### ISSUE THREAD

**Issue by binki** [aspnet/EntityFramework6#563]
The `MigrateDatabaseToLatestVersion` initializer ignores the context passed to [`IDatabaseInitializer<TContext>.InitializeDatabase(TContext context)`](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/MigrateDatabaseToLatestVersion%60.cs#L90) by default. This is because [the default constructor’s default value for `useSuppliedContext` is `false`](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EntityFramework/MigrateDatabaseToLatestVersion%60.cs#L33). It appears from 777a7a77a740c75d1828eb53332ab3d31ebbcfa3  that this decision was made because respecting the context was added as a new feature to a patch release. The wording of that commit suggests that the default value could be changed in a minor release or, if it wasn’t meant to suggest that, at least the default value could be changed in a major release.

I think this default value should be changed or scheduled to change in 6.3 or 7.0.

### Steps to reproduce

Consider a project like https://github.com/binki/EntityFrameworkMigrationUseContext where the context is always given a dynamic connection string and I have opted for [a default construction of `MigrateDatabaseToLatestVersion`](https://github.com/binki/EntityFrameworkMigrationUseContext/blob/72dfc09158358c53769cd01aebdfa3114f186534/EntityFrameworkMigrationUseContext/ProgramContext.cs#L13). In that application, you would

1. Run `set-connection` and respond to the prompt with something like `Data Source=(LocalDb)\v11.0;Integrated Security=true;Initial Catalog=efmig0` (adjust for your version of LocalDb or to point to a real server).
2. Run some command which accesses the database like `list`.

Upon trying to run `list`, the first access triggers the initializer to run. However, the initializer, by default, ignores the supplied context and tries initializing the “default” connection (which doesn’t point to anything on my machine and thus crashes the app).

Developers can work around this by specifying `useSuppliedContext=true` to override the default value of false. However, I would argue that the default value is [unintuitive and rarely what one wants](https://stackoverflow.com/q/45285687/429091).

I think the default should be changed to help developers into the [Pit of Success™](https://blog.codinghorror.com/falling-into-the-pit-of-success/).

### Further technical details
EF version: (6.2.0
Database Provider: default (EntityFramework.SqlServer?)
Operating system: Windows 10 version 1803 build 17692.1000.
IDE: Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment]
Unfortunately, this would be a breaking change, which means we won't be making in the EF6 codebase.
