### ISSUE TITLE
Entity Framework 6 MySQL update operation affects all the rows.

### ISSUE THREAD

**Issue by jovvybersamin** [aspnet/EntityFramework6#564]
This is my update.

```
   public void Update(User user)
        {
            using (var ctx = new DataSystemDbContext())
            {
                ctx.Users.Add(user);
                ctx.Entry(user).State = EntityState.Modified;
                ctx.SaveChanges();
            }
        }
```

When it executes all the rows are updated.

**Comment by divega** [comment]
@jovvybersamin EF normally generates UPDATE statements that contain a condition I the WHERE clause to only affect the row that matches the value of the entity key. 

Can you confirm that the SQL statement being sent to the database is missing this condition? If yes, I would suggest that you report this as a possible bug on the MySQL provider you are using.

Otherwise, another possibility that comes to mind is that the entity key could incorrectly mapped in your model to a column that is not the primary key on the table on the database, and that instead of having a unique value on each row, has the same value in all rows.

**Comment by jovvybersamin** [comment]
Hi @divega,

Yes,  the WHERE clause with value ID is missing.

Below is sample generated sql.

```
`User_Update`
-- Id: '6' (Type = Int32, IsNullable = false)
-- Username: 'test123' (Type = String, IsNullable = false, Size = 7)
-- Password: 'vZxTTTgLiQUxwchySt1e1o/I9XMWm4QW5pO6MpPGI0o=' (Type = String, IsNullable = false, Size = 44)
-- Email: 'test1@gmail.com' (Type = String, IsNullable = false, Size = 15)
-- FullName: 'test1' (Type = String, IsNullable = false, Size = 5)
-- CreatedAt: 'null' (Type = DateTime, IsNullable = false)
-- UpdatedAt: 'null' (Type = DateTime, IsNullable = false)
-- RoleId: '2' (Type = Int32, IsNullable = false)
-- Executing asynchronously at 
-- Completed in 9 ms with result: 6

```
My SO Post [](https://stackoverflow.com/questions/51008874/mysql-entity-framework-6-update-affecting-all-rows-code-first)

**Comment by divega** [comment]
@jovvybersamin that doesn’t seem to include a full SQL statement, therefore it is inconclusive. However I would start reporting this as a possible bug on MySQL.Data.Entity.

**Comment by divega** [comment]
I am guessing User_Update is a stored procedure. What is in the body?

**Comment by divega** [comment]
Troubleshooting tip: try invoking that stores procedure with the right parameter values from ADO.NET.

**Comment by jovvybersamin** [comment]
Removing the MapToStoredProcedure in my DbContext fixes the issue.

And then I ran my migration again to delete all created stored procedures.

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
     base.OnModelCreating(modelBuilder);    
     // Mapp all entities in a single line.    
     //modelBuilder.Types().Configure(t => t.MapToStoredProcedures());
}
```

The User_Update stored procedure generated by Entity Framework has where Id = @Id ( something like that.) My Configuration file is updated and does not have code to generate the stored procedure anymore.

**Comment by divega** [comment]
@jovvybersamin if I understand correctly, you are ok with avoiding stored procedures as a workaround, however the issue still exists and can cause data loss. 

Are you planning to follow up with the owners of MySQL.Data.Entity to get this fixed?

**Comment by jovvybersamin** [comment]
That would be great, I prefer using a stored procedure to prevent data loss. Where I can issue this for the owners of MySQL.Data.Entity?

**Comment by divega** [comment]
I believe the right place for that is ttps://bugs.mysql.com/. It will help a lot if you can provide a repro project.
