### ISSUE TITLE
Verify EF packages work correctly in Visual Studio 2017

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#58]
We have been made aware of various compatibility issues at various stages of the development of Visual Studio 15. In particular issues around components no longer being in the GAC in low-impact installs and implicit dependencies and other assumptions in our PowerShell scripts and our treatment of AppDomains.

Many known issues have been fixed but we should keep testing our packages with recent builds.

**Comment by figher56** [comment]
Julie Lerman in her post "Installing EF Power Tools into VS2015" provided a fix to get the product installed in VS 2015 by adding a new node to indicate the latest version.  Is it possible to just update the manifest source.extension.vsixmanifest with the xml node code block  <VisualStudio Version="14.0"><Edition>Pro</Edition></VisualStudio>.  This will allow people to install and use the product then move on to the verification process.  This is a hard roadblock for VS 2015.

**Comment by bricelam** [comment]
The `EntityFramework` package and commands appear to be working fine on VS 2017 RC. @divega was there anything in particular that we needed to test?

**Comment by divega** [comment]
@bricelam There isn't anything specific that I expect to be broken at this stage. The main concern is that changes in VS 2017 (e.g. removals of components from the GAC and the new project system) may break our commands. I just hoped we could do some smoke testing on a few combinations of supported project types, languages and EF versions (e.g. EF5 and EF6).

**Comment by bricelam** [comment]
It looks like we work everywhere except in the new ASP.NET Core projects:

> Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

We knew we'd probably have to do some work to enable that, but I couldn't find an issue tracking it.

**Comment by divega** [comment]
@bricelam ok, I didn't know :smile: I guess we need a new issue. Curious, is this ASP.NET Core with the new project system but targeting .NET Framework? Is there any other way to hit this?

**Comment by bricelam** [comment]
You can probably also hit it if you manually edit a new .NET Standard Class Library project to target .NET Framework too/instead.

**Comment by divega** [comment]
Ok, that is what I thought. I don't  understanding what the error is about but in principle I would treat this as a bug in the new project system, since it is supposed to be highly compatible. Thoughts?

**Comment by bricelam** [comment]
For this particular error yes, we can file a bug on them.

In general however, we're probably going to need some new code to handle these types of projects (like [we do in EFCore](https://github.com/aspnet/EntityFramework.Tools/blob/feature/msbuild/src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1#L847-L850)). Fixing dotnet/roslyn-project-system#755 will also help minimize the changes we need to make here.

The project file extension (`.csproj`) and, to some extent, the file format happen to be the same, but the actual VS project system looks and behaves differently. I think under the covers, they're both CPS now, but they end up loading a different set of extensions on top of CPS.

**Comment by bricelam** [comment]
A goal of the "old" (existing) project types (e.g. UWP, WPF, WinForms, ASP.NET, etc.) was to preserve as much behavior as possible, but I'm not sure that was ever a goal with the new (.NET Core, ASP.NET Core, etc.) project types.

**Comment by bricelam** [comment]
I think the testing is done. I've file #146 and dotnet/roslyn-project-system#934 to track the issues found.
