### ISSUE TITLE
Memory leak when using EF + Oracle: OracleParameter(s) are not disposed

### ISSUE THREAD

**Issue by Dennis-Petrov** [aspnet/EntityFramework6#580]
Greetings.

Faced with memory leak when using EF + Oracle.
My Windows Service application consumes about 7 GB memory after 1 day of uptime. There's no unusual activity - service just polls database for some data.

Memory dump from production machine looks like this:
![image](https://user-images.githubusercontent.com/5005677/42987745-f00b8088-8c02-11e8-8307-15c44a50f4e3.png)

Analysis shows, that every `OracleConnection` and `OracleCommand` are disposed, but `OracleParameter`s **are not**. Yes, they (Oracle) had implemented `IDisposable` in `OracleParameter`. 

After some googling and EF source code research, think I found the reason:

1. EF creates `DbConnection` and `DbCommand` (Oracle ones in my case) using factory approach.
2. EF executes command and calls `Dispose` for command, **but not for command parameters**, because it doesn't know that particular `DbParameter` implementation is `IDisposable`.
3. Disposing of context disposes connection.
4. Since `OracleParameter.Dispose` had not been called, parameters hold their resources. Looks like they hold references to command and connection.

This confirms my conclusion:

https://blogs.msdn.microsoft.com/asiatech/2013/01/14/case-study-net-memory-leakage-caused-by-un-released-oracle-objects/

The same service works fine with SQL Server and PostgreSQL.

Is it possible to add this workaround before disposing command:

```
            foreach (var parameter in command.Parameters)
            {
                (parameter as IDisposable)?.Dispose();
            }

            command.Parameters.Clear();
            command.Dispose();
```

?

EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.Client/Oracle.ManagedDataAccess.EntityFramework, 12.2.1100
Operating system: Windows 10 
IDE: Visual Studio 2017 15.7.5

**Comment by Dennis-Petrov** [comment]
Ooops. `OracleCommand` **are not** disposed too. But `DbCommand` implements `IDisposable`, at it must be called. What's happening? Does EF ever call `DbCommand.Dispose`?

**Comment by ajcvickers** [comment]
See #639
