### ISSUE TITLE
Navigation property is null, when lazy is enabled

### ISSUE THREAD

**Issue by mynkov** [aspnet/EntityFramework6#584]
When I insert new entity and then get it, value of childEntity is null, but when I clear the context averything is fine. Lazy is enabled. Why is that?

```C#
           var entity = CreateNewEntity();

            entity.ChildEntityId; // some value
            entity.ChildEntity; // null

            _repository.Add(entity); // insert new entity

            _unitOfWork.Save();

            var entity1 = _repository.GetById(entity.Id);
            entity1.ChildEntity; //null ??????????????????????

            _repository.Clear(); // detach all antities in ChangeTracker

            var entity2 = _repository.GetById(entity.Id);
            entity2.ChildEntity; // not null ??????????????????????
````

```C#
        public virtual void Clear()
        {
            Execute(db =>
            {
                var changedEntriesCopy = db.ChangeTracker.Entries()
                    .ToList();
                foreach (var entity in changedEntriesCopy)
                {
                    db.Entry(entity.Entity).State = EntityState.Detached;
                }
            });
        }
```

Assembly: EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by ajcvickers** [comment]
@mynkov Lazy loading requires a proxy instance to work. When EF creates the instance for you, then you get a proxy automatically. I am assuming that CreateNewEntity creates the instance with `new`, which therefore is not a proxy. Instead use the DbSet.Create method to create a proxy instance.

**Comment by mynkov** [comment]
I get entity1 from dbContext, it's created by EF. Trouble is that entity1.ChildEntity (proxy) is null.

**Comment by mynkov** [comment]
And yes, CreateNewEntity creates the instance with new

**Comment by mynkov** [comment]
@ajcvickers could you reopen issue?

**Comment by ajcvickers** [comment]
@mynkov `entity1` is the same instance as `entity`, since `entity` is being tracked so identity resolution resolves the query result as being the same instance. Hence it is not a proxy. If this isn't the case, then please post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by mynkov** [comment]
@ajcvickers  yes, entity1 is the same instancea as entity, but why? Can I disable this caching (not obvious) behavior?

**Comment by ajcvickers** [comment]
@mynkov No way to change it. Either create a proxy to begin with `DbSet.Create`, detach the instance after saving and then query, or consider the two things different units-of-work and use a different context instance for each part.

**Comment by mynkov** [comment]
Ok, I understood. Thank you for help
