### ISSUE TITLE
Unexpected behavior from DbSet<T>.Find() when trying to Find an id that exists in another deriving table

### ISSUE THREAD

**Issue by JoasE** [aspnet/EntityFramework6#598]
## Description

The `DbSet<T>.Find()` method throws an `System.InvalidOperationException` when `Find`'ing a id in a `DbSet<T>` where `T` inherits from a class which has it's own table, and the id exists in another table that inherits from the same class as `T`. This feels like unexpected behavior as the `Find` method should simply return `null`.

I understand this sounds confusing, so please see the partial code listings in the retro seps below.

## Exception

```
Exception message: The specified cast from a materialized 'System.Data.Entity.DynamicProxies.Post_F0E06E764FED1F3C899F46C50BB6323AB653D8519ED1A77CAE62DD032DBA2B42' type to the 'TestWebApp.Models.Comment' type is not valid.
ExceptionType: System.InvalidOperationException
Stack trace: at System.Data.Entity.Core.Common.Internal.Materialization.CodeGenEmitter.CheckedConvert[TSource,TTarget](TSource value)\r\n   at lambda_method(Closure , Shaper )\r\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)\r\n   at lambda_method(Closure , Shaper )\r\n   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)\r\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable`1 sequence)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)\r\n   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)\r\n   at System.Data.Entity.DbSet`1.Find(Object[] keyValues)\r\n   at TestWebApp.Controllers.CommentsController.GetComment(Int32 id) in C:\\Users\\Joas\\source\\repos\\TestWebApp\\TestWebApp\\Controllers\\CommentsController.cs:line 29\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

#### Steps

First create a post by performing a POST to /api/posts with `{}` as json content.
Then create a comment by performing a POST to /api/comments with `{"PostId": 1}` as json content.

The comment will have an id of 2, because the comments and posts share the same id

Then try to GET a comment with the id of the just created post: GET /api/comments/1.

This will result in the error.

The `Find` method will look in the likables table and find a comment, then it will try to cast that comment to a post, which is not possible, and throws an exception.

The behavior should be `Find` returning `null`.

#### Partial code listings

For example I am using the idea of a blog in which you can like both posts and comments on those posts.

In that scenario you could design this Model hiarchy
```c#
public abstract class Likable
{
	public int Id { get; set; }

	public virtual List<Like> Likes { get; set; }
}

public class Post : Likable
{
	public string Title { get; set; }

	public string Content { get; set; }

	public virtual List<Comment> Comments { get; set; }
}

public class Comment : Likable
{
	public int PostId { get; set; }

	public virtual Post Post { get; set; }

	public string Content { get; set; }
}

public class Like
{
	/// <summary>
	/// The id of the likable object the like is on
	/// </summary>
	[Key, Column(Order = 0)] 
	public int LikableId { get; set; }

	/// <summary>
	/// The likable object the like is on
	/// </summary>
	public virtual Likable Likable { get; set; }

	[Key, Column(Order = 1)] 
	public int UserId { get; set; }

	public virtual User User { get; set; }
}

public class User
{
	public int Id { get; set; }

	public string Username { get; set; }

	public virtual List<Like> Likes { get; set; }
}
```

Then use Fluent API to give each likable a dedicated table and like that setup proper database table inheritance:

```c#
public class TestWebAppContext : DbContext
{
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        // Give posts and comments dedicated tables.
        modelBuilder.Entity<Post>().ToTable("Posts");
        modelBuilder.Entity<Comment>().ToTable("Comments");

        base.OnModelCreating(modelBuilder);
    }

    public System.Data.Entity.DbSet<Post> Posts { get; set; }
    public System.Data.Entity.DbSet<Comment> Comments { get; set; }
}
```

The database and model hierarchy will now look like this:

![image](https://user-images.githubusercontent.com/32096708/44361566-92e4a680-a4be-11e8-92c6-44c92698f4ff.png)

Then scaffold 2 API controllers for `Post`s and `Comment`s  (As you might notice while scaffolding the controllers, the scaffolder will misunderstand the naming of the dbset properties in the `Context`, you will have to rename the properties).

perform the steps sectioned above to recreate the error.

**For a complete code listing, see above.**

## What about `FirstOrDefault` and `SingleOrDefault`?

If you replace [Line 29](https://github.com/JoasE/ReplicateEF6Error/blob/ef486e064dbd7677724bf7f40bc79aaa52e878df/TestWebApp/Controllers/CommentsController.cs#L29) in the `CommentsController` with `Comment comment = db.Comments.FirstOrDefault(c => c.Id == id);` or `Comment comment = db.Comments.SingleOrDefault(c => c.Id == id);`, the error does not occur.

### Further technical details
EF version: 6.2.0
Database Provider: System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2017 15.7.5

**Comment by ajcvickers** [comment]
@JoasE This was one of those behaviors that we debated a lot back in the day and ultimately went for the option of throwing. In retrospect, that was probably the wrong choice--in EF Core we changed to returning null in these situations. I'll discuss with @divega whether this is something we could change in a future EF6 release--it would technically be a breaking change, but only in a case that currently throws, so it might be acceptable.

As a workaround, you should be able to call Find on the `DbSet<Likable>` which will return either a Comment or a Post, and then check the runtime type to see whether it is the item you were looking for.

**Comment by ajcvickers** [comment]
@JoasE We discussed this, and while we are not planning to make the change to return null, we would consider a well-written community PR to make such a change.
