### ISSUE TITLE
Transactions are auto-committed

### ISSUE THREAD

**Issue by pavlexander** [aspnet/EntityFramework6#603]
I am using Entity Framework code-first approach. I create transactions in the code, and they are never committed. Despite NOT having a commit - some of the transactions end up being saved to the database!

This ticket could be either an issue or a question. I am willing to understand if it's an expected behavior. If it is - then please share some comments on this. Otherwise if it's a bug then you might want to fix it in the next milestone.

### Steps to reproduce
Consider following testcase:

```c#
[TestMethod]
public void Test1()
{
    int invoiceId = 1;

    Parallel.For(0, 30, i =>
    {
        var context1 = new ApplicationDbContext();
        var transaction1 = context1.Database.BeginTransaction();
        var invoice1 = new Invoice()
        {
            InvoiceId = (invoiceId + i).ToString()
        };
        context1.Invoices.Add(invoice1);
        context1.SaveChanges();

        //transaction1.Commit();
    });
}
```

There is no commit done, but, after you run the test several times - you will then see that new records appear in DB. There are total of 30 transactions created. Only 0 to 5 of them will be auto-committed, on average. I couldn't find any reasons why it's happening, so if it's working for you just fine - try increasing a number of transactions to 100 or running test multiple times.

### Fix
A quick for this - is to dispose of DB context using a "using" block, like so:

```c#
[TestMethod]
public void Test2()
{
    int invoiceId = 3350;

    Parallel.For(0, 30, i =>
    {
        using (var context = new ApplicationDbContext())
        {
            var transaction = context.Database.BeginTransaction();
            var invoice = new OracleDatabaseService.Models.Invoice()
            {
                InvoiceId = (invoiceId + i).ToString(),
                ClientId = "3",
                ExternalSystemId = "0"
            };
            context.Invoices.Add(invoice);
            context.SaveChanges();

            //transaction.Commit();
        }
    });
}
```

This works fine, though, I think this should not be a fix, because sometimes you will get exceptions in the code, meaning that destructor will NOT be called and same data might end up in DB. So what I am looking forward to - is a proper fix, which will make sure that transaction is committed once you explicitly wish for it!

### Sources

Following code should help you with issue recreation:

```c#
[System.ComponentModel.DataAnnotations.Schema.Table("Invoice")]
public class Invoice
{
	[Column("INVOICE_ID")]
	[MaxLength(100)]
	public string InvoiceId { get; set; }

	[Required]
	[Column("DATE_CREATED")]
	public DateTime DateCreated { get; set; }

	[Column("DATE_CHANGED")]
	public DateTime? DateChanged { get; set; }
}
```
and

```c#
public class ApplicationDbContext : DbContext
{

	public ApplicationDbContext() : base("ApplicationDbContext")
	{
		this.Configuration.LazyLoadingEnabled = false;
	}

	public DbSet<Invoice> Invoices { get; set; }

	protected override void OnModelCreating(DbModelBuilder modelBuilder)
	{
		Database.SetInitializer<ApplicationDbContext>(null);
		base.OnModelCreating(modelBuilder);

		string connectionSTring = this.Database.Connection.ConnectionString;
		var connectionStringBuilder = new OracleConnectionStringBuilder(connectionSTring);
		string schemaName = connectionStringBuilder.UserID.ToUpper();
		modelBuilder.HasDefaultSchema(schemaName);

		modelBuilder.Entity<Invoice>()
			.HasKey(pc => new { pc.InvoiceId });
	}
}
```

### Further technical details
EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.EntityFramework
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.7.5 Pro

**Comment by ajcvickers** [comment]
@pavlexander Couple of things here. First, is is required that the DbContext is disposed. Note that an exception occurring inside the using statement (or other try/finally construct) will still result in the context instance being disposed.

Second, if the context is not disposed, then typically the DbConnection will not be disposed, which can mean that native resources are not correctly cleaned up. It seems possible from your example that this results in something going wrong in the Oracle ADO.NET provider, which then causes the transaction to be committed. You would need to follow up with Oracle on this since this is in their code, not EF or ADO.NET.
