### ISSUE TITLE
Issues with schemas

### ISSUE THREAD

**Issue by pavlexander** [aspnet/EntityFramework6#606]
This ticket is a summary of many issues that I have faced while working with EF code-fist approach. All issues are applicable exclusively in scope of Oracle managed data access provider and not guaranteed to work with other providers (I haven't tested). In order to see all issues for yourself - you will have to go through all processes as I did.

#### Solution structure:
1. project - Class library - .net Framework 4.6.1 - name "DatabaseProject"
2. project - Unit test project - .net Framework 4.6.1 - name "UnitTests" (references project 1)

#### NuGet packages (for each project):
1. Oracle.ManagedDataAccess.EntityFramework 12.2.1100
2. EntityFramework 6.2.0

#### Connection string (for each project, see App.config):
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="ApplicationDbContext" providerName="Oracle.ManagedDataAccess.Client" connectionString="User Id=efbugstest;Password=1;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=xe)))"/>
  </connectionStrings>
</configuration>
```

Some code omitted for brevity

#### Oracle user/schema creation script and giving grants:
```sql
create user efbugstest identified by 1;
 
grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK,
  CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM,
  CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE,
  CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE
  to efbugstest;
```

I am using Oracle 11g Express on Windows 10. Run above commands from "system" user to create "efbugstest" user.

#### Model (project: DatabaseProject)

```C#
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DatabaseProject.Models
{
    [Table("Invoice")]
    public class Invoice
    {
        [Column("INVOICE_ID")]
        public int InvoiceId { get; set; }

        [Required]
        [Column("DATE_CREATED")]
        public DateTime DateCreated { get; set; }

        [Column("DATE_CHANGED")]
        public DateTime? DateChanged { get; set; }
    }
}
```

#### Context (project: DatabaseProject)

```C#
namespace DatabaseProject
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext() : base("ApplicationDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }

        public DbSet<Invoice> Invoices { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<ApplicationDbContext>(null);
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Invoice>()
                .HasKey(pc => new { pc.InvoiceId });
        }
    }
}
```

#### Test (project: UnitTests)

```C#
using System.Linq;
using DatabaseProject;
using DatabaseProject.Models;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTests
{
    [TestClass]
    public class InvoiceTests
    {
        [TestMethod]
        public void Test_AddInvoice()
        {
            var context = new ApplicationDbContext();

            Invoice inv = context.Invoices
                .OrderByDescending(o => o.InvoiceId)
                .FirstOrDefault();

            int nextId = 0;
            if (inv != null)
                nextId = inv.InvoiceId + 1;

            context.Invoices.Add(
                new Invoice() { InvoiceId = nextId }
                );

            context.SaveChanges();
        }
    }
}
```

### Step 2. Enabling migrations

Set DatabaseProject as default and run:

```
PM> enable-migrations -StartupProject DatabaseProject -Force
Checking if the context targets an existing database...
Code First Migrations enabled for project DatabaseProject.
```

### Step 3. Creating new migration (Issue 1)

Run:

```
PM> add-migration InitialCreate -StartupProject DatabaseProject
Scaffolding migration 'InitialCreate'.
The Designer Code for this migration file includes a snapshot of your current Code First model. This snapshot is used to calculate the changes to your model when you scaffold the next migration. If you make additional changes to your model that you want to include in this migration, then you can re-scaffold it by running 'Add-Migration InitialCreate' again.
```

The first issue is that schema name is defaulted to ```dbo```. If you worked with oracle then you will now that ```dbo``` is something very specific to MS SQL server and so this migration will fail:

```C#
public override void Up()
{
	CreateTable(
		"dbo.Invoice",
		c => new
			{
				INVOICE_ID = c.Decimal(nullable: false, precision: 10, scale: 0, identity: true),
				DATE_CREATED = c.DateTime(nullable: false),
				DATE_CHANGED = c.DateTime(),
			})
		.PrimaryKey(t => t.INVOICE_ID);
	
}

public override void Down()
{
	DropTable("dbo.Invoice");
}
```

Expected: no schema specified - no schema in migration file
Actual: schema defaulted to ```dbo```

We can further confirm SQL by running:

```
PM> update-database -StartupProject DatabaseProject -Script
Applying explicit migrations: [201808241401052_InitialCreate].
Applying explicit migration: 201808241401052_InitialCreate.
```

```sql
create table "dbo"."Invoice"
create table "dbo"."__MigrationHistory"
```
Some code omitted for brevity.

**Note 1: ```Invoice``` and ```__MigrationHistory``` table same schema is used.**

### Step 4. Setting default schema (Issue 2)
Now, since we know that ```dbo``` is a no-go for us (migration will fail) - we must remove old migration file and change context to following:

```C#
 protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<ApplicationDbContext>(null);
            base.OnModelCreating(modelBuilder);
            
            string connectionSTring = this.Database.Connection.ConnectionString;
            var connectionStringBuilder = new OracleConnectionStringBuilder(connectionSTring);
            string schemaName = connectionStringBuilder.UserID;//.ToUpper();
            modelBuilder.HasDefaultSchema(schemaName);
            
            modelBuilder.Entity<Invoice>()
                .HasKey(pc => new { pc.InvoiceId });
        }
```

This will take schema name from use that we are using to connect to DB. If we now create migrations - they will look like this:

```C#
public override void Up()
        {
            CreateTable(
                "efbugstest.Invoice",
                c => new
                    {
                        INVOICE_ID = c.Decimal(nullable: false, precision: 10, scale: 0, identity: true),
                        DATE_CREATED = c.DateTime(nullable: false),
                        DATE_CHANGED = c.DateTime(),
                    })
                .PrimaryKey(t => t.INVOICE_ID);
            
        }
        
        public override void Down()
        {
            DropTable("efbugstest.Invoice");
        }
```

and

```sql
create table "efbugstest"."Invoice"
create table "efbugstest"."__MigrationHistory"
```

And if we now try to run this migration we will then face an issue:

```
PM> update-database -StartupProject DatabaseProject -Verbose
Using StartUp project 'DatabaseProject'.
Using NuGet project 'DatabaseProject'.
...
ORA-01918: user 'efbugstest' does not exist
```

For some reason lowercase schema name will not work. So for this to work you should re-create the migration with schema that has all-capital letters in it. I.e. change this like:

```C#
string schemaName = connectionStringBuilder.UserID.ToUpper();
```

**Note 2: Run Unit test to verify that our context is working. This is very important step.**

**Note 3: another important step - if we run update command 2 times - EF will notice existing migration:***
```
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
No pending explicit migrations.
Running Seed method.
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
No pending explicit migrations.
Running Seed method.
```

To reverse a migration we run:

```
PM> update-database -target:0 -StartupProject DatabaseProject -Force
Reverting migrations: [201808241412275_InitialCreate].
Reverting explicit migration: 201808241412275_InitialCreate.
```

### Step 5. Removing schema from migrations script - Attempt 1 (issue 3)
Ideally we don't want migration scripts to contain any schema information. because on Prod/Dev/QA we should be able to use different schema names. This section is my first attempt to remove the schema name from scripts.

If we modify context as this:

```C#
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	Database.SetInitializer<ApplicationDbContext>(null);
	base.OnModelCreating(modelBuilder);


	modelBuilder.HasDefaultSchema(string.Empty);

	modelBuilder.Entity<Invoice>()
		.HasKey(pc => new { pc.InvoiceId });
}
```

The migration script result will be following (remove old file before that):

```C#
public override void Up()
        {
            CreateTable(
                "Invoice",
                c => new
                    {
                        INVOICE_ID = c.Decimal(nullable: false, precision: 10, scale: 0, identity: true),
                        DATE_CREATED = c.DateTime(nullable: false),
                        DATE_CHANGED = c.DateTime(),
                    })
                .PrimaryKey(t => t.INVOICE_ID);
            
        }
        
        public override void Down()
        {
            DropTable("Invoice");
        }
```

This looks good, but if we now try to run migration we will see:

```
PM> update-database -StartupProject DatabaseProject -Verbose
Using StartUp project 'DatabaseProject'.
Using NuGet project 'DatabaseProject'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: '' (DataSource: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=xe))), Provider: Oracle.ManagedDataAccess.Client, Origin: Configuration).
Applying explicit migrations: [201808241430056_InitialCreate].
Applying explicit migration: 201808241430056_InitialCreate.
System.ArgumentNullException: Value cannot be null.
Parameter name: seqOwner
   at Oracle.ManagedDataAccess.EntityFramework.EntityUtils.CheckArgumentNull[T](T value, String parameterName)
   at Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.GenerateSequenceCreate(String seqOwner, String seqName)
   at Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.Generate(CreateTableOperation createTableOperation)
   at CallSite.Target(Closure , CallSite , OracleMigrationSqlGenerator , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.<GenerateStatements>b__2(Object op)
   at Oracle.ManagedDataAccess.EntityFramework.EntityUtils.Each[T](IEnumerable`1 ts, Action`1 action)
   at Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.GenerateStatements(IEnumerable`1 migrationOperations)
   at Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator.Generate(IEnumerable`1 migrationOperations, String providerManifestToken)
   at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClasse.<Update>b__d()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()
Value cannot be null.
Parameter name: seqOwner
```

To fix this issue we must tell EF to avoid creating sequence:

```C#
modelBuilder.Entity<Invoice>().Property(p => p.InvoiceId).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
```

### Step 6. Removing schema from migrations script - Attempt 2 (issue 4)
So our previous step fixed the issue with the sequence.
Now we can generate an SQL script:

```PM> update-database -StartupProject DatabaseProject -Script```

result:

```sql
create table "Invoice"
create table "dbo"."__MigrationHistory"
```

**Expected:** when schema is set - then it's set for all tables. (see ```Note 1```)
**Actual:** When ANY schema name is present - then it is set for all tables. If schema name is an empty string, then for it is NOT being set for ```__MigrationHistory``` table.

What's with this duality?

### Step 7. Removing schema from migrations script - Attempt 3 (issue 5)
This paragraph is a continuation of previous issue. After googling I have found info that migrations table is using a separate context (though, it's not clear now why was this table then affected by my previous code?).

Anyway, we can override default history context by creating a couple of new classes:

```C#
using System;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Migrations.History;

namespace DatabaseProject
{
    public class CustomHistoryContext : HistoryContext
    {
        public CustomHistoryContext(DbConnection dbConnection, string defaultSchema)
            : base(dbConnection, defaultSchema)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasDefaultSchema(string.Empty);
        }
    }
    
    public class CustomHistoryConfiguration : DbConfiguration
    {
        public CustomHistoryConfiguration()
        {
            this.SetHistoryContext("Oracle.ManagedDataAccess.Client",
                (connection, defaultSchema) => new CustomHistoryContext(connection, String.Empty));
        }
    }
}
```

According to my expectations - code above should get rid of ```dbo``` schema name in front of ```__MigrationHistory``` table. If we check SQL script now - it will look gorgeous (as needed):

```sql
create table "Invoice"
create table "__MigrationHistory"
insert into "__MigrationHistory"("MigrationId", "ContextKey", "Model", "ProductVersion")
```

Looks good. Let's run it (you should have disposed of all previous migrations at this point):

```
PM> update-database -StartupProject DatabaseProject -Verbose
Using StartUp project 'DatabaseProject'.
Using NuGet project 'DatabaseProject'.
...
Running Seed method.
```

Great! New tables created. Now let's run this command again. Remember ```Note 3```? No issues before.

```
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201808241434349_InitialCreate].
Applying explicit migration: 201808241434349_InitialCreate.
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00955: name is already used by an existing object
...
ORA-00955: name is already used by an existing object
```

Guess what happened? Entity Framework did NOT notice an existing migration. Which means that every time from now on - migration will be run over and over again. Our original issue with hard-schema-name-binding was resolved (no schemas are mentioned in SQL), but it raised yet another issue.

**Expected:** migrations are detected on repetitive runs
**Actual** migrations are not detected on repetitive runs

To fix the issue you must now manually run:

```sql
DROP TABLE "__MigrationHistory" CASCADE CONSTRAINTS;
DROP TABLE "Invoice" CASCADE CONSTRAINTS;
```

### Step 8. Removing schema from migrations script - Attempt 4 (issue 6)
Luckily for us - there seems to be another way of overriding default history context

1. step - remove ```CustomHistoryConfiguration``` from previous step
2. step - modify ```Configuration.cs``` file as following

```C#
internal sealed class Configuration : DbMigrationsConfiguration<DatabaseProject.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            SetHistoryContextFactory("Oracle.ManagedDataAccess.Client", (c, s) => new CustomHistoryContext(c, s));
        }

        protected override void Seed(DatabaseProject.ApplicationDbContext context)
        {
        }
    }
```

If we now create SQL script - it will be exactly the same as in our previous try:

```sql
create table "Invoice"
create table "__MigrationHistory"
insert into "__MigrationHistory"("MigrationId", "ContextKey", "Model", "ProductVersion")
```

Looks good. Now, let's try running migration.

```
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201808241456061_InitialCreate].
Applying explicit migration: 201808241456061_InitialCreate.
Running Seed method.
```

and once more (see ```Note 3```):

```
PM> update-database -StartupProject DatabaseProject
...
ORA-00955: name is already used by an existing object
```

Same expected and actual results as in previous step:

**Expected**: migrations are detected on repetitive runs
**Actual**: migrations are not detected on repetitive runs

To tell you the truth - I am a bit surprise to see that it failed at this point.. The last time I was running it - I had no issues running migration for the second/third-time from under DatabaseProject scope. However, there was another issue (see ```Note 2```) - I was unable to run unit tests, as they were triggering re-running of migrations. So - OK from ```DatabaseProject```, not ok from ```UnitTests``` project. I have failed to recreate the issue, but you can still look into it and check whether the code can work that way..

### Step 9. Fixing previous issue.

Needless to say that if you want to fix issue from previous step - then you MUST set a schema name,

So, add following lines into both applciation DB context and history DB context:

```C#
string connectionSTring = this.Database.Connection.ConnectionString;
var connectionStringBuilder = new OracleConnectionStringBuilder(connectionSTring);
string schemaName = connectionStringBuilder.UserID.ToUpper();
modelBuilder.HasDefaultSchema(schemaName);
```

And then you can safely try running migrations without any issues at all:

```
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201808241456061_InitialCreate].
Applying explicit migration: 201808241456061_InitialCreate.
Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
You can use the Add-Migration command to write the pending model changes to a code-based migration.
```

and

```
PM> update-database -StartupProject DatabaseProject
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
No pending explicit migrations.
Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
You can use the Add-Migration command to write the pending model changes to a code-based migration.
```

So, all good, if schema name is specified.

### Conclusion
At this point I am stuck at having to use the same schema for Prod/QA/Dev/Local environments. This is very unfortunate and I am hoping that at least some of the above mentioned issues will be fixed in next EF releases.

I think that issue 2 with lowercase schema name erroring out could be a valid Oracle DB behavior. About all the rest issues - I think these are valid bugs. Please look into it.

### Further technical details
EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.EntityFramework
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.7.5 Pro

**Comment by ajcvickers** [comment]
@pavlexander It's true that EF6 doesn't handle schemas very well, especially when used with Oracle or other database systems that treat schemas differently than SQL Server. Some of the issues above could potentially be fixed by the Oracle database provider, but I doubt that will cover everything. We have tried to improve this experience from the ground-up in EF Core, where we are attempting to be both a lot less SQL Server-specific and where we don't have the EDM model to add complexity. However, we are not planning to address these things in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW some of this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
