### ISSUE TITLE
EF default project and startup project dependency

### ISSUE THREAD

**Issue by pavlexander** [aspnet/EntityFramework6#607]
Why do we have to set default project in both ```Package Manager Console``` AND also setting ```StartUp project``` in order to be able to run migrations? Aren't these essentially the same thing? Shouldn't just 1 of these options be enough?

To avoid setting switching StartUp project - I am setting ```-StartupProject``` flag in every command.

But it is still necessary that a Default Project is correct EF project, as there will be an error:

```
PM> update-database -StartupProject DatabaseProject -Script
No packages installed.
The EntityFramework package is not installed on project 'ClassLibrary1'.
```

### Further technical details
EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.EntityFramework
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.7.5 Pro

**Comment by ajcvickers** [comment]
@pavlexander These two things are not always the same. Specifically, the default project is where EF will scaffold migrations. The startup project may be a different project and is used when building the Code First model needed to generated a migration.
