### ISSUE TITLE
Unable to create a new database with TransactionContext

### ISSUE THREAD

**Issue by hjb417** [aspnet/EntityFramework6#61]
The below code gives me the error "System.Data.SqlClient.SqlException: Invalid object name 'dbo.__TransactionHistory'." Is this a regression? I'm using EF 6.1.3

```
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.SqlServer;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            new SomeDbContext().Database.Initialize(false);
        }

        public class Person
        {
            public virtual int Id { get; set; }
            public virtual string Name { get; set; }
        }

        public class MyConfiguration : DbConfiguration
        {
            public MyConfiguration()
            {
                SetTransactionHandler(SqlProviderServices.ProviderInvariantName, () => new CommitFailureHandler());
            }
        }


        [DbConfigurationType(typeof(MyConfiguration))]
        public class SomeDbContext : DbContext
        {
            static SomeDbContext()
            {
                Database.SetInitializer<SomeDbContext>(new DropCreateDatabaseAlways<SomeDbContext>());
            }

            public SomeDbContext()
                : base(@"Data Source=.;Initial Catalog=SomeDbContext;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=1;")
            {
            }

            public virtual DbSet<Person> People { get; set; }
        }
    }
}
```

**Comment by rowanmiller** [comment]
Running your code I am able to see that this exception is thrown when there is no `__TransactionHistory` table in the database, but it is then handled within EF. Is the exception actually making its way back up to your code, or do you maybe have first chance exceptions enabled so that the debugger is breaking on the exception even though it is later handled by EF? https://blogs.msdn.microsoft.com/visualstudioalm/2015/01/07/understanding-exceptions-while-debugging-with-visual-studio/

**Comment by hjb417** [comment]
nope. it crashes the console app. It's ok though, I can't use the feature anyway because I found out later that it doesn't work with "User Initiated Transactions" (https://msdn.microsoft.com/en-us/data/dn307226) which is a deal breaker for me.

**Comment by hjb417** [comment]
Oh btw, Thank you so much for your blog post!!!!!! I used your "EF6.1 Get Mapping Between Properties and Columns" to implement bulk inserts using the SqlBulkCopy class.

I needed to insert 1.5MM records and was currently Parallel.ForEach to create a dbcontext and insert 1000 entities. This was causing timeout issues, even after reducing the MaxDegreeOfParallelization to 16. I was hoping the TransactionContext feature would help me by having EF perform the retries.... No go due to the error above.

I got it working using a hack I posted on SO http://stackoverflow.com/questions/39461010/system-data-sqlclient-sqlexception-invalid-object-name-dbo-transactionhistor and then I encountered that it doesn't work when transactions are created by the "user".

I then tried using the ConnectRetryInterval and ConnectRetryCount on the sql connection string... No luck.

So I ended up using your article to get the column mappings between the classes and the DB columns and bulk insert the records.

It also takes much less time and resources because the multithreaded dbcontext insert was CPU intensive and slow for obvious reasons.

**Comment by rowanmiller** [comment]
If at any point you are able to isolate what causes the exception in user code you were seeing then let us know. I was able to get the exception to occur with your code, but not bubbling its way back up into user code.

**Comment by rowanmiller** [comment]
> Oh btw, Thank you so much for your blog post!!!!!! 

You are very welcome 😄

**Comment by divega** [comment]
> I needed to insert 1.5MM records and was currently Parallel.ForEach to create a dbcontext and insert 1000 entities

Not sure if it is related but this comment raised a flag for me. `DbContext` is not thread-safe. If you are doing this concurrently in the same instance anything can happen. This is a shot in the dark, but even if you are using separate instances you may still have multiple instances racing to initialize the database and the transaction context that owns `__TransactionHistory`. In that case it might help to explicitly use a single `DbContext` instance to initialize the database before you start the parallel loop.

**Comment by hjb417** [comment]
The code I posted was a single threaded console app. I used nuget to pull in the latest version of EF6.

**Comment by divega** [comment]
I understood that but as @rowanmiller mentioned the code you posted was not sufficient to repro (there was an exception but it was handled in EF code). I only made my commented in case it helped with your actual code which I assume is different from what you posted.
