### ISSUE TITLE
Setting length of string forces variable-length type

### ISSUE THREAD

**Issue by simonsouth** [aspnet/EntityFramework6#615]
Several properties in my model are most efficiently stored as fixed-length strings, as type `nchar(4)` for instance instead of the usual `nvarchar`. The length I've specified using an attribute:

```c#
[Required, StringLength(4)]
public string TypeCode { get; set; }
```

The fixed-length aspect I'm handling using a custom convention class (following [the documentation](https://docs.microsoft.com/en-ca/ef/ef6/modeling/code-first/conventions/custom#convention-classes)) that calls `ConventionPrimitivePropertyConfiguration.IsFixedLength()` for these fields. However, I've been surprised to discover **this method has no effect when the length of the string is specified by an attribute**, whether by `StringLength` or `MaxLength`&mdash;these fields are always created with type `nvarchar`, not `nchar` as I expected from my code.

The reason seems to be [the `ConventionPrimitivePropertyConfiguration.HasMaxLength()` method](https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/ModelConfiguration/Configuration/Properties/Primitive/ConventionPrimitivePropertyConfiguration.cs#L401-L438), in addition to setting the `MaxLength` value for a property, [_also_ sets its `IsFixedLength` flag to `false`](https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/ModelConfiguration/Configuration/Properties/Primitive/ConventionPrimitivePropertyConfiguration.cs#L430-L433), after which [it cannot be changed](https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/ModelConfiguration/Configuration/Properties/Primitive/ConventionPrimitivePropertyConfiguration.cs#L364-L367). As a result **it is effectively impossible to define a fixed-length string column using attributes** unless an entirely custom attribute is created that sets both properties at once (as suggested in [this StackOverflow answer](https://stackoverflow.com/a/32084264/473305)).

**Is this behaviour intentional?** [The commit that introduced this code](https://github.com/aspnet/EntityFramework6/commit/4415b95af1861d3f52da6cfcc6f6a16aff035264) mentions only that it was done to match the Fluent API, [which it does](https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/ModelConfiguration/Configuration/Properties/Primitive/Api/LengthPropertyConfiguration.cs#L37), but then [there is no explanation available](https://github.com/aspnet/EntityFramework6/commit/1dc675f86d6c22a9f59b1085e07c08bb7c5063c2#diff-a9b4fd0029c77f52b689ab85231288a2) for why it was implemented this way in the first place.

I'd like to change it as I find the behaviour surprising&mdash;the magnitude and "fixed-ness" of a string's length seem to me like two separate attributes that ought to be controllable separately.

### Steps to reproduce
This program demonstrates the problem:

```c#
namespace FixedLengthStringTest
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration.Conventions;
    using System.Linq;

    class TestEntity
    {
        [Key]
        public int Id { get; set; }

        [StringLength(32)]
        public string Name { get; set; }
    }

    class TestContext : DbContext
    {
        public DbSet<TestEntity> TestEntities { get; set; }

        class StringConvention : Convention
        {
            public StringConvention()
            {
                // Make every string-type property fixed-length
                this.Properties<string>()
                    .Where(p =>
                    {
                        Console.WriteLine($"(Configuring property {p.Name})");
                        return true;
                    })
                    .Configure(p => p.IsFixedLength());
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Add(new StringConvention());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                var query = from t in db.TestEntities
                            select t;

                Console.WriteLine("All entities in the database:");
                foreach (var entity in query)
                    Console.WriteLine(entity.Name);

                Console.WriteLine("Press any key to exit...");
                Console.ReadKey();
            }

            // Run with F5 (in Visual Studio), then check the type of the
            // "Name" field created in the database. It will be of type
            // nvarchar and not nchar, even though the StringConvention class
            // above explicitly set its fixed-length property.
            //
            // Deleting the StringLength attribute on the field's definition
            // then dropping the created database and re-running the program
            // causes the field to be created as type nchar, as expected---but
            // without the desired width.
        }
    }
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.1

**Comment by ajcvickers** [comment]
@simonsouth What's happening here is that conventions only override configuration that has not previously been set. So, for example, if IsFixLength is called not in a convention, then it will be set appropriately:
```C#
 public class Blog
{
    public int Id { get; set; }

    [MaxLength(77)]
    public string Name { get; set; }
}

public class SixTwoContext : DbContext
{
    ...
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property(e => e.Name).IsFixedLength();
    }
}
```
Results in this table mapping:
```sql
CREATE TABLE [dbo].[Blogs] (
    [Id] [int] NOT NULL IDENTITY,
    [Name] [nchar](77),
    CONSTRAINT [PK_dbo.Blogs] PRIMARY KEY ([Id])
)
```
So in this case where MaxLength is configuring two facets it is possible to override either of these, but not in a convention.

Changing MaxLength to not configure both does seem to make sense (I don't remember why it configures both) but unfortunately that would be a breaking change that we can't take. If it could be done in a non-ugly, non-breaking way, then I would be receptive, but I don't immediately see how.

One way to work around this issue is to remove the existing MaxLengthAttributeConvention and (effectively) replace it with your own. For example:
```C#
public class Blog
{
    public int Id { get; set; }

    [MaxLength(77)]
    public string Name { get; set; }
}

public class SixTwoContext : DbContext
{
    ...
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.Conventions.Remove<MaxLengthAttributeConvention>();
        modelBuilder.Conventions.Add(new StringConvention());
   }
}

public class StringConvention : Convention
{
    public StringConvention()
    {
        Properties<string>()
            .Where(x => x.GetCustomAttributes(false).OfType<MaxLengthAttribute>().Any())
            .Configure(c =>
            {
                c.IsFixedLength();
                c.HasMaxLength(c.ClrPropertyInfo.GetCustomAttribute<MaxLengthAttribute>().Length);
            });
    }
}
```

**Comment by simonsouth** [comment]
@ajcvickers Thanks for the great response, Arthur. That clears things up for me.

Inspired by the example you posted, I think what I'll do is provide my own custom `StringLengthAttributeConvention` that overrides the default and recognizes string properties with an equal minimum and maximum length as being fixed-length. (This was the first thing I tried and was a little surprised it didn't work out-of-the-box&mdash;surely a string that's expected to always contain a specific number of characters it is by definition fixed-length.)

In case it's helpful to anyone else, with code like the following:

```c#
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.ModelConfiguration.Conventions;

...

protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.Conventions.Remove<StringLengthAttributeConvention>();
    modelBuilder.Conventions.Add(new CustomStringLengthAttributeConvention());
}

/// <summary>
/// Custom convention for <see cref="StringLengthAttribute"/> that recognizes fixed-length fields.
/// </summary>
private class CustomStringLengthAttributeConvention : StringLengthAttributeConvention
{
    /// <inheritdoc/>
    public override void Apply(
        ConventionPrimitivePropertyConfiguration configuration,
        StringLengthAttribute attribute)
    {
        if (attribute.MinimumLength == attribute.MaximumLength)
        {
            configuration.IsFixedLength();
        }

        base.Apply(configuration, attribute);
    }
}
```
I can define a property like this:

```c#
[Required, StringLength(4, MinimumLength = 4)]
public string TypeCode { get; set; }
```

and have the corresponding field created with type `nchar(4)`, as I wanted.
