### ISSUE TITLE
Openning big edxm designer file crash VS 2017

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#616]
From VS Feedback:

Hello,

When Visual Studio 2017 open à very big (for me 116 829 lines) Designer.cs of a EDMX. After somes secondes, VS freeze and close.

**Comment by Ordanche** [comment]
This is a project for reproduce : [CrashEf.zip](https://github.com/aspnet/EntityFramework6/files/2354580/CrashEf.zip)

The way is : 
1.  open the projet in visual studio (I use VS Pro 15.8.2)
2. open the file "Model1.Designer.cs" (yes it's horrible) 
3. Wait some secondes (10 for me)
4. VS Freeze and crash

**Comment by ajcvickers** [comment]
@Ordanche The solution, designer, and cs file all open for me in a few seconds. You might want to try repairing or re-installing VS.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
