### ISSUE TITLE
https://github.com/maddy027/EF6WithCore (Git-repository-to-repro)  system.InvalidOperationException: No connection string named test' could be found in the application config file. at System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel() at System.Data.Entity.Internal.LazyInternalContext.InitializeContext() at System.Data.Entity.Internal.InternalContext.Initialize() at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()

### ISSUE THREAD

**Issue by maddy027** [aspnet/EntityFramework6#622]
I am using EF6 DB first with Asp.net core . when I try to retrieve the details from db using context object , getting error as "System.InvalidOperationException: No connection string named 'test' could be found in the application config file."
And flow is Asp.net core webpai(controller)-> BL->DAL(EDMX).

I have created git repo to repro.  https://github.com/maddy027/EF6WithCore
I have removed the connection string and modifed db name.  Please look into this ASAP.

**Comment by ajcvickers** [comment]
See #271
