### ISSUE TITLE
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

### ISSUE THREAD

**Issue by maddy027** [aspnet/EntityFramework6#623]
Code is available here  https://github.com/maddy027/IssueWithEF6WithCore.git 
when I tried to use EDMX with Asp.net core , getting the below error 
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

VS: 2017 15.8
EF: 6.2 

Team , help me on this ASAP.

**Comment by ajcvickers** [comment]
@maddy027 Are you attempting to use EF6 with .NET Core?

**Comment by maddy027** [comment]
Yes

**Comment by ajcvickers** [comment]
EF6 does not (yet) run on .NET Core--see #271

**Comment by maddy027** [comment]
@ajcvickers but this doc says: https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1

**Comment by maddy027** [comment]
@ajcvickers please remove this doc

**Comment by maddy027** [comment]
@ajcvickers Even I am using ASP.net core with EF 6. I am just doing the steps which are mentioned in the doc and ended up here with exception

**Comment by maddy027** [comment]
@ajcvickers  please read desc (when I tried to use EDMX with Asp.net core , getting the below error) I have mentioned that I am using Asp.net core with EF

**Comment by ajcvickers** [comment]
@maddy027 Then I would suggest to file feedback on that document, using the buttons at the bottom of the doc. This issue tracker is for reporting bugs in EF6, and so far I haven't seen anything that seems to me like a bug.

**Comment by maddy027** [comment]
@ajcvickers  Do I need to open new issue as it is closed here ?

**Comment by furqansafdar** [comment]
@maddy027, did you find any solution to this issue as i am also facing the same exception.

**Comment by maddy027** [comment]
@furqansafdar Yes I am using Ado.net with core
https://social.technet.microsoft.com/wiki/contents/articles/51324.asp-net-core-2-0-crud-operation-with-ado-net.aspx
