### ISSUE TITLE
SqlDataReader and Closed connection time different and logging

### ISSUE THREAD

**Issue by okarpov** [aspnet/EntityFramework6#630]
Time between SqlDataReader/EF executing DataReader and closing connection different from time to time. Here is slow log example:

Closed connection at 9/20/2018 3:58:05 AM -04:00
Opened connection at 9/20/2018 3:58:05 AM -04:00

[GetTimesheet] @Param??

-- @Param??: '????...????' (Type = String, IsNullable = false, Size = 24)

-- Executing at 9/20/2018 3:58:05 AM -04:00
-- Completed in 3 ms with result: SqlDataReader

Closed connection at 9/20/2018 3:58:14 AM -04:00
Opened connection at 9/20/2018 3:58:14 AM -04:00

As you can see Executing time was at 3:58:05, SP was completed in 5 ms but connection was closed at 3:58:14 means SqlDataReader/EF took 9 seconds to close connection and start another one. 
Executing this code 10-20 times gives 4-6 slow executions out of 10.

Here is another fast/normal one:

Closed connection at 9/20/2018 4:39:50 AM -04:00
Opened connection at 9/20/2018 4:39:50 AM -04:00

[GetTimesheet] @Param??

-- @Param??: '????...????' (Type = String, IsNullable = false, Size = 24)

-- Executing at 9/20/2018 4:39:50 AM -04:00
-- Completed in 132 ms with result: SqlDataReader

Closed connection at 9/20/2018 4:39:50 AM -04:00
Opened connection at 9/20/2018 4:39:50 AM -04:00

As you can see this time it took less as 1 second in total. The @Param/@UserModelID param value is always the same.

Is there a way to log what is going on inside/between SqlDataReader and Closing Connection?
Any ideas on what may cause it?

(this code run under shared hosting)

### Steps to reproduce

```c#
using (Models.TTTDbContext dbctx = new Models.TTTDbContext())
{
        ....
        var dtimesheets = dbctx.Database.SqlQuery<Models.tblTimeSheet>("[GetTimesheet] @UserModelID",
                           new System.Data.SqlClient.SqlParameter("@UserModelID", user.ModelID)).ToList();
        ....
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10, Windows Server 2012 & 2016  
IDE: Visual Studio 2017 15.8.4

**Comment by ajcvickers** [comment]
@okarpov The time to execute the stored procedure does not include the time to consume the results. Are you taking account of that?

**Comment by okarpov** [comment]
@ajcvickers I assume it but even so there are still two questions:
- how to log everything between execution and closed connection?
- why same result sets so much vary in time between milliseconds up to seconds?

**Comment by ajcvickers** [comment]
@okarpov For the first question, can you be more specific about what you mean by "log everything"? Do you mean that you think their might be logging events that you're not seeing? Or there should be more events, but there aren't?

With regard to the second question, that's impossible to say from the info above. Your best bet is probably running with a profiler and analyzing the results.

**Comment by okarpov** [comment]
@ajcvickers yes - I mean how to get more details to see where exactly time goes.
More details, more log information, etc.

It is under shared hosting and I can not profile it unless you can suggest any good way to profile it.

**Comment by ajcvickers** [comment]
@okarpov As far as I can tell from what you have posted, you are getting all the log information that is available. EF Core has significantly richer logging, but it's not something we're planning on investing on in EF6.

**Comment by okarpov** [comment]
@ajcvickers so there is no way to extend the log even myself?

**Comment by ajcvickers** [comment]
@okarpov Well you can always write whatever you want to whatever log you've hooked up EF to.

**Comment by okarpov** [comment]
@ajcvickers yes, thought there any predefined guide for it to save time. thank you anyway.
