### ISSUE TITLE
Code first test cases automation, add-migration from command line

### ISSUE THREAD

**Issue by radhikagadde** [aspnet/EntityFramework6#633]
We are trying to automate Code First test cases, but i do not see any command line tool through which we can achieve the same.

Can you suggest any command tool in this regard!

EF version:  EF6 (6.1.1)
Database Provider:  SQLServer
IDE:  Visual Studio 2017 15.5.7
Operating system: (e.g. Windows 10) 

Thanks,
Radhika.

**Comment by ajcvickers** [comment]
The command line tool is called "migrate.exe". It is included with the NuGet package.
