### ISSUE TITLE
New MaxLenght of existing columns does not generate a change script

### ISSUE THREAD

**Issue by michalpipal** [aspnet/EntityFramework6#636]
Hello,

I'm facing a very similar problem like [this one](https://github.com/aspnet/EntityFrameworkCore/issues/3434) mentioned in EF Core project.

When I add the MaxLenght (or StringLenght, I tried both of them) attribute to an existing field and then I add a new migration, no new changes are generated. 

For ex., when I add the attribute to the existing Name field:

```
public class Claim
{   
   [StringLength(100)]
   public string Name { get; private set; }
}
```

EF generates an empty migration:

```
public partial class NvarcharLenghtRestriction : DbMigration
{
   public override void Up()
   {
   }
        
   public override void Down()
   {
   }
}
```

However, when I add a completely new field with the same restrictions, this field has then the correct lenght restriction applied:

```
public class Claim
{
   [StringLength(100)]
   public string NewTestField { get; set; }
   
   [StringLength(100)]
   public string Name { get; private set; }
}
```

```
public partial class NvarcharLenghtRestriction : DbMigration
{
  public override void Up()
  {
     AddColumn("dbo.Claims", "NewTestField", c => c.String(maxLength: 100));
   }
	
   public override void Down()
   {
      DropColumn("dbo.Claims", "NewTestField");
   }
}
```

Could be the problem the same like in EF Core?

Thank you.

**EDIT:**
The same problem is when updating fields by Fluent notation in Context class:

`modelBuilder.Entity<Claim>().Property(o => o.Name).HasMaxLength(100), for ex.;`

EF version: 6.2.0
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.5

**Comment by juchom** [comment]
I'm experiencing the same with EF 6.1.3 & EF 6.2.0.

**Comment by michalpipal** [comment]
@sathyarajv : Thank you for your reply. I tried your demo and it works for me too. My example would have probably some other issue, which is causing the problem. Until I found something more helpful, I'm closing this topic.
