### ISSUE TITLE
nchar and char strings include space padding

### ISSUE THREAD

**Issue by Xaeroxe** [aspnet/EntityFramework6#652]
When string member types in entities are populated from Microsoft SQL server's char and nchar types, if the total string length is less than the length of the data type the padded spaces from the SQL storage are included in the new string.

This is inconvenient as it can cause display issues as well as issues with determining equality of string values.  While this can be resolved with a simple `TrimEnd()` it presents an ease of use wart for this use case.  The end result is that developers feel discouraged from using the char and nchar types in their database, which is unfortunate because if used correctly these types can boost query performance.

I would like to fix this, but I'm not completely certain where to start and was hoping someone could point me in the right direction.

**Comment by ajcvickers** [comment]
This is a behavior of the SqlClient (the ADO.NET provider for SQL Server) and not a behavior of EF directly.

**Comment by Xaeroxe** [comment]
Darn, looks like I better start planning a way to break in to Microsoft source then :P
