### ISSUE TITLE
Is Entity Framework for .NET dead in the water?

### ISSUE THREAD

**Issue by hades-incarnate** [aspnet/EntityFramework6#653]
With all the efforts now moved to EF Core, we would really like to know if this is it in terms of non-Core EF? The list of feature differences between non-Core and Core grows over time, the professional team seems to be only focused on Core and the roadmap hasn't been touched in a year and is inaccurate. Majority of commits seem to be just fixes by 2 guys. In all appearances it looks dead like Linq2SQL is, kept only on artificial support for backward compatibility. So, is EF.NET going to catch up to Core ever or never?

For various reasons, mostly related to stability and compatibility, we are not going to adopt Core (please no fanboi response, this was not a decision made lightly), so we need to know if we should start migrating to a more stable maintained external solution (or away from .net in general, but thats out of scope here). 

Thanks

**Comment by ajcvickers** [comment]
@hades-incarnate The only work planned for EF6 is:
* Make it run on .NET Core for .NET Core 3.0 with the only goal here being to allow people with existing EF6 applications to run them on Core.
* Take good community PRs that add value without impacting stability or bringing breaking changes
* Fix some bugs if they seem serious enough and don't have workarounds

We do not plan to add any new features to EF6. This has been the case for about the last four years now.

It's worth noting that EF Core is not tied to .NET Core. It runs on .NET Framework and other places.

**Comment by hades-incarnate** [comment]
So, Core way or the highway. Nice. Real nice. I never thought I would actually miss Ballmer.
