### ISSUE TITLE
1-to-1 relationship does not throw an exception when dependent entity is null

### ISSUE THREAD

**Issue by randelramirez** [aspnet/EntityFramework6#66]
Steps to reproduce

Model:
```C#
public class Student
{

    public int StudentId { get; set; }
    public string StudentName { get; set; }
    public virtual StudentAddress Address { get; set; }

}
public class StudentAddress
{
    public int StudentId { get; set; }

    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public int Zipcode { get; set; }
    public string State { get; set; }
    public string Country { get; set; }

    public virtual Student Student { get; set; }
}

public class DataContext : DbContext
{
    public DbSet<Student> Student { get; set; }

    public DbSet<StudentAddress> Addresses { get; set; }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        // Configure StudentId as PK for StudentAddress
        modelBuilder.Entity<StudentAddress>()
            .HasKey(e => e.StudentId);

        // Configure StudentId as FK for StudentAddress
        modelBuilder.Entity<Student>()
                    .HasRequired(s => s.Address)
                    .WithRequiredPrincipal(ad => ad.Student);

    }
}
```

Console App.
```C#
class Program
{
    static void Main(string[] args)
    {
        using (var context = new DataContext())
        {
            var student = new Student { StudentName = "sample name" };
            context.Student.Add(student);
            context.SaveChanges();
        }
            Console.ReadKey();
    }
}
```
In the console application, I expect it throw an exception since a Student must have a StudentAddress in order for it be saved, but when I ran the application and checked the database the student entry actually got saved. I might be missing something under the hood...though if I try adding the [Required] attribute on top of the StudentAddress property of the Student class, it throws an exception If I don't supply a StudentAddress for a Student Entity.

http://stackoverflow.com/questions/38533303/entity-framework-1-to-1-relationship-does-not-throw-an-exception-when-dependent

**Comment by ajcvickers** [comment]
@randelramirez EF will always let you insert a new principal (Student in your model) without any dependents regardless of whether the relationship is required or not. A required relationship means that a dependent (Address in your model) cannot be inserted without a corresponding principal. I realize that the way relationships are modeled in EF6 implies something different, but the decision to describe relationships in this way and then behave like this was made many years ago and we cannot change it now.

**Comment by randelramirez** [comment]
Thanks @ajcvickers
