### ISSUE TITLE
Commit yields EntityException with ArgumentNullException if SaveChanges failed

### ISSUE THREAD

**Issue by angularsen** [aspnet/EntityFramework6#667]
`Commit()` on `DbContextTransaction` throws `EntityException` with message `"The underlying provider failed on Commit."` if `SaveChanges()` has previously failed with `DbUpdateException` due to optimistic concurrency. The inner exception is `ArgumentNullException` on parameter `connection`, which is not helpful at all.

I would expect the exception message to describe that the reason is due to the snapshot isolation of the transaction and a concurrent change, similar to how `DbUpdateException` in `SaveChanges()` describes it.

[Docs for DbContextTransaction.Commit](https://msdn.microsoft.com/en-us/library/system.data.entity.dbcontexttransaction.commit(v=vs.113).aspx) does not describe any exceptions.

**Pseudo-code:**
```c#
using (var context = new MyContext())
using (var trans = context.Database.BeginTransaction(System.Data.IsolationLevel.Snapshot))
{
  var person = context.Persons.First();

  // --> At this point, assume another conflicting transaction was committed <--

  person.Name = "gunnar";

  try {  context.SaveChanges(); }
  catch (DbUpdateException) { /* mute it to get to Commit()*/ }

  // Non-descriptive EntityException here
  transaction.Commit();
}
```

**With EntityFramework 6.1.3 and 6.2.0**
```
Exception message: The underlying provider failed on Commit.

at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()   
at UserQuery.Main() in C:\Users\andreasl\AppData\Local\Temp\LINQPad5\_vrdycpcu\query_djbyit.cs:line 118   


InnerException: Value cannot be null.Parameter name: connection

at System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)   
at System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext.WithConnection(DbConnection connection)   
at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Commit(DbTransaction transaction, DbInterceptionContext interceptionContext)   
at System.Data.Entity.Core.EntityClient.EntityTransaction.Commit()
```

### Steps to reproduce
- Run attached script (.linq) in [LINQPad](https://www.linqpad.net/download.aspx) or alternatively run the code in a console app and install EntityFramework 6.1.3 nuget
- By default it targets default instance of SQL Server and will drop/create an `ef_repro` database, change the connection string in line 88 if you want something else

[Sample - EntityFramework Transactions.zip](https://github.com/aspnet/EntityFramework6/files/2607706/Sample.-.EntityFramework.Transactions.zip)

Code is copied here for easier review in GitHub:
```c#
void Main()
{
    Database.SetInitializer(new DropCreateDatabaseAlways<EntityContext>());            
    string connectionString;
    using (var context = new EntityContext())
    {
        context.Database.Initialize(true);
        connectionString = context.Database.Connection.ConnectionString;
    }
    
    using (var conn = new SqlConnection(connectionString))
    using (var cmd = conn.CreateCommand())
    {
        conn.Open();
        Console.WriteLine("Enable snapshot isolation.");
        cmd.CommandText = "ALTER DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION ON";
        cmd.ExecuteNonQuery();
    }
    
    GenerateData();
    Console.WriteLine("Create contexts and transactions.");
    using (var context = new EntityContext())
    using (var trans = context.Database.BeginTransaction(System.Data.IsolationLevel.Snapshot))
    using (var context2 = new EntityContext())
    using (var trans2 = context2.Database.BeginTransaction(System.Data.IsolationLevel.Snapshot))
    {
        Console.WriteLine("Fetch in context #1");
        var list = context.Customers.ToList();

        Console.WriteLine("Fetch in context #2");
        var list2 = context2.Customers.ToList();
        
        Console.WriteLine("SaveChanges and commit in context #1"); 
        list[0].Description = "Modified description";
        context.SaveChanges();
        trans.Commit();
        
        Console.WriteLine("SaveChanges in context #2 - this should blow up!");
        list2[0].Description = "Also modified description";
        try 
        {
            context2.SaveChanges(); 
        }
        catch (Exception e)
        {
            Console.WriteLine($"It did: {e.GetType().Name} - {e.Message}");
            Console.WriteLine("Let's mute the exception and see what happens when committing transaction #2.");
        }

        Console.WriteLine("Committing transaction #2 - this should give ArgumentNullException about parameter 'connection'.");
        try
        {
            trans2.Commit();
        }
        catch (ArgumentNullException e) 
        {
            Console.WriteLine("Yup! Isn't that weird?");
            throw;
        }
    }
    Console.WriteLine("Dispose contexts and transactions.");

    Console.WriteLine("Results:");
    using (var context = new EntityContext())
    {
        var list = context.Customers.ToList();
        list.Dump();
    }
}

// Define other methods and classes here
public static void GenerateData()
{
    Console.WriteLine("Generate data.");
    using (var context = new EntityContext())
    {
        context.Customers.Add(new Customer() { Name = "Customer_A", Description = "Description", IsActive = true, LastLogin = new DateTime(2010, 1, 1) });
        context.Customers.Add(new Customer() { Name = "Customer_B", Description = "Description", IsActive = true, LastLogin = new DateTime(2010, 1, 1) });
        context.Customers.Add(new Customer() { Name = "Customer_C", Description = "Description", IsActive = true, LastLogin = DateTime.Now });

        context.SaveChanges();
    }
    Console.WriteLine("Generate data OK.");
}

public class EntityContext : DbContext
{
    public EntityContext() : base(@"Database=ef_repro; Trusted_Connection=True")
    {
    }

    public DbSet<Customer> Customers { get; set; }
}


public class Customer
{
    public int CustomerID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public DateTime LastLogin { get; set; }
    public Boolean IsActive { get; set; }
}
```

### Further technical details
EF version: 6.1.3 and 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: LINQPad 5 or Visual Studio 2017 15.8

**Comment by ajcvickers** [comment]
@angularsen Question: what is the the reason for still calling `Commit` when an error in the transaction has already been reported?

**Comment by angularsen** [comment]
@ajcvickers It was a flaw in the code, but it was difficult to pinpoint the root cause for why we were getting `ArgumentException` on `transaction.Commit()`  with an inner exception of `ArgumentNullException` on an internal `connection` parameter. 

The transaction commit was higher up in the call stack so it was not trivial to see the connection with the trapped exception on `dbContext.SaveChanges()` further down the callstack. First when we enabled break on first-chance exceptions did we see what was going on.

So what I ask for here is a more descriptive exception in this edge case scenario.
Did that help answer your question?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
