### ISSUE TITLE
SnapshotChangeTrackingStrategy With Oracle Database

### ISSUE THREAD

**Issue by davidrevoledo** [aspnet/EntityFramework6#672]
Entity Framework connected with oracle is failing with a lot of queries / commit
```
Exception message:
Message: Object reference not set to an instance of an object.

Stack trace:
```
System.Data.Entity.Core.Objects.Internal.SnapshotChangeTrackingStrategy.SetCurrentValue(EntityEntry entry, StateManagerMemberMetadata member, Int32 ordinal, Object target, Object value):0
System.Data.Entity.Core.Objects.Internal.EntityWrapper`1.SetCurrentValue(EntityEntry entry, StateManagerMemberMetadata member, Int32 ordinal, Object target, Object value):0
System.Data.Entity.Core.Objects.DataClasses.EntityReference.UpdateForeignKeyValues(IEntityWrapper dependentEntity, IEntityWrapper principalEntity, Dictionary`2 changedFKs, Boolean forceChange):441
System.Data.Entity.Core.Objects.DataClasses.EntityReference.UpdateDependentEndForeignKey(RelatedEnd targetRelatedEnd, Boolean forceForeignKeyChanges):9
System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges):229
System.Data.Entity.Core.Objects.ObjectStateManager.AddEntityToCollectionOrReference(MergeOption mergeOption, IEntityWrapper wrappedSource, AssociationEndMember sourceMember, IEntityWrapper wrappedTarget, AssociationEndMember targetMember, Boolean setIsLoaded, Boolean relationshipAlreadyExists, Boolean inKeyEntryPromotion):242
System.Data.Entity.Core.Objects.ObjectStateManager.UpdateRelationships(ObjectContext context, MergeOption mergeOption, AssociationSet associationSet, AssociationEndMember sourceMember, IEntityWrapper wrappedSource, AssociationEndMember targetMember, IList targets, Boolean setIsLoaded):157
System.Data.Entity.Core.Common.Internal.Materialization.Shaper.FullSpanAction[TTargetEntity](IEntityWrapper wrappedSource, IList`1 spannedEntities, AssociationEndMember targetMember):49
System.Data.Entity.Core.Common.Internal.Materialization.Shaper+<>c__DisplayClass2`1.<HandleFullSpanCollection>b__0(Shaper state, List`1 spannedEntities):0
System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ResetCollection(Shaper shaper):8
System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1+RowNestedResultEnumerator.MaterializeRow():69
System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1+RowNestedResultEnumerator.MoveNext():45
System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1+ObjectQueryNestedEnumerator.TryReadToNextElement():19
System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1+ObjectQueryNestedEnumerator.ReadElement():0
System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1+ObjectQueryNestedEnumerator.MoveNext():35
System.Data.Entity.Internal.LazyEnumerator`1.MoveNext():43
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection):119
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source):14
 
### Steps to reproduce
A simple dbcontext connected with oracle doing a table reading  using oracle.manageddataaccess.client

```c#
### Further technical details
EF version:  6.1.2
Database Provider: (oracle.manageddataaccess.client)
Operating system: Windows Server) 
IDE: (e.g. Visual Studio 2017 15.6)

Thanks in advance

**Comment by ajcvickers** [comment]
This looks like an issue with the Oracle provider; please report it to Oracle. Also, it would be great if you could include full code to reproduce what you are seeing when you report it to them.
