### ISSUE TITLE
New Version release

### ISSUE THREAD

**Issue by ericnewton76** [aspnet/EntityFramework6#676]
Looking for a timeline of a new version release for Entity Framework.  

Looks like enough issues and pull requests here for a minor version bump to 6.3.0

**Comment by ajcvickers** [comment]
Current plan is to release 6.3 as part of the .NET Core 3 wave.

**Comment by divega** [comment]
@weitzhandler it will support .NET Framework as well as .NET Core 3.0. See https://github.com/aspnet/EntityFramework6/issues/271.
