### ISSUE TITLE
Entity framework resets navigation property to previous state 

### ISSUE THREAD

**Issue by pawel31bielsko** [aspnet/EntityFramework6#70]
In context I have two navigation properties Collection and Nullable property to the same Entity.
Take a look at class diagram:
![class diagram](https://cloud.githubusercontent.com/assets/5707048/18715924/3ec47432-801b-11e6-96ef-2aca435aa496.png)

When executing code:
```C#
 using (var ctx = new RequestContext())
            {
                var request = ctx.Requets.FirstOrDefault(x => x.Name == "test");
                //request.ProjectManager is Bob (Email = "Bob@test.com" );
                //request.ProjectManagerDeputies is collection with Alice (Email ==  "Alice@test.com");

                request.ProjectManager = ctx.Employees.FirstOrDefault(x => x.Email == "Alice@test.com");
                
                foreach (var toDelete in request.ProjectManagerDeputies.ToList())
                    request.ProjectManagerDeputies.Remove(toDelete);

                var bob = ctx.Employees.FirstOrDefault(x => x.Email == "Bob@test.com");
                request.ProjectManagerDeputies.Add(bob);

                Debug.Assert(request.ProjectManager.Email == "Alice@test.com");
                Debug.Assert(request.ProjectManagerDeputies.First().Email == "Bob@test.com");

                ctx.SaveChanges();
                
            }
```

First assertion fails. 

Moreover if you use debugger in visual studio sometimes it will pass test. If you won't it will fail every time. Workaround for issue is  to call DetectChanges() after line:
`request.ProjectManager = ctx.Employees.FirstOrDefault(x => x.Email == "Alice@test.com");`

Please take a look at attached project to observe the bug. 

[EfTest.zip](https://github.com/aspnet/EntityFramework6/files/485297/EfTest.zip)

**Comment by ajcvickers** [comment]
@pawel31bielsko The problem is that EF does not have any chance to detect that request.ProjectManager has been set to Alice before the query for Bob takes place. EF therefore does the query for Bob and based on the the info it has it fixes up the navigation properties for Bob, which includes setting request.ProjectManager to point to the newly loaded entity. The workaround that you state isn't really a workaround, but rather the correct way to tell EF that a change has been made and it needs to be detected so that future operations will behave accordingly.

**Comment by pawel31bielsko** [comment]
I'm not getting something. Request is loaded as dynamic proxy, it has virtual navigation property ProjectManager. I would expect that if you assign value to ProjectManager it will track this change as the dynamic proxy is aware that ProjectManager was changed using override set accessor. 

If I'm missing something please point me to resource where this behavior is explained.

**Comment by ajcvickers** [comment]
@pawel31bielsko That will happen if you are using change tracking proxies, but does not happen when using lazy loading proxies. In your solution the entities are lazy loading proxies. See 
- https://msdn.microsoft.com/en-us/library/dd468057(v=vs.100).aspx
- https://blog.oneunicorn.com/2011/12/05/entity-types-supported-by-the-entity-framework/ 
- https://blog.oneunicorn.com/2011/12/05/should-you-use-entity-framework-change-tracking-proxies/
