### ISSUE TITLE
Can you tell me what I just need to do to get Intellisense to ID the ObjectQuery class?

### ISSUE THREAD

**Issue by LJ9999** [aspnet/EntityFramework6#701]
Describe what is not working as expected.

Intellisense redlines ObjectQuery class usage and it is impossible to locate this class esp. since Microsoft rearranged namespaces from EF5 to EF6.

```
![screen shot 2019-01-27 at 12 52 57 am](https://user-images.githubusercontent.com/45138874/51797697-fee5dc00-21cd-11e9-8b35-e207ae68e2b7.png)
```

### Steps to reproduce
See attachment.

### Further technical details
EF version: 6
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2017 15.9.3

**Comment by ajcvickers** [comment]
See https://docs.microsoft.com/en-us/ef/ef6/what-is-new/upgrading-to-ef6
