### ISSUE TITLE
Call ObjectContext.ExecuteFunction asynchronously

### ISSUE THREAD

**Issue by FSou1** [aspnet/EntityFramework6#712]
Greetings,

I'm wondering whether there is a chance to call the `ExecuteFunction` asynchronously.

There is a sample of calling the method with the usage of `IDbAsyncEnumerable<T>`:

```c#
IDbAsyncEnumerable<SomeResult> enumerable = this.ExecuteFunction<SomeResult>("sp_myproc", p1, p2, p3) as IDbAsyncEnumerable<SomeResult>;
```

But, unfortunately, my stored procedure does not return anything and throws the following exception:

```c#
The stored procedure or function 'sp_myproc' does not have a return type. ExecuteFunction only supports stored procedures and functions that have a return type.
```

So, is there any workaround or a specific method for addressing the current need?

### Steps to reproduce

```c#
List<ObjectParameter> parameters = new List<ObjectParameter>();
IDbAsyncEnumerable<T> enumerable = objectContext.ExecuteFunction<T>(spName, parameters.ToArray());
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.5

**Comment by FSou1** [comment]
Any thoughts?

**Comment by ajcvickers** [comment]
@FSou1 Look at [ExecuteStoreCommandAsync](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.core.objects.objectcontext.executestorecommandasync?view=entity-framework-6.2.0)
