### ISSUE TITLE
Multiple Database Providers with single migration set

### ISSUE THREAD

**Issue by GitHubAre** [aspnet/EntityFramework6#714]
Hello!
Is it possible to maintain **single EF Migration set for multiple DB Providers**?
I have tried it with **SQL Server** and **Oracle** - two database contexts. Application is not expected to be running against two DB Providers at the same time, its based on what flavor the customer prefers (some prefer Oracle, while others might have SQL Server).

I am trying to achieve running **single Add-Migration** (f.e. against SQL Server configuration) and tweaking some of incompatible code with Oracle within generated migration with if-else statements so that I have only one .cs file.

Searching so far has only led me to solutions where each **DbContext** has its own **Migration** folder and each change in code is reflected by executing **Add-Migration** twice - once for each **DbContext**.

I have compared generated migration and when I generate the migration the code does not match in certain data types, f.e. for **SQL server** generated migration snippet was:

```
            CreateTable(
                "QA_CALCQUEUE",
                c => new
                    {
                        CALCREQID = c.Long(nullable: false, identity: true),
                        ACTIONCODE = c.String(maxLength: 32),
                        ACTIONTEXT = c.String(maxLength: 2048),
                        CALCQAMEASID = c.Int(nullable: false),
```
**For Oracle:**
```
            CreateTable(
                "QA_CALCQUEUE",
                c => new
                    {
                        CALCREQID = c.Decimal(nullable: false, precision: 19, scale: 0, identity: true),
                        ACTIONCODE = c.String(maxLength: 32),
                        ACTIONTEXT = c.String(maxLength: 2048),
                        CALCQAMEASID = c.Decimal(nullable: false, precision: 10, scale: 0),
```

I know that data type mapping can differ from provider to provider, but is there some recommended way how to generalize it?

### Further technical details
EF version: 6.2.0

**Comment by ajcvickers** [comment]
@GitHubAre Short answer is no. The migrations are inherently database specific (as indeed is the EF6 model when built) so the only option I am aware of is to somehow manage two different sets of migrations.
