### ISSUE TITLE
Can't query DateTime column

### ISSUE THREAD

**Issue by DWAK-HECLA** [aspnet/EntityFramework6#717]
I'm writing software that integrates with a 3rd part database (Sql Server) - thus structure changes are not possible.  I'm using EF 6.2.0 for this.

The Invoice table has a column named "DateTime"  (horrible, I know.. but it is what it is).  EF is working perfectly for all columns except this one.

The Invoices table looks, in part, like this:  
**Invoices**  
[Invoice_Number]  PK  BIGINT  NOT NULL  IDENTITY  
[DateTime]  DateTime  NOT NULL  
[CustNum]  NVARCHAR(12)  NOT NULL  
[Grand_Total]  MONEY  NOT NULL
[Amt_Tendered]  MONEY  NULL
[Amt_Change]  MONEY  NULL

and my model looks like:
```
<Table("Invoices")>
	Public Class Invoice

		<Key>
		<Column("Invoice_Number")>
		Public Property IntegrationKey As Int64

		<Column("CustNum")>
		Public Property CustomerKey As String = String.Empty

		<Column("DateTime")>
		Public ReadOnly Property CreatedTime As DateTime

		<Column("Grand_Total")>
		Public Property Price As Decimal = Decimal.MaxValue

		<Column("Amt_Tendered")>
		Public Property Payment As Decimal = 0

		<Column("Amt_Change")>
		Public Property PaymentChange As Decimal = 0
	End Class
```

And my EF query:  
```
    Dim items As List(Of Invoice) = database.Invoices.ToList()
```

The generated query looks like:
```
SELECT
    [c].[Invoice_Number] AS [Invoice_Number], 
    [c].[CustNum] AS [CustNum], 
    [c].[Grand_Total] AS [Grand_Total], 
    [c].[Amt_Tendered] AS [Amt_Tendered], 
    [c].[Amt_Change] AS [Amt_Change]
    FROM [dbo].[Invoices] AS [c]
```
You can see that the [DateTime] field is missing from the query.

Is this because the column is named the same as a data type?  Any thoughts on how I can make this work, preferably without writing SQL.. I'd like to use the standard method with Entity classes and DbSets.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.7

**Comment by DWAK-HECLA** [comment]
Even doing the query via SQL doesn't get me the correct results.  All the Invoice.CreatedTime properties are set to DateTime.MinValue.

```
Dim q As DbSqlQuery(Of Invoice) = database.Invoices.SqlQuery(
				"SELECT TOP (200) 
    [c].[Invoice_Number] AS [IntegrationKey], 
	[c].[DateTime] AS [CreatedTime],
    [c].[CustNum] AS [CustomerKey], 
    [c].[Grand_Total] AS [Price], 
    [c].[Amt_Tendered] AS [Payment], 
    [c].[Amt_Change] AS [PaymentChange]
    FROM [dbo].[Invoices] AS [c]"
			)
			_tempData = q.ToList
```

**Comment by ajcvickers** [comment]
@DWAK-HECLA The property will not be mapped by convention because it is read-only. EF6 doesn't support read-only properties, but giving it a private setter should make it work.
