### ISSUE TITLE
Use own build on Azure App Service

### ISSUE THREAD

**Issue by chrfin** [aspnet/EntityFramework6#728]
To solve my performance problems (see [here](https://github.com/aspnet/EntityFramework6/pull/430)) I created my own EF build which solved the problem and works fine in my development environment.
But today I tried to publish a new version to my Azure App Service and it failed to start with `Strong name signature could not be verified.`. I quickly copied over the original 6.2.0 version and the app is now working again, but with the performance problems...

Is there a way to disable the strong-name check on Azure to use my custom build?

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Azure App Service
IDE: Visual Studio 2017 15.9.9

**Comment by ajcvickers** [comment]
@chrfin I doubt very much that there is a way to do this, but that would really be a question for the Azure folks.
