### ISSUE TITLE
Visual Studio 2019 Preview .edmx Update

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#730]
From VS Feedback:

In .edmx Design Diagram Visualization

On right-click and click at option "Update Model from Database…".

If you add a new table, refresh or delete existing table, is not updated on .edmx file and is not updated on the project classes.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by ajcvickers** [comment]
See also #705, but that should not impact the diagram.

**Comment by ajcvickers** [comment]
Also from Feedback:

When using a database first model (to an Azure database), the Entity Framework diagram is empty although all of the necessary DbSet, model classes, foreign keys and everything else have been created correctly.

Without the diagram being available, there is no option for "Update model from database" etc., so the only current option is to delete the EDMX and re-create each time.

Opening the EDMX in an XML viewer, it would appear that the diagram content is just not being generated, as per the snippet below:

<Designer xmlns="http://schemas.microsoft.com/ado/2009/11/edmx">
<Connection>
<DesignerInfoPropertySet>
<DesignerProperty Name="MetadataArtifactProcessing" Value="EmbedInOutputAssembly" />
</DesignerInfoPropertySet>
</Connection>
<Options>
<DesignerInfoPropertySet>
<DesignerProperty Name="ValidateOnBuild" Value="true" />
<DesignerProperty Name="EnablePluralization" Value="true" />
<DesignerProperty Name="IncludeForeignKeysInModel" Value="true" />
<DesignerProperty Name="UseLegacyProvider" Value="false" />
<DesignerProperty Name="CodeGenerationStrategy" Value="None" />
</DesignerInfoPropertySet>
</Options>

<Diagrams></Diagrams>
</Designer>

View on Developer Community
To find diagnostic information, see the original linked feedback ticket.

**Comment by ajcvickers** [comment]
Also from feedback:

I have VS Community 2017 and VS Preview 2.1 2019
When i try open edmx file in 2019 - studio freeze ( the only possibility - kill it in process manager)
Not depend of model content - same on 3 different files
Same project in  VS 2017- open edmx without problem
Microsoft.XmlEditor in devenv.exe.config - have  <bindingRedirect oldVersion="0.0.0.0-16.0.0.0" newVersion="16.0.0.0"/>
EntityFramework v 6.2.0

**Comment by ajcvickers** [comment]
Also from feedback:

VS 2019 RC from Mar 12 2019 hangs up having opened the EntityFramework 6.x edmx (design surface).


This is happening with a few projects where I have EF6.x Db first edmx as part of the VS solution/project.


Solutions that VS 2019 has this problem with were created in VS 2017 (where it does not have any problems).


Another note: all troublesome VS 2017 solutions target .NET 4.5-4.7 and employ EF6.x for Db first data access.

**Comment by ajcvickers** [comment]
Also from VS feedback:

Unable to load large Model.edmx diagram


VS 2019 just locks up


Same aplication  functioned well in vs 2010 2015 2017


Approx 85 large projects in solution DDD

**Comment by ajcvickers** [comment]
Using VS2019 Community RC.4, we have been unable to reproduce these results. We have tried a large EDMX model and tried .NET versions 4.5 - 4.7. Is anyone still seeing this problem? If so could you please post a solution/project that reproduces what you are seeing?

**Comment by sachinnshah** [comment]
I am facing same issue in VS 2019.  Any solution ?

**Comment by Rawheadrex** [comment]
I have the same problem, with VS 2019 Pro, release version 16.0.1. The .tt files not run after saving edmx file. I need to open each .tt files and save (without change) for run .tt script.

**Comment by ajcvickers** [comment]
Closing this as a duplicateof #705. (There may be other issues here, but we have not been able to reproduce them. If you are hitting an bug that is not #705 then please file a new issue and include a runnable project/solution that reproduces what you are seeing.)

**Comment by vijaysahu12** [comment]
@ajcvickers I am also facing the same issue.. My web project was created in VS 2015 then after 1 years I start the development on 2017 and just few days back we jumped to 2019 but seems like the same steps working in VS2017 but not in VS2019  -- Steps was : Taking the "Update model From Database". 

I can see the procedure successfully added to 

1. GSModel.Store -> Stored Procedure/Functions
2. GSModel -> Function Import 
3. GsModel - > Complex types 

but not able to find the same procedure in code. 

Can you please help and any suggestion.

**Comment by jtrout** [comment]
Same as described here. We have a database-first EF model, and when adding a new table or view to it, or creating a new association, the underlying classes are never updated or created. It all has to be done by hand. Makes VS 2019 a no-go for us, for the time being.
