### ISSUE TITLE
__TransactionHistory not being cleared down

### ISSUE THREAD

**Issue by Shawson** [aspnet/EntityFramework6#736]
We're using Azure web apps for hosting and an Azure SQL Server which requires transient data error policies, which we've put in place.  We're having problems with the CommitFailureHandler which commits rows to the __TransactionHistory table.  I'd expect there to be a handful of recent rows for ongoing transactions, however looking in there are 1000's of rows, some dating back months.

I'd expect records in here to be removed when the transaction is complete- is there a missing house keeping job?

### Steps to reproduce
We turn on the CommitFailureHandler and SqlAzureExecutionStrategy and ran the site on live for a few months.  Normal crud operations occur, the __TransactionHistory table has started gradually filling.

```c#
public class EFConfiguration : DbConfiguration
    {
        public EFConfiguration()
        {
            SetTransactionHandler(SqlProviderServices.ProviderInvariantName, () => new CommitFailureHandler());
            SetExecutionStrategy(SqlProviderServices.ProviderInvariantName, () => new SqlAzureExecutionStrategy());
        }
```

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Azure
IDE: Visual Studio 2017 Pro 15.9.6

**Comment by ajcvickers** [comment]
@Shawson As the [documentation here](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/commit-failures#how-transactions-are-tracked) states, EF makes a best attempt to prune entities that are not needed anymore, but there are some situations where this is not possible. @AndriySvyryd may be able to provide mode details if needed.

**Comment by AndriySvyryd** [comment]
@Shawson You can prune the old transactions manually or by running this:
```C#
var objectContext = ((IObjectContextAdapter)context).ObjectContext;
((CommitFailureHandler)c.TransactionHandler).PruneTransactionHistory();
```
It's probably not worth it running it frequently.

**Comment by Shawson** [comment]
Ok, thanks for the response chaps.  We've written a web job to clear it nightly.

**Comment by Himalaya10** [comment]
@Shawson did that web job execute a sql command to delete rows or execute stored procedure ?
