### ISSUE TITLE
Function mapping issue: System.Data.Entity.Core.EntityCommandExecutionException: The data reader is incompatible with the specified 'DataModel.User'. A member of the type, 'NotifyByEmailInternal', does not have a corresponding column in the data reader with the same name.

### ISSUE THREAD

**Issue by bazarco** [aspnet/EntityFramework6#75]
My common task is: move data model from .edmx to Code-First model with less changes as possible. There was no big troubles to map entities, entity hierarchies, complex types, associations. But when I start to map function imports it happen to be non-trivial task. First time I try to use "Store Functions for EntityFramework CodeFirst" from CodePlex (https://codefirstfunctions.codeplex.com/) but this solution has many issues when mapping entities particularly with hierarchies. Then I found EntityFramework.Functions solution from Dixin (https://github.com/Dixin/EntityFramework.Functions). It is more flexible and edmx-autogen mostly native solution. And everything would be fine except one issue (subj) which cause me to do some reverse engineering of EntityFramework.
My issue appears because of this:
```cs
[Column("NotifyByEmail")]
internal bool NotifyByEmailInternal { get; set; }
```

There was a preamble.
### And this is my investigation.

I start from the end.
`ColumnMapFactory.GetMemberOrdinalFromReader(storeDataReader,member,currentType,renameList)` method (columnmapfactory.cs, line 329) generates this exception. It receives a renameList dictionary which empty in my case.
Let's move up by calling flow to find where renameList parameter fills:
`GetColumnMapsForType(storeDataReader,edmType,renameList)` (columnmapfactory.cs, line 276)
`CreateColumnMapFromReaderAndType(storeDataReader,edmType,entitySet,renameList)` (columnmapfactory.cs, line 83)
And this is it! (columnmapfactory.cs, line 28):
```c#
internal virtual CollectionColumnMap CreateFunctionImportStructuralTypeColumnMap(
	DbDataReader storeDataReader, FunctionImportMappingNonComposable mapping, int resultSetIndex, EntitySet entitySet,
	StructuralType baseStructuralType)
{
	var resultMapping = mapping.GetResultMapping(resultSetIndex);
	Debug.Assert(resultMapping != null);
	if (resultMapping.NormalizedEntityTypeMappings.Count == 0) // no explicit mapping; use default non-polymorphic reader
	{
		// if there is no mapping, create default mapping to root entity type or complex type
		Debug.Assert(!baseStructuralType.Abstract, "mapping loader must verify abstract types have explicit mapping");

		return CreateColumnMapFromReaderAndType(
			storeDataReader, baseStructuralType, entitySet, resultMapping.ReturnTypeColumnsRenameMapping);
	}
	...
```
So! Let's investigate why `resultMapping.NormalizedEntityTypeMappings.Count == 0` and what `resultMapping.ReturnTypeColumnsRenameMapping` produce.
ReturnTypeColumnsRenameMapping is an internal property of `FunctionImportStructuralTypeMappingKB` class. Like `NormalizedEntityTypeMappings` property too.
All this properties initializes in `FunctionImportStructuralTypeMappingKB` ctor which calls from `FunctionImportMappingComposableHelper` and `FunctionImportMappingNonComposable` classes.
Then let's see `FunctionImportMappingNonComposable` initialization (for stored procs) in EntityFramework.Functions framework:
```c#
model.ConceptualToStoreMapping.AddFunctionImportMapping(new FunctionImportMappingNonComposable(
	modelFunction,
	storeFunction,
	Enumerable.Empty<FunctionImportResultMapping>(),
	model.ConceptualToStoreMapping));
```
If third parameter (resultMappings) is not an empty collection there will be an `NullReferenceException` here (`FunctionImportMappingNonComposable` ctor):
```c#
else
{
	Debug.Assert(functionImport.ReturnParameters.Count == resultMappings.Count());

	_internalResultMappings = new ReadOnlyCollection<FunctionImportStructuralTypeMappingKB>(
		resultMappings
			.Select(
				resultMapping => new FunctionImportStructuralTypeMappingKB(
										resultMapping.TypeMappings,
										containerMapping.StorageMappingItemCollection.EdmItemCollection))
			.ToArray());

	noExplicitResultMappings = false;
}
```
because `containerMapping.StorageMappingItemCollection` **is null**.
This issue described upper in ctor code (commit b4cb2b1 by @moozzyk):
```cs
// when this method is invoked when a CodeFirst model is being built (e.g. from a custom convention) the
// StorageMappingItemCollection will be null. In this case we can provide an empty EdmItemCollection which
// will allow inferring implicit result mapping
```
This is the full code part:
```cs
if (!resultMappings.Any())
{
	// when this method is invoked when a CodeFirst model is being built (e.g. from a custom convention) the
	// StorageMappingItemCollection will be null. In this case we can provide an empty EdmItemCollection which
	// will allow inferring implicit result mapping
	var edmItemCollection = containerMapping.StorageMappingItemCollection != null
		? containerMapping.StorageMappingItemCollection.EdmItemCollection
		: new EdmItemCollection(new EdmModel(DataSpace.CSpace));

	_internalResultMappings = new ReadOnlyCollection<FunctionImportStructuralTypeMappingKB>(
		new[]
			{
				new FunctionImportStructuralTypeMappingKB(
					new List<FunctionImportStructuralTypeMapping>(), 
					edmItemCollection)
			});
	noExplicitResultMappings = true;
}
```
So... It means I must set resultMapprins ctor parameter to `Enumerable.Empty<FunctionImportResultMapping>()`. And it means (according to code) `structuralTypeMappings` parameter of `FunctionImportStructuralTypeMappingKB` ctor will be `new List<FunctionImportStructuralTypeMapping>()` and this code part of `FunctionImportStructuralTypeMappingKB` class will be invoked (line 30):
```cs
if (structuralTypeMappings.Count() == 0)
{
	// Initialize with defaults.
	ReturnTypeColumnsRenameMapping = new Dictionary<string, FunctionImportReturnTypeStructuralTypeColumnRenameMapping>();
	NormalizedEntityTypeMappings =
		new ReadOnlyCollection<FunctionImportNormalizedEntityTypeMapping>(
			new List<FunctionImportNormalizedEntityTypeMapping>());
	DiscriminatorColumns = new ReadOnlyCollection<string>(new List<string>());
	MappedEntityTypes = new ReadOnlyCollection<EntityType>(new List<EntityType>());
	return;
}
```
At last we have `NormalizedEntityTypeMappings` collection is **empty**, `ReturnTypeColumnsRenameMapping` dictionary is **empty**.

I did not found any other locations where I can reset `NormalizedEntityTypeMappings` or `ReturnTypeColumnsRenameMapping` values.

So, there is no way to setup 'rename list' of columns used by DB reader wrapper of ObjectContext.
**Another point is that everything works fine for TVFs** (over `FunctionImportMappingComposable` ctor and `FunctionImportMappingComposableHelper`).

Finally I propose to add one method to native framework which helps to solve this issue:
```cs
/// <summary>
/// Initializes a new FunctionImportMappingNonComposable instance.
/// </summary>
/// <param name="functionImport">The model function import.</param>
/// <param name="targetFunction">The store non-composable function.</param>
/// <param name="resultMappings">The function import result mappings.</param>
/// <param name="containerMapping">The parent container mapping.</param>
// TODO: This ctor can be optimized with next ctor as one used by another
public FunctionImportMappingNonComposable(
	EdmFunction functionImport,
	EdmFunction targetFunction,
	IEnumerable<FunctionImportResultMapping> resultMappings,
	EdmItemCollection edmItemCollection)
	: base(
		Check.NotNull(functionImport, "functionImport"),
		Check.NotNull(targetFunction, "targetFunction"))
{
	Check.NotNull(resultMappings, "resultMappings");
	//Check.NotNull(edmItemCollection, "edmItemCollection");

	Debug.Assert(!functionImport.IsComposableAttribute);
	Debug.Assert(!targetFunction.IsComposableAttribute);

	var edmItemCollectionInt = edmItemCollection ?? new EdmItemCollection(new EdmModel(DataSpace.CSpace));

	if (!resultMappings.Any())
	{
		_internalResultMappings = new ReadOnlyCollection<FunctionImportStructuralTypeMappingKB>(
			new[]
				{
					new FunctionImportStructuralTypeMappingKB(
						new List<FunctionImportStructuralTypeMapping>(),
						edmItemCollectionInt)
				});
		noExplicitResultMappings = true;
	}
	else
	{
		Debug.Assert(functionImport.ReturnParameters.Count == resultMappings.Count());

		_internalResultMappings = new ReadOnlyCollection<FunctionImportStructuralTypeMappingKB>(
			resultMappings
				.Select(
					resultMapping => new FunctionImportStructuralTypeMappingKB(
											resultMapping.TypeMappings,
											edmItemCollectionInt))
				.ToArray());

		noExplicitResultMappings = false;
	}

	_resultMappings = new ReadOnlyCollection<FunctionImportResultMapping>(resultMappings.ToList());
}
```

**Comment by rowanmiller** [comment]
It is by design that a raw SQL query does not use the mappings, it does a straight match on result set column names to property names. We would consider a pull request to enable opting in to use mappings (it can't be the default behavior as this would break existing apps), but it's not something our team is planning to work on.

BTW in EF Core we do use mappings when running raw SQL queries.
