### ISSUE TITLE
Code Snippet not show entityframework System.Data.Entity on Visual Studio 2019

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#763]
From VS Feedback:

I have installed both VS 2017 Community and VS 2019 Community (Just installed today).

I has a project (.net Framework 4.5.2) created with VS 2017 with EntityFrameWork (version 6.1.3) already installed in my project nuget package

(Visual studio 2019 Community)

When i open my Models file that extend DBContext,I cant find Class under DBContext, and when i try to look at code snippet on import "using System.Data.Entity" . it`s not show on my code snippet. but when i compile project not showing error. i try to checking my nuget package i still have EntityFramework package. when i see my project object reference i can still find System.Data.Entity under EntityFramework dll. when i see my project reference , i find warning icon .

(Visual studio 2017 Community)

Working just fine

Thank you

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by zq0flaz** [comment]
I guessing the cause is VS 2019 code snippet cant detect package from package.config. I think in code snippet VS 2019 use Package Reference because when i try to create project in VS 2019 and open it in both VS 2017 and VS 2019 it work just fine.  

Maybe this link will help you to migrate project from package.config to package reference
https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

Thank You

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
