### ISSUE TITLE
EDMX Designer Broken in VS2019 (16.1 Preview 1)

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#767]
I just upgraded to the latest VS2019 preview, and opened up a project with a previously working EDMX file. Now, opening the file throws an exception.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by robertmclaws** [comment]
@ajcvickers Sorry about that. Here's the problem. Entity Framework 6 has no understanding of SDK-style (CPS) projects. So all of the code generation is designed for the legacy C# project types. Specifically, [this code](https://github.com/aspnet/EntityFramework6/blob/22a11d132306c257435fa7d6d75a31359cbbd05a/src/EFTools/EntityDesign/VisualStudio/VsUtils.cs#L1828-L1866) does not properly detect CPS projects, and so if you try to manipulate an EDMX file in a .NET Core project, you get this error message about 9 times:

![image](https://user-images.githubusercontent.com/1657085/57971251-962b9680-7959-11e9-8cde-df885dc58f59.png)

Hope that helps!

**Comment by ajcvickers** [comment]
Duplicate of #231
