### ISSUE TITLE
Update-Dabase -Script does not generate seed sql

### ISSUE THREAD

**Issue by San7hos** [aspnet/EntityFramework6#78]
We have disabled automatic migrations. We use Update-Databse to update our local dev databases and migrate.exe to update our dev/test remote database.

However, when deploying for our client, we need to generate a sql script with seed (= referential) data as well.

The `Update-Database -Script` does not generate the seed sql.

**Comment by rowanmiller** [comment]
We have discussed implementing scripting for seed data, but it would be pretty complex to do and isn't something our team is planning to tackle on EF6.x. We may tackle it when we implement seeding in EF Core (https://github.com/aspnet/EntityFramework/issues/629).

An option is to not use the built in seed methods, but instead use raw SQL in you migrations (the `Sql(...)` API) to insert the data. These operations will be included in the generated script.
