### ISSUE TITLE
Browser Model not visible

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#788]
From VS Feedback:

The Model Browser window & #232; empty or not visible

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by lstauber** [comment]
Same here. 16.1, ef model, model browser empty or containing data from previously active tab. Steps to reproduce - open edmx designer with old edmx file and then model browser.

**Comment by melcug** [comment]
I confirm the issue.
I'm using Visual Studio 2019 version 16.1.1 and EF version 6.2.
In order to reproduce this issue, I created a model based on an existing database, the application is built it's running with no errors.
But the Entity Data Model Browser Window is empty or gets "parts" from other opened windows (see bellow).
![EF Model Browserl](https://user-images.githubusercontent.com/8708178/58753148-d8111c80-84c3-11e9-9a22-22bf2cf49bd5.png)

**Comment by roblarky** [comment]
Same issue here. This is a brand new laptop, so it has only ever had VS 2019 Community installed, no prior versions. The solution was created in VS 2017. The Model Browser panel renders fine for the same solution on my other systems in VS 2019, though those machines also have VS 2017 installed, in case that helps any.

It's difficult to identify exactly what is wrong. The steps to reproduce are simple, open any EDMX and try to view the Model Browser. It's not rendering/painting anything; clicking in the unrendered area has no reaction. 

Existing solutions exhibit the issue and I even created a brand new solution with a new EDMX, always the same result on this system.

I've repaired, and uninstalled/reinstalled EF6 Tools, all with no success. For now, I simply have to use another machine if I need to access the Model Browser, check in and pull on my new system. Everything functions fine, just cannot view the Model Browser at all. EDMX designer shows fine, shows tables, but right-click a table and click Show in Model Browser just shows an empty panel, or one with visual artifacts from whatever was displayed in that area previously.

**Comment by corylangston** [comment]
Issue resolved by uninstall .NET 4.8 and restarting.

For existing project, only the designer opens in VS 2019 Ent. The model browser and table mapping views are blank.
Verified issue does not occur with either VS 2017 Ent. or VS 2019 Pro.

Running 
Microsoft SurfaceBook 2
Microsoft Windows 10 version 1809 (OS Build 17763.529)
Microsoft Visual Studio Enterprise 2019 Version 16.1.1
Microsoft .NET Framework 4.8.03761

1) Same computer, different user profile. Same issue.
2) Empty test project with a simple DB first model (.NET 4.7.2 + EF 6.2). Same issue.
3) Removed and reinstalled EF Tools via "Tools > Get Tools and Features". Same issue.
4) Completely uninstalled(Add/Remove programs) all VS editions and reinstalled VS 2019 Ent. Same issue.
5) Completely uninstalled(Add/Remove programs) and ran InstallCleanup "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\layout\InstallCleanup.exe" -f. Reinstalled VS 2019 Ent. Resolved issue with test project.
6) Existing project with complex model. Same issue.
7) Reopend test project. Same issue.
8) Updated to VS 2019 Ent. 16.1.2. Same issue.
9) Downgraded to VS 2019 Pro. Same issue.
10) Uninstall .NET 4.8. Issue resolved.

**Comment by melcug** [comment]
Unchecking in **Tools -> Options ->  Environment -> General -> Optimize rendering for screens with different pixel densities** solves the problem with the rendering of the model browser and the table mapping views.
I also updated Windows 10 to the latest version (10.0.18362.145).

**Comment by corylangston** [comment]
Thank you @melcug for the workaround.  I just updated Windows 10 and unchecked **Tools -> Options -> Environment -> General -> Optimize rendering for screens with different pixel densities**.  It worked like a charm.

**Comment by roblarky** [comment]
@melcug  Thank you!
