### ISSUE TITLE
Simplify transaction handling samples

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework6#8]
Our current set of [documentation for using transactions with EF6](https://msdn.microsoft.com/en-us/data/dn456843.aspx) includes some samples that follow this pattern:

```
using (var context = new BloggingContext()) 
{ 
    using (var dbContextTransaction = context.Database.BeginTransaction()) 
    { 
        try 
        { 
            DoSomeWork(context);
            context.SaveChanges(); 
            dbContextTransaction.Commit(); 
        } 
        catch (Exception) 
        { 
            dbContextTransaction.Rollback(); 
        } 
    } 
} 
```

It turns out that:
1. The explicit call to `dbContextTransaction.Rollback()` is in most cases unnecessary, because disposing the transaction at the end of the using block will take care of rolling back.
2. If an error of sufficient severity occurs in SQL Server, the transaction will get automatically rolled back, and the call to `dbContextTransaction.Rollback()` in the catch block will actually fail.

For the second, note that our implementation of `Rollback()` simply delegates to the ADO.NET provider `Rollback()` method so the following note from the remarks in [the underlying method's documentation](https://msdn.microsoft.com/en-us/library/zayx5s0h%28v=vs.110%29.aspx) apply:

> Try/Catch exception handling should always be used when rolling back a transaction. A Rollback generates an InvalidOperationException if the connection is terminated or if the transaction has already been rolled back on the server.

The sample code has proven to be confusing at least for one of our customers and relying on the automatic rollback behavior of disposing without first calling `Commit()` works more reliably and leads to simpler code, so I propose we fix the samples to use that pattern:

```
using (var context = new BloggingContext()) 
{ 
    using (var dbContextTransaction = context.Database.BeginTransaction()) 
    { 
        DoSomeWork(context);
        context.SaveChanges(); 
        dbContextTransaction.Commit(); 
    } 
} 
```

Note that this pattern applies to EF Core 1.0 as well, when we write the corresponding documentation.

**Comment by rowanmiller** [comment]
Ported from CodePlex https://entityframework.codeplex.com/workitem/2909

**Comment by ShadySadek** [comment]
Please i have scenario here , in the following code i am assuming that for-each will be executed twice:
_-first loop will be executed successfully and commit the inner transaction._
_-second loop will fail  and Rollback the inner transaction._

**I am expected to find the added rows by the first transaction before rollback the outer transaction but looks like what is happening is rolling back second loop will roll back also first loop**

looks like using **BeginTransaction** within **TransactionScope** has some issues in addition to the issues with nested transaction in EF6

Any thoughts on this? 

```
 using (var OuterTransactionScope = new TransactionScope())
            {
                using (DbContext = new DbContext())
                {
                    foreach (var x in list) // assume this will be executed twice 
                    {
                        try
                        {
                            var innerTransaction = DbContext.Database.BeginTransaction(isolationLevel);
                            DbContext.SaveChanges(); //Add row
                            DbContext.SaveChanges(); //Add row
                            innerTransaction.Commit();
                        }
                        catch (Exception ex)
                        {
                            innerTransaction.Rollback();
                        }
                    }
                    //Expecting to find two rows here but Actually no data get added
                }
```

**Comment by rowanmiller** [comment]
Moved to the docs repo as the EF6.x docs are going to end up in the same repo as the EF Core docs. They are going thru a migration process, so changes are difficult right now. https://github.com/aspnet/EntityFramework.Docs/issues/327
