### ISSUE TITLE
Ability to specify size and precision for decimal columns using Fluent API

### ISSUE THREAD

**Issue by NaomiN** [aspnet/EntityFramework6#80]
I've checked https://msdn.microsoft.com/en-us/data/jj591617.aspx#1.10 but I don't see a way to specify the exact size and precision for decimal columns. In our case we're using decimal(17,0) for keys. The INSERT command generated by EF creates parameter as decimal(18,2) which produces an error when I am passing 3438000001.00. That value is OK to insert if the parameter would have been defined as decimal(17,0).

What can be done?

**Comment by rowanmiller** [comment]
There is a `.HasPrecision` API that you can use.

```
modelBuilder.Entity<Product>()
    .Property(e => e.ListPrice)
    .HasPrecision(18, 2)
```
