### ISSUE TITLE
Unable to update EntityFramework models from PostgreSQL database (version 9.3) in Visual Studio 2017

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#811]
From VS Feedback:

Our developer group upgraded from Visual Studio 2013 to Visual Studio 2017. we now attempted to update some of our existing "db-first" EntityFramework models from our PostgreSQL database. When doing so, we received the following error. An exception of type 'System.ArgumentException' occurred while attempting to update from the database. The exception message is: 'Unable to convert runtime connection string to its design-time equivalent. The libraries required to enable Visual Studio to communicate with the database for design purposes (DDEX provider) are not installed for provider ‘Npgsql’. Does anyone has clue how to solve this problem? Thx! we ask the question in forum in the link: https://social.msdn.microsoft.com/Forums/en-US/3df4ca4a-aa96-40b1-bc4f-3152c27be42a/unable-to-update-entityframework-models-from-postgresql-database-version-93-in-visual-studio-2017?forum=adodotnetentityframework

**Comment by ajcvickers** [comment]
@roji Doest his ring any bells? If not, I'll ask for a repro.

**Comment by roji** [comment]
These DDEX/VSIX issues are notoriously difficult to diagnose. First thing would be to confirm which version of the VSIX they have installed. I'd also recommend trying the latest VSIX on a totally new computer which hasn't been used with Npgsql/VSIX before, as leftovers from previous versions of the VSIX can interfere and cause issues.

You can also propose that they open an issue in the Npgsql repo.

**Comment by ajcvickers** [comment]
@roji Thanks. 

VS Feedback user: please follow suggestions from @roji and get back to us.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
