### ISSUE TITLE
Exception: Collection is already set to an EntityCollection in object with all properties virtual

### ISSUE THREAD

**Issue by jfevia** [aspnet/EntityFramework6#812]
Any entity that contains only virtual properties will throw an exception when initializing its collection(s) in the constructor. This issue requires to have at least one entry in the database in order to be reproduced.

This seems to be an issue since the entity should be initialized regardless of the rest of its properties or the logic behind the virtual modifier. I found a similar issue dating back to 2010 in SO (https://stackoverflow.com/a/4069727), more specifically this part:

> So it appears that I only have the problem with a full 'change tracking proxy' if all my properties are virtual.

```
Exception message: The property 'Packages' on type 'Store_87BE7390C3646F421F89B434F1E15F1984BB49603F57243C6D4933AB0309AACD' cannot be set because the collection is already set to an EntityCollection.
Stack trace:    at System.Data.Entity.DynamicProxies.Store_87BE7390C3646F421F89B434F1E15F1984BB49603F57243C6D4933AB0309AACD.set_Packages(ICollection`1 )
   at Test.Store..ctor() in E:\Dev\EntityBase.cs:line 30
   at System.Data.Entity.DynamicProxies.Store_87BE7390C3646F421F89B434F1E15F1984BB49603F57243C6D4933AB0309AACD..ctor()
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
```

### Steps to reproduce
Note that the below steps require **at least one entry for each entity in the database**.

1. Create a class (e.g.: EntityBase) with all its properties set to virtual.
2. Create 2 classes (e.g.: Store and Package) that inherit from the above class.
3. Add a collection of Packages to the Store class.

I managed to reproduce this issue with the below code:
```c#
public abstract class EntityBase
{
	public virtual int Id { get; set; }
	public virtual string Name { get; set; }
}

public abstract class PackageBase : EntityBase
{
	public virtual int StoreId { get; set; }
}

public class Package : EntityBase
{
	public virtual Store Store { get; set; }
}

public class StoreBase : EntityBase
{
}

public class Store : StoreBase
{
	public Store() => Packages = new HashSet<Package>();
	public virtual ICollection<Package> Packages { get; set; }
}

public class SqlDbContext : DbContext
{
	public SqlDbContext()
		: base("name=ConnectionString")
	{
	}
	public virtual DbSet<Store> Stores { get; set; }
	public virtual DbSet<Package> Packages { get; set; }
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.0.3

**Comment by ajcvickers** [comment]
**EF Team Triage:** This is a known limitation of the way change tracking proxies are implemented for classic EF. It is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
