### ISSUE TITLE
EDMX Metadata Generator options for .NET Core

### ISSUE THREAD

**Issue by robertmclaws** [aspnet/EntityFramework6#828]
Per the announcement post, EF 6.3 Preview 5 is currently shipping without EDMX support. Fortunately, I solved that problem about a year ago for SDK-style projects targeting the .NET Framework. I've open-sourced that tool here: https://github.com/CloudNimble/EF6.3MetadataGenerator.

Elements of this tool could be turned into a .NET Core Global Tool using `dotnet-script` and csx files (or possibly another option), but the code would have to be changed to manipulate the Project XML manually.

[According to this tweet](https://twitter.com/divega/status/1126271044505853952), the team is considering a couple different options. I thought this thread would be a good place to discuss those options, and consider if the tool I linked to would be useful in the final product.

**Comment by bricelam** [comment]
My initial thought was just to port and package `Microsoft.Data.Entity.targets` and `Microsoft.Data.Entity.Build.Tasks.dll` as part of EntityFramework. It feels like a good candidate for NuGet's [buildTransitive](https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior) directory.

**Comment by bricelam** [comment]
I've got this working on an internal branch using the approach I described. We're just waiting for approval to open source Microsoft.Data.Entity.Build.Tasks.dll...

**Comment by GuyBenhaim** [comment]
Hello,
Was there a conclusion on this? in 6.3 Preview 7?
Thx

**Comment by ajcvickers** [comment]
@GuyBenhaim The fix was included in preview 7.
