### ISSUE TITLE
Update error numbers for SQL Azure Execution Strategy

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework6#83]
Add 121, 1205, 41839, 49918, 49919, 49920
See https://github.com/aspnet/EntityFramework/issues/6665 and https://github.com/aspnet/EntityFramework/issues/6970

**Comment by judowalker** [comment]
Should this be updated as well:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/sql-database/sql-database-develop-error-messages.md

**Comment by tjrobinson** [comment]
This documentation doesn't include the additional error numbers: https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlazureexecutionstrategy?view=entity-framework-6.2.0

I've raised an issue: https://github.com/dotnet/EntityFramework.Docs/issues/3981
