### ISSUE TITLE
Entity Data Model Wizard - display error

### ISSUE THREAD

**Issue by blfuentes** [aspnet/EntityFramework6#846]
While trying to use the Entity Data Model Wizard with the option Database First the selection of tables and other items is not shown correctly.
The "layer" with the "Retrieving database information, please wait ..." stays at the top in front of the selection treeview and I cannot use it correctly (check screenshot)

I have reinstalled the complete Visual Studio and still not working. 

### Further technical details
Visual Studio 2019 Enterprise 16.0.3, 16.0.4 also not working
Windows 10 1809 17763.475
EF version: 6.2.0
Database Provider: SQL Server

![error EF](https://user-images.githubusercontent.com/5121778/57779380-43b66400-7726-11e9-9265-3b76dc28e030.PNG)

Related to
https://github.com/aspnet/EntityFramework6/issues/789

https://developercommunity.visualstudio.com/content/problem/562586/entity-data-model-wizard-display-error.html

**Comment by lajones** [comment]
@blfuentes First try updating your VS. 16.1 Preview 3 is now available.

If that doesn't work then let us know. Unfortunately, as detailed in #789, a couple of customers have run into this but we've been unable to repro it internally even on the 16.0 builds. So please provide as much detail as possible. Also did you try the workarounds in #789 - what were the results?

**Comment by blfuentes** [comment]
@lajones Thanks for the quick answer.
- I tried the two workarounds( re-scale the dialog and change the screen resolution). Both didn't work.

So I installed the Preview 3 and I can confirm it is working. I hope this is still fixing the problem once the preview version is moved to the stable channel.

**Comment by blfuentes** [comment]
@lajones I think this issue can be closed as the last prod version 16.1.0 solved this problem.

**Comment by lajones** [comment]
@blfuentes Thanks for letting us know. Appreciate the feedback.
