### ISSUE TITLE
Add ability to have custom aggregate functions with multiple parameters

### ISSUE THREAD

**Issue by trs79** [aspnet/EntityFramework6#85]
Currently when creating custom aggregate functions in a code-first scenario, calling the function will fail if there is more then one parameter

**Comment by rowanmiller** [comment]
Can you provide a little more info on this one.
* Is this something you believe should work but is blocked by a bug in code first?
* Can you share the exception message and stack trace?

**Comment by trs79** [comment]
After looking at the source code, it looks like this isn't a bug but is intentional. In PlanCompilerUtils.cs in the function `IsCollectionAggregateFunction()` the code is explicitly checking that there is only one argument.

In GroupAggregateRefComputingVisitor.cs in the function `Visit()` there is also an assert:
`PlanCompiler.Assert(n.Children.Count == 1, "Aggregate Function must have one argument");
`

I'll also post the message and stack trace tomorrow. Even though this is intentional, would it be possible to change the behavior to allow multiple arguments?

**Comment by rowanmiller** [comment]
This isn't something our team would plan to address on EF6.x, but we would be willing to consider a pull request if you (or someone else) wanted to look at relaxing the requirement.

**Comment by trs79** [comment]
Thanks for the response. It sound like this might be something that makes its way into Entity Framework Core?

As far as a pull request for EF6.x, can you recommend any resources for understanding the codebase for someone who is new to it ?

**Comment by rowanmiller** [comment]
When we implement the equivalent in EF Core we will look at this scenario.

> As far as a pull request for EF6.x, can you recommend any resources for understanding the codebase for someone who is new to it ?

Here is a blog series from one of our developers that helps you get started... https://blog.oneunicorn.com/2012/07/19/so-you-want-to-contribute-to-ef-part-1-introduction/

**Comment by rowanmiller** [comment]
Re-opening as a PR has been submitted https://github.com/aspnet/EntityFramework6/pull/90

**Comment by maumar** [comment]
moving out of 6.2

**Comment by ajcvickers** [comment]
Closing for now; will re-open if the PR gets to a state where it can be merged.
