### ISSUE TITLE
Where are ComplexType property names constructed?

### ISSUE THREAD

**Issue by phatcher** [aspnet/EntityFramework6#86]
I'm trying to override the column name for a number of complex types - I can see the conventions that find the complex type but I can't locate the code that constructs the name as [ReferencingEntity]_[Property]

**Comment by rowanmiller** [comment]
Here is the main entry point that adds complex types to the model, you should be able to drill down from there https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/ModelConfiguration/Conventions/Edm/ComplexTypeDiscoveryConvention.cs
