### ISSUE TITLE
Compile EntityFramework6 with 2017

### ISSUE THREAD

**Issue by testZyhGitHub** [aspnet/EntityFramework6#887]
The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 1.6 or lower, 
        or use a version of the .NET SDK that supports .NET Standard 2.1.

**Comment by testZyhGitHub** [comment]
I want to build the total project of EntityFramework6 with vs2018 on win10 but get this error

**Comment by ajcvickers** [comment]
@testZyhGitHub You're going to need VS2019 to build EF6 with Visual Studio, since nothing earlier supports targeting .NET Core 3.

**Comment by testZyhGitHub** [comment]
> @testZyhGitHub You're going to need VS2019 to build EF6 with Visual Studio, since nothing earlier supports targeting .NET Core 3.

Thank you, but if i dot not have Vs2019, but only have vs2017, can i get the Previous version of EF6.

**Comment by testZyhGitHub** [comment]
@ajcvickers Thank you, but if i dot not have Vs2019, but only have vs2017, can i get the Previous version of EF6.

**Comment by bricelam** [comment]
You can...

- Download [Visual Stuido Community 2019](https://visualstudio.microsoft.com/vs/community/) for free
- Check out or download the code for an earlier release. For example, [6.2.0](https://github.com/aspnet/EntityFramework6/releases/tag/6.2.0).
- Remove `netstandard2.1` from the target frameworks list

**Comment by testZyhGitHub** [comment]
@bricelam ths
