### ISSUE TITLE
can't get Enable-Migrations to work

### ISSUE THREAD

**Issue by jancg** [aspnet/EntityFramework6#904]
Can't get Enable-Migrations to work.

I know this is not a complete bug report. It isn't meant to be. Please reply with a guide *how* Migrations should work using EF 6.3 (targeting .NET FrameWork). EF 6.3 works in the sense that I succeeded to insert and query some data from a fresh database (CreateIfNotExists).

Kind regards, Jan.

**Comment by ajcvickers** [comment]
@jancg Tooling is still being worked on, so it likely doesn't work because it hasn't been implemented yet in the build you are using.
/cc @bricelam
