### ISSUE TITLE
Save LineString in DbGeometry from MySql Error

### ISSUE THREAD

**Issue by pauloanalista** [aspnet/EntityFramework6#91]
When you save an entity that owns a property DbGeometry the entity framework error.

When saving a POINT works perfectly

When saving a LineString or Polygon an error occurs.

![x](https://cloud.githubusercontent.com/assets/6010161/19519907/a6847cb6-95ec-11e6-88e5-1bddf88fd2e1.PNG)
![capturar](https://cloud.githubusercontent.com/assets/6010161/19519913/ad0add14-95ec-11e6-99cd-4aa121d7f7a2.PNG)

Stack Trace:
System.Data.Entity.Infrastructure.DbUpdateException was unhandled
HResult=-2146233087
Message=An error occurred while updating the entries. See the inner exception for details.
Source=EntityFramework
StackTrace:
em System.Data.Entity.Internal.InternalContext.SaveChanges()
em System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
em System.Data.Entity.DbContext.SaveChanges()
em ConsoleApplication.Program.Main(String[] args) na C:\Users\paulo\Desktop\EFWithMySql\EFWithMySql\ConsoleApplication\Program.cs:linha 44
em System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
em System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
em Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
em System.Threading.ThreadHelper.ThreadStart()
InnerException: 
HResult=-2146233087
Message=An error occurred while updating the entries. See the inner exception for details.
Source=EntityFramework
StackTrace:
em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.b__2(UpdateTranslator ut)
em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.UpdateT
em System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
em System.Data.Entity.Core.Objects.ObjectContext.b__35()
em System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransactionT
em System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
em System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.b__27()
em System.Data.Entity.Infrastructure.DefaultExecutionStrategy.ExecuteTResult
em System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
em System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
em System.Data.Entity.Internal.InternalContext.SaveChanges()
InnerException: 
HResult=-2146232005
Message=An error occurred while preparing the command definition. See the inner exception for details.
Source=EntityFramework
StackTrace:
em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.CreateCommand(DbModificationCommandTree commandTree)
em System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.CreateCommand(Dictionary2 identifierValues) em System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary2 identifierValues, List1 generatedValues) em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update() InnerException: HResult=-2146233080 Message=O índice estava fora dos limites da matriz. Source=MySql.Data.Entity.EF6 StackTrace: em MySql.Data.Entity.Metadata.NormalizeValue(TypeUsage type, Object value) em MySql.Data.Entity.SqlGenerator.Visit(DbConstantExpression expression) em System.Data.Entity.Core.Common.CommandTrees.DbConstantExpression.Accept[TResultType](DbExpressionVisitor1 visitor)
em MySql.Data.Entity.InsertGenerator.GenerateSQL(DbCommandTree tree)
em MySql.Data.MySqlClient.MySqlProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree)
em System.Data.Entity.Core.Common.DbProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
em System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
em System.Data.Entity.Core.Common.DbProviderServices.CreateCommand(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
em System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.CreateCommand(DbModificationCommandTree commandTree)
InnerException:

**Comment by rowanmiller** [comment]
This looks like an issue in the MySQL provider - which is provided by the MySQL team. Can you follow up with them at http://bugs.mysql.com/.
