### ISSUE TITLE
Inconsistent Pluralization of Table names using migrations

### ISSUE THREAD

**Issue by AdamHess** [aspnet/EntityFramework6#92]
I created two different entities both with the suffix "Info"  (BasicInfo and W4Info)and represent them in my context using a different property names. 

When running migrations it generates two different pluralizations for each entity. 

That is: 

BasicInfo**es**  
W4Info**s**

An example of the code can be seen here (very rudimentary but will generate this inconsistency): 

https://github.com/AdamHess/entityframework-pluralization-bug

the commands I used on the commandline were: 

```
Enable-Migrations   
Add-Migration MyTestMigration
```

Finally, this was while using Visual Studio 2015 update 3.

**Comment by AlbertoMonteiro** [comment]
According with the pluralization rules, in those lines(https://github.com/aspnet/EntityFramework6/blob/527ae18fe23f7649712e9461de0c90ed67c3dca9/src/EntityFramework/Infrastructure/Pluralization/EnglishPluralizationService.cs#L595..L598), any word that contains non alphabetical characters will not have the same pluralization rule.

So you can remove the algarism 4 of your table name.

**Comment by AdamHess** [comment]
It seems an overly broad rule . (also troublesome for globalization) with the latter issue aside, would it make more sense for the pluralization rules to not kick in if and only if the last character is a number? 

(while it's kind of late) i feel like it's an "opt out" feature, anyway to override its 'broadness' without having to explicitly specify the table name.

**Comment by rowanmiller** [comment]
At this stage we aren't going to take any changes to the pluralizer in EF6.x. The main issue is that any changes we take can result in a existing model changing when you upgrade to a new version of EF. 

However, you can customize the pluralizer by replacing `IPluralizationService`. See [Dependency Resolution](https://msdn.microsoft.com/en-us/data/jj680697) for more info.
