### ISSUE TITLE
SQLite & REGEXP

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#938]
The REGEXP function of SQLite does not function with VB NET 2019.

```VB
Imports System.Text.RegularExpressions
Public Class Form1
   ' ...
    Sub REGEXP()
        OpenDataBase()
        sqlite_cmd.commandtext = "SELECT * FROM books WHERE comment REGEXP '[^ ]\?'  "  
        sqlite_cmd. ExecuteNonQuery()
        sqlite_cmd. Dispose()
        sqlite_conn. Close()
    End Sub
     '  ...
End Class
```

```VB
Imports System.Data.SQLite
Module SQLite

Public Database As String = FichierFSL
    Public sqlite_conn As New SQLiteConnection   'ici new
    Public sqlite_cmd = New SQLiteCommand
    Public Reader As SQLiteDataReader

Public Sub OpenDataBase()
        Try
            sqlite_conn. ConnectionString = "Data Source=" &amp; Database
            sqlite_conn. Open()
            sqlite_cmd = sqlite_conn. CreateCommand
        Catch ex As Exception
            MessageBox.Show(ex. Message)
        End Try
    End Sub

End Module
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/594638/sqlite-regexp.html
VSTS ticketId: 904979_
_These are the original issue comments:_

Visual Studio Feedback System on 6/5/2019, 00:32 AM (20 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

John Qiao [MSFT] on 6/5/2019, 08:23 PM (19 days ago): <p>Hi Jean,</p><p>Thanks for your feedback!</p><p>What’s the expected result in your REGEXP function? What’s the error message you received?</p><p>Which code line did not work as expect?</p><p>Does the same REGEXP function work well in other type of project?</p><p>If you can repro this scenario in a new simple project, please share your sample project here, that will help us provide the better response. </p>

_These are the original issue solutions:_
(no solutions)

**Comment by lajones** [comment]
@bricelam - may want to move to the sqlite repo.

**Comment by ErikEJ** [comment]
This is external (System.Data.SQLite)

**Comment by ajcvickers** [comment]
As @ErikEJ says, this is `System.Data.SQLite` which is not something produced by Microsoft. You will need to follow up with them.

**Comment by bricelam** [comment]
FYI, their issue tracker is here: https://system.data.sqlite.org/index.html/rptview?rn=2
