### ISSUE TITLE
Inserting a migration between already existing migrations

### ISSUE THREAD

**Issue by San7hos** [aspnet/EntityFramework6#94]
Imagine a scenario where you have a production environment (prod) and development environment (dev).

You applied migrations A to C to prod and it is live.
The developers meanwhile produces migration D and E on top of C.

A situation arises where you are forced to do a hot fix on the production and while fixing the issue you find out that you need to create a migration (change model and db). Let's name the migration C-HotFix.

When merging back to dev, is it possible to insert the migration and recalculate the checksum of the following migrations so the result would on dev would be: A B C C2 D E?

Are there any best/good practices to handle such scenarios?

**Comment by AlbertoMonteiro** [comment]
Look this: http://devgush.com/2016/02/05/entity-framework-code-first-migrations-in-a-team-environment/

**Comment by San7hos** [comment]
I've already read the msdn article.Those articles do not really discuss the fact that you have a db deployed and you cannot do downs as you please.

So far my solution would be to take the hot fix migration path.Revert all to hot fix -1,apply HF migration and then scaffold a new migration on top of that.It seems like a lot of hassle even though it should be rather a rare scenario.

**Comment by rowanmiller** [comment]
The ordering is based purely on the timestamps of the migration file, so you can definitely change the timestamp to make C2 come directly after C. The rough edge you will hit, is that the target model of E is considered the last known model when the next migration is generated, and this won't include the change introduced in C2 - so the next generated migration will try to re-apply the change. This is where the info in https://msdn.microsoft.com/en-us/library/dn481501(v=vs.113).aspx comes in - you need to use one of the approaches in the "Resolving the merge conflict" section.

**Comment by San7hos** [comment]
We have concluded that we need to keep the path from the production and "re-scaffold" a brand new migration on top including all the newer migrations.

Thanks for your time
