### ISSUE TITLE
The wrong method call is skipped by the studio and the compiler.

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#941]
In my method, I used a method call with an incorrect parameter. Neither the studio (v.16.1.1 community) nor the compiler will issue any messages during building.

```C#
public async Task<T> FindDictData<T>(Expression<Func<T, bool>> findPredicate) where T : class, IDictData, new() {
            /* for feedback.
            using Microsoft.EntityFrameworkCore;
            public DbContext Connection { get; }
            */
            DbSet<T> table = Connection.Set<T>();
            try {
                return await table. FindAsync(findPredicate /*wrong type!!! */);
            } catch (Exception err) {
                // какой-то error
                Debug.WriteLine($"{err. GetType(). Name}: {err. Message}");
            }
            return default; 
        }
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/587971/the-wrong-method-call-is-skipped-by-the-studio-and.html
VSTS ticketId: 901185_
_These are the original issue comments:_

Visual Studio Feedback System on 5/30/2019, 01:24 AM (26 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by ajcvickers** [comment]
@vsfeedback Find is intentionally defined to take `object` instances because the type of the key is not known. LINQ provides a more strongly typed API if you would prefer that.

**Comment by DkmS1953** [comment]
On the [documentation page](url=https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.findasync), the type of first parameter shows an array of objects. 
How the only object transferred to the method can be considered an array is a mystery.

**Comment by DkmS1953** [comment]
And in fact, of course, the FirstOrDefaultAsync (findPredicate) method was used.

**Comment by ajcvickers** [comment]
@DkmS1953 The method uses a [params array](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params) argument to allow a variable number of values to be passed. Multiple values are used for entity types with composite keys.

**Comment by DkmS1953** [comment]
Indeed, that is the way it is. However, to find out, you need to dig up the documentation quite deeply.
Thank you for the clarification.
