### ISSUE TITLE
StronglyTypedResourceBuilder invoked during Add-Migration if xproj file exists along side csproj

### ISSUE THREAD

**Issue by dozemunkeez** [aspnet/EntityFramework6#95]
I am tantalisingly close to being able to use the code first migrations tooling from within an ASP.NET Core solution with one strange issue.  
All projects in the solution are xproj + project.json based targeting net461 with the exception of a "dev only" csproj to be able to use the migration tooling.  The entity classes, migrations, DbConfiguration  and DbContext are shared in a xproj + project.json project for the application solution and a csproj  + {project name.}project.json project so that I don't have to link the .cs files into the csproj based project.  

In this setup I can add-migrations, however the {migrationid}.Designer.cs file get overwritten by the StronglyTypedResourceBuilder.   I say overwritten because when I inspected returned ScaffoldedMigration  from the CodeGenerator in my DbConfiguration, the DesignerCode property is what I would expect, however what gets written to disk resembles what one would expect to come from the StronglyTypedResourceBuilder .

The interesting part is if I remove the xproj project file from the folder, then the {migration id}.Designer.cs file matches the DesignerCode property value of the CodeGenerator.

e.g.

Without xproj file:
```
// <auto-generated />
namespace MyProject.EF.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test));
        
        string IMigrationMetadata.Id
        {
            get { return "201611020111493_test"; }
        }
    //...
    }
}
```

With xproj file present:
```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EF.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201611021542314_test {
 
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201611021542314_test() {
        }
       //...
    }
}
```

Is there any way to disable or prevent the StronglyTypedResourceBuilder from being invoked and still be able to keep the side by side project types?

**Comment by rowanmiller** [comment]
Closing this one out as `xproj` is being deprecated in favor of an MSBuild based project system, so this is not something we would spend time on. Generally speaking, the commands are not something that we have supported on .NET Core/xproj.
