### ISSUE TITLE
Non generic Fluent API

### ISSUE THREAD

**Issue by cdie** [aspnet/EntityFramework6#99]
Is this possible, like EF Core, to have a non-generic version of fluent API for mapping ? 
We already have designed our business objects with our own custom attribute (used for business and for data), and we want to proceed all by reflection to generate mapping...
I've tried with Code First Conventions, but some operations seems not possible to do everything this way (I can't ignore properties, I can't filter them exactly to give them a correct name, ...)

**Comment by rowanmiller** [comment]
Note for triage. We currently have `Ignore()` for entity types, but not properties.

@cdie can you elaborate on what you mean by `I can't filter them exactly to give them a correct name`?

**Comment by cdie** [comment]
@rowanmiller I don't really remember what I really meant when I said that ... I guess it was giving the property the db column name I want

**Comment by rowanmiller** [comment]
Configuring the db column name for each property looks like this (the example is just setting them to the lowercase version of the property name):

```c#
modelBuilder
    .Properties()
    .Configure(p => p.HasColumnName(p.ClrPropertyInfo.Name.ToLower()));
```

**Comment by rowanmiller** [comment]
**EF Team Triage:** Ignoring of properties is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue... we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.
